### ISSUE TITLE
AzureFileCopy additional argument /MT

### ISSUE THREAD

**Issue by ChSchmidt81** [Microsoft/vsts-tasks#1559]
I want to use the AzCopy parameter /MT but when I add /MT as additional argument I get an error:

[error]Upload to container: 'xxxx' in storage account: 'xxxx' with blobprefix: '' failed with error: '' For more info please refer to http://aka.ms/azurefilecopyreadme

**Comment by niadak** [comment]
/MT additional argument is not supported in AzureFileCopy Task. We have called out supported Additional arguments here http://aka.ms/azurefilecopyreadme, under "Parameters Of Ther task" -> 
"Additional Arguments" section.

**Comment by ChSchmidt81** [comment]
Is it planned to support more "Additional Arguments" in the next version?

**Comment by bryanmacfarlane** [comment]
+1

**Comment by niadak** [comment]
Hi ChSchmidt81,
Thanks for you valid feedback. The issue is that we take AzCopy Additional argument in a single parameter and used the same for both uploading to blob and downloading to VM. /MT is only supported for downloading to local machine. If you enable detailed logs in build definition by setting System.Debug = True you will see the bellow error
[2016/04/22 09:55:52][ERROR] The syntax of the command is incorrect. The "MT" parameter is only valid when downloading from an Azure Storage location to local file system.
I will create a work item to track this and will take it in appropriate priority order.
