### ISSUE TITLE
Simpler SqlServerDacpacDeployment task

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#1785]
Hi,

This isn't an issue per se, just some feedback.

I recently used the SqlServerDacpacDeployment task and was really confused by it.  I understand it now, but I was looking for a basic call to sqlpackage rather than a WinRM remote deployment.

In other words, I wanted sqlpackage.exe to be executed from my agent.  This task seems to be geared towards using WinRM to remotely execute on another machine.  I can see that would be useful to some people, but the only way I could get this to run how I wanted was to enter "localhost" in the machine variable and then supply a username and password to my local agent.  This seems a bit unnecessary.

I hope this makes sense.

thanks,

Greg

**Comment by codito** [comment]
Hi Greg,
Thanks for your feedback.

SqlServerDacpacDeployment task in its current form is targeting a *push* deployment model, where `sqlpackage.exe` needs to be run a production machine (not the agent machine).

The scenario you suggest is quite interesting, we do plan to support it in near future. [Release management planning update - 2016 H2](https://blogs.msdn.microsoft.com/visualstudioalm/2016/04/13/release-management-planning-update-2016-h2/) blog post has more details around agent based deployment.

I am closing this issue since it is already in team's backlog.

Thanks,
Arun

**Comment by wasabii** [comment]
I dont' think his issue was that it was "pull" or "push". It's that it uses WinRM, which is wholly unnecessary to executing SqlPackage.exe
