### ISSUE TITLE
One or more of the steps defined in the build does not have an associated task definition

### ISSUE THREAD

**Issue by pcoombe** [Microsoft/vsts-tasks#1816]
Same problem as #1170 
TFS 2015 Update 2.1, this now appears to be the default behaviour of our nightly scheduled builds for the last week.

Queuing builds manually does not cause the problem. I've resorted to PowerShell to script them.
[TFS-BuildAll - template.txt](https://github.com/Microsoft/vsts-tasks/files/292301/TFS-BuildAll.-.template.txt)

![2016-06-01 08_27_50-microsoft team foundation server](https://cloud.githubusercontent.com/assets/15317948/15692654/07f88376-27d3-11e6-84f5-214ff2852d9e.png)

Both TFS and the build agent have been rebooted. The previous issue mentioned this was a cache problem, is there any way I can clear this cache manually to try and rectify the issue.

**Comment by yaananth** [comment]
Are you using any tasks served by extensions? or any custom tasks uploaded?

**Comment by pcoombe** [comment]
Yes using both extensions and tasks uploaded by the TFS-CLi (tfx). 
Our c# builds generally follow this configuration

![2016-06-09 08_50_29-microsoft team foundation server](https://cloud.githubusercontent.com/assets/15317948/15913762/57183008-2e1f-11e6-9a45-e97b115f337b.png)

**Comment by yaananth** [comment]
What's your account name?

**Comment by pcoombe** [comment]
This is TFS not VSTS account

**Comment by sanyogitaranade** [comment]
What are the visibility filters in those tasks? If the visibility filter does not contain "Build" then it may be causing an issue while opening a build definition. Can you share the task.json if possible.

**Comment by pcoombe** [comment]
Visibility of ours is both, gitversion is just build. 
I really dont think that is the issue, it works all the time when it is built manually.
It also worked on Friday for the first time in forever, and we hadnt changed anything.
Then monday it was back to not working. 
Yesterday we installed update 3 and this morning it still isnt working.

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionTfsTask/task.json
[dnx_restore_task.txt](https://github.com/Microsoft/vsts-tasks/files/338157/dnx_restore_task.txt)
[dnx_test_task.txt](https://github.com/Microsoft/vsts-tasks/files/338155/dnx_test_task.txt)
[dnx_version_task.txt](https://github.com/Microsoft/vsts-tasks/files/338156/dnx_version_task.txt)

**Comment by sanyogitaranade** [comment]
Sorry for the late reply. I created an extension using the task jsons you gave and ran manual, triggered as well as scheduled builds and I did not face any issue. (The task failed because I did not have .ps1, but I did not get "one or more steps are not defined" error.) I tested this behavior on VSTS.

I have few questions.

1. When you are using the tasks, are you uploading them through extension or tfx-cli?
2. Are you facing this issue only on TFS 2015 Update 2.1, or on VSTS too? We recently have seen a lot of caching issues on TFS 2015 Update 2.1 and you may be hitting that.
3. Can you gather event logs and Fiddler trace when you load the task gallery? It will be very helpful to debug.

**Comment by pcoombe** [comment]
I only have the issue with scheduled builds, manual and triggered (CI) work without problem.

1a. custom tasks yes, are uploaded with tfx-cli
1b marketplace extensions no, they are uploaded via the managed extensions gallery

2. TFS 2015 Update 2.1 and now Update 3. We are not using VSTS.

3. Sorry do you mean instance/tfs/_gallery, or at the point of add task in a build definition?
There isn't anything going on in the event log when the builds are scheduled

**Comment by sanyogitaranade** [comment]
I mean at the point when you add a task to the build Definition.

**Comment by pcoombe** [comment]
[https://gist.github.com/pcoombe/df20e687e008bb1b8462f751997b8a63#file-tfs-boris-api-build-saz](url)

**Comment by sanyogitaranade** [comment]
I do not find anything particularly suspicious in Fiddler trace.

If you are still facing this problem, I think the best way further is  to gather event logs when your scheduled builds run. (I am assuming you are still facing this issue) They should hopefully contain some exceptions which will point us to the issue.

Since the tasks which are giving you problems are uploaded through tfx-cli, it is very less likely that it is a cache issue. But if you still want, you can recycle your ATs to reload the cache.

**Comment by bryanmacfarlane** [comment]
This is not an issue with any of the tasks in this repo.

**Comment by dbtfsbre** [comment]
While trying to manually queue an existing build, I faced this same message (running on TFS 2015 update 3). One of the steps (SCVMM) was greyed out. If I try to add a new SCVMM step to the build definition, I notice that this one does not exist any more in the library.

**Comment by rosieks** [comment]
I have similar issue. 

@bryanmacfarlane - where I can report suggestion to add more descriptive message than:

> One or more of the steps defined in the build does not have an associated task definition.
