### ISSUE TITLE
run powerShell on agent with different user context

### ISSUE THREAD

**Issue by rs38** [Microsoft/vsts-tasks#1972]
....similar to PowerShellOnTargetMachines. 

Or is it easily possible to use PowerShellOnTargetMachines to run a script on the local agent?

**Comment by bryanmacfarlane** [comment]
We copied this to our backlog.  If we add it will be a generic task control option (not just for ps).

**Comment by lukepuplett** [comment]
What's the status on this? This single feature is the base thing to have, it's a get out of jail since PS can do everything so PS + "run as" can do **everything**.

As aside, I would rather use PS for everything over built-in tasks since I prefer my own code and control. Tasks never quite do all you want the way you want.
