### ISSUE TITLE
dSYM file missing in Xamarin iOS app in VSTS

### ISSUE THREAD

**Issue by Ali-Syed** [Microsoft/vsts-tasks#1983]
Hi,

I am building the iOS app through VSTS using MacInCloud. I could see that its generating both ipa and dSYM file. In the test cloud step, for dSYM location, i tried passing **/*.dSYM or *.dSYM but it is not able to find it. I downloaded the artifact after the build. In the artifact, I can see the generated ipa file but could not locate dSYM file. 

Am I looking at the wrong place? I need the location of dSYM file for running the UITestScript on Test cloud.

**Comment by madhurig** [comment]
@Ali-Syed: Thank you for reporting this issue. The .dSYM is being generated but it is a folder and not a single file and the test cloud task is looking for files, so it is not picking it up. One workaround would be to identify the full path to the dsym folder on your build machine and set "Optional Arguments" in the "Advanced" section to "--dsym <path to dsym folder>"

I will work on a fix in the task.

Thanks,
Madhuri

**Comment by madhurig** [comment]
Fix merged, it will be deployed to Team Services in early November.

**Comment by TomSoderling** [comment]
This still seems to be an issue and we're in early Dec. Do you know what version of VSTS Build Agent this fix will go in?

**Comment by madhurig** [comment]
@TomSoderling: The fix was deployed to the service. There is no fix in the VSTS build agent and your version should work unless you have a very old agent. Are you unable to find the .dSYM from the Xamarin test cloud task?

**Comment by TomSoderling** [comment]
Oh I see. No, I was having an issue with the Copy Files task actually

**Comment by TimMarlow** [comment]
Hi There,

Also having some issues with dSYM files. If you can offer some advice either @TomSoderling  or @madhurig  that would be appreciated.

I have my builds working fine for .ipa, but when I add --dsym=true, to the optional args in the build task then the build stops with the following error: 

'MSBUILD: error MSBUILD0004: Too many project files specified'

I have tried just --dsym as well and that doesn't appear to generate them either. I have had a look at VSTS & Xamarin docs and cannot find it mentioned. Hope you can help!

@TomSoderling  for the copy are you using **/* rather than **/*.dsym?

**Comment by madhurig** [comment]
@TimMarlow: "--dsym=true" is not a valid msbuild argument, so passing it to XamariniOS task will not work. I see that "--dsym=true" is an mtouch argument but it doesn't look like Xamarin exposes it as a property to pass during build. 
In my Xamarin solution, I see the .dSYM is generated by just running the build with default arguments. I am building for device and not simulator. Are you targeting "Simulator"?

@TomSoderling: To copy the .dSYM you can have settings like this:
![image](https://cloud.githubusercontent.com/assets/3269636/21275838/9b7ed20c-c39c-11e6-83b2-4823133da6e9.png)

Thanks,
Madhuri

**Comment by TimMarlow** [comment]
Hi Madhuri,

Thanks for the response, I have create app package selected, but not build for simulator. When I was  building by default I noticed there was a line in the console output which said '--dsym=no', but that must be output rather than input.

In the mean time I will clean it all out and try another default build.
