### ISSUE TITLE
Please add support dotCover coverage report for Publish Code Coverage Results 

### ISSUE THREAD

**Issue by nelsonmorais** [Microsoft/vsts-tasks#2024]
Now Publish Code Coverage Results support only:
 JaCoCo
 Cobertura

Please add support for dotCover from JetBrains https://www.jetbrains.com/dotcover/

Meanwhile, is there's an alternative like a converter from dotCover to JaCoCo or Cobertura?

**Comment by allendm-msft** [comment]
Hi @nelsonmorais 

This is a valid feature ask and we do have it on our backlog but just haven't gotten to it yet. 

If you have an interest in contributing this feature into the project we would love to work with you on it. Reference [https://github.com/Microsoft/vsts-agent/tree/master/src/Agent.Worker/CodeCoverage](vsts-agent)

**Comment by nelsonmorais** [comment]
Hi @allendm-msft 

First of all , sorry for the late response.

I looked briefly for the repository link you have sent but I need to know where to start after that point :)

- What is needed to set up the dev environment to start working on this
- I don't know the structure of the dotCover CodeCoverage outputs so it might take me some time to get this
- If/When I have something working, how can I test it and see if it's Ok, do I need to deploy the code to some environment?

I don't have any time available on my working hours to work on this task, so my time is also limited, but let's see if I can help with something.

**Comment by allendm-msft** [comment]
Thanks for getting back @nelsonmorais. Let me try to answer your questions

>  What is needed to set up the dev environment to start working on this  

A basic setup would require vscode/sublime/editor + git tools + .net core + the source repo
[See here for details][1]

> I don't know the structure of the dotCover CodeCoverage outputs so it might take me some time to get this  

Thats true. I didnt spot the xsd file published by atlassian anyplace in public either. since this is a proprietary format you would have to refer other open source tools that support it or you can consume the xsd in your task from an install of dotcover - making it a requirement for anyone wanting to use the feature

> If/When I have something working, how can I test it and see if it's Ok, do I need to deploy the code to some environment?  

You can upload the task to your vsts account or onprem tfs server for testing. [See here for details][1]

[1]: https://github.com/Microsoft/vsts-agent/blob/master/docs/contribute.md

**Comment by atinb** [comment]
Unfortunately, this is not in our current plans.

**Comment by GaTechThomas** [comment]
The CodeCoverage link earlier in this conversation is not the same as the text. Here's a working link:

https://github.com/Microsoft/vsts-agent/tree/master/src/Agent.Worker/CodeCoverage
