### ISSUE TITLE
AzureRMWebApp Deployment - Error: Source does not support parameter called 'IIS Web Application Name'

### ISSUE THREAD

**Issue by Morgma** [Microsoft/vsts-tasks#2088]
All I have set are: AzureRMSubscription, WebApp Name and Package (path to zip). 

The exception below is thrown; no files are transferred to the Azure Web App. However, the task reports completing successfully.

2016-07-15T18:55:56.2452591Z Running msdeploy command: `n`t"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="C:\a\ea5e3f730\**\website.zip" -dest:auto,ComputerName="https://****.scm.azurewebsites.net:443/msdeploy.axd?site=****",UserName="$****",Password=****,AuthType="Basic" -setParam:name="IIS Web Application Name",value="****" -enableRule:DoNotDeleteRule
 
2016-07-15T18:55:57.4146077Z Error: Source does not support parameter called 'IIS Web Application Name'. Must be one of ().

**Comment by pascalberger** [comment]
@Morgma You need to make sure that the WebDeploy package which you want to deploy has a parameter called `IIS Web Application` (this is a hardcoded requirement [here](https://github.com/Microsoft/vsts-tasks/blob/22f50ec6122c83d7192d0deb6ae00c18cc48941f/Tasks/AzureRmWebAppDeployment/Utility.ps1#L103)). It seems like your WebDeploy package doesn't contain any parameters. 

But I also don't have any clue what was the reasoning behind the decision to make this parameter required, since I don't see any technical requirement. Would be nice to have someone from MSFT to comment on this.

**Comment by mvvsubbu** [comment]
Web App deployment task deploys to the website name given in the task UI. So here for the task inputs are web deploy package and website name. We wanted to deploy to the website without having to interpret the web deploy package structure and hence we are depending on the default parameter "IIS Web Application Name". We are more than happy if you could contribute to the task which can remove this dependency not breaking our above principle of not interpreting web deploy package. 

As you might be already aware this task is removed to extension and this is no longer updated and hence you can send your PR to https://github.com/Microsoft/vsts-rm-extensions

**Comment by pascalberger** [comment]
@mvvsubbu This is about the AzureRMWebApp task not the IIS Web App Deployment task. Is this task now also deprecated here and will be moved to the RM Extensions repo? Currently I don't see it added there.

**Comment by onovotny** [comment]
I'm also seeing this...it's not clear what's going on here?

**Comment by onovotny** [comment]
Here's the kicker...I think the confusion is that we're talking about the AzureRM tasks, not the IIS WinRM tasks.
