### ISSUE TITLE
Task Versioning

### ISSUE THREAD

**Issue by RDalziel** [Microsoft/vsts-tasks#2131]
I can't seem to find any references as to how this works, can someone point me in the right direction?

I'd like to know how versioning of tasks effects how the build process pulls them down.

Specifically - what changes will effect existing build templates and which will require the build task to be re-added to the templates?

**Comment by brettjacobson** [comment]
I'm just an outside observer, but, it seems relatively random!  This is based on my experience with on-prem TFS 2015 Update 2; no idea if it applies to VSTS in the same way.  I believe the *theory* is that a subsequent build after an update the latest registered Task will be used, *but* this is not what experience has shown.  My experience says that "sometimes it uses the latest version... eventually."  I've found (probably coincidence, and not really the solution) that "editing the build definition and CTRL F5-ing the window a couple times" seems to get it to use my latest task.

Now, one thing I know for certain is that if you change parameter names or default values, that *requires* the task to be removed/readded as the inputs are only parsed during add and not updated just because you edited the build definition.  But I've also gotten in the habit of removing/readding the task as that seems to "force" it to use the latest task version so I dont have to wait for it to decide it will use the latest version on its own.

I hope I'm wrong and the system is actually more sophisticated about updates, but this has been my experience.

**Comment by RDalziel** [comment]
That's roughly been my experience Brett - I'd hoped there'd be some smart logic on the Major/Minor/Patch versions to control whether it's a forced up date.

Perhaps Patches and possible Minor are Forced with Major being a remove re-add job.

**Comment by bryanmacfarlane** [comment]
The backend supports pinning definitions to versions but the experience wasn't settled on.

The build server resolves the latest version of the task *at queue time* to a fully qualified version and the message to the agent contains that full version.  The agent is dumb - I have that task/version on disk or not.  If not, it downloads it.  Versions are immutable on the service.  

In the box tasks are deployed with the database servicing of the service or the on-prem upgrade.

Extensions are a different story.  If you are installing an update there's some async work to install the tasks in the build backend.  So with extensions you can have some delay.  There's also been some extension bugs where the task didn't get install and if we detect that at certain scenarios (opening task UI, running a build etc...) when we do licensing checks, we'll queue background work to install.

But once a task is installed via servicing or extension (eventually) the build server will resolve latest at queue time.

**Comment by RDalziel** [comment]
Ah ! So tasks which are updated via extensions will take longer to become "live" than ones that are added via the commandline tool!

Thanks for the details response, Bryan.
