### ISSUE TITLE
NuGet Installer/Publisher tasks do not work behind a proxy

### ISSUE THREAD

**Issue by mjacobs80** [Microsoft/vsts-tasks#2146]
## **Environment** 
VSTS account name? http://nchcorporation.visualstudio.com
Version of your agent: 2.104.0
OS of the machine running the agent: Windows Server 2012 R2

## **What's not working?** 
NuGet Package Installer task is failing.

Our corporate environment requires a proxy server for our agent servers to access our VSTS account. This is configured with no authentication. We know this to be working as the get sources build step is working as expected.

The error we recieve is Error: connect ECONNREFUSED 23.98.150.230:443.

The build step log with debug enabled and also the agent _diag logs are attached.

[Worker_20160725-120940-utc.log.txt](https://github.com/Microsoft/vsts-tasks/files/387862/Worker_20160725-120940-utc.log.txt)
[3_Restore.packages.txt](https://github.com/Microsoft/vsts-tasks/files/387863/3_Restore.packages.txt)

**Comment by jmyersmsft** [comment]
The issue is understood and we are working on a hotfix

**Comment by jmyersmsft** [comment]
This should have been mitigated by #2142 + #2149, which were deployed last night.

**Comment by zjrunner** [comment]
We had moved from powershell to node tasks to start providing better, consistent multi platform support in packaging and missed that node does not have any proxy resolution built in unlike powershell.  We're working around the need to make one-off http calls before invoking nuget until the agent provides proxy configuration and can hand out a configured http client for our use.

**Comment by igorguga** [comment]
Hi guys, this issue was solved?? I'm experiencing the same problem with a build agent behind a proxy trying to connect to VSTS Package management... We configured a .proxy file for the agent, the get sources goes successfull but the Nuget restore gives "connect ECONNREFUSED 191.234.179.224:443" error.

**Comment by Onefox** [comment]
@igorguga  i have the same problem

**Comment by cindoum** [comment]
Same problem here, i cannot install nuget 4.5 as it doesnt seem to be using the proxy. Any update?

**Comment by jmyersmsft** [comment]
@igorguga @Onefox @cindoum can you provide more information in a new issue? This is unlikely to be the same underlying cause at this point.

**Comment by cindoum** [comment]
My issue is like the original one. I have a task Nuget tool installer. This task work on my computer  (which has no proxy) but cant seem to be working on a private build server behind a corporate proxy.

The .proxy seem to be working for the agent as i have been able to install the agent and the downloading of the source code is working.

Here the log without setting variable env http_proxy:
[3_Install nuget.exe.txt](https://github.com/Microsoft/vsts-tasks/files/1575646/3_Install.nuget.exe.txt)

When the proxy is set (though the env variable, it fail but without any error:
[3_Install nuget.exe.txt](https://github.com/Microsoft/vsts-tasks/files/1575657/3_Install.nuget.exe.txt)

Any clue?

**Comment by hebu** [comment]
I have the same issue as @cindoum and would be thankful for any hint.

**Comment by zjrunner** [comment]
First please verify you are using the most recent major version of the task (there is a V0 and a V1 major version, and the V1 has the basic proxy support).  Do the same for the NugetCommand task, or move to the newer [NugetAuthenticate](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/NuGetAuthenticateV0) task for auth, set your env vars or configure nuget for a proxy via nuget.exe commandline options and call nuget directly via script.  We're going to be encouraging folks move away from the 'heavy' nugetcommandline tasks to the auth+script because the direct control of nuget has a lot of advantages.

**Comment by hebu** [comment]
Thanks @zjrunner – I could not find find the V1 taswks, so I'll do an update to TFS 2018 Update 3.2 (incl. new Build Agents) first to see what happens. We're currently using Build Agent 2.122.1.

**Comment by hebu** [comment]
Works like a charm with TFS 2018 Update 3.2 and Build Agents 2.136.1 - next time I better install the latest TFS update from the beginning before losing so many days ...
