### ISSUE TITLE
NuGetInstaller 0.2.0 Issue With VSTS Package Management Addon

### ISSUE THREAD

**Issue by rjosborne** [Microsoft/vsts-tasks#2152]
Hi,

We are using the VSTS package management addon to host a number of packages, which are a key part of our build process.

Up until last night, everything worked just fine. We have a nuget.config checked into our source tree which provides the username and access token required by the build to access the package management source.

The config for the task in the build process specifies the path to this nuget config file within the source tree and this used to work perfectly.

As of last night (when the NuGetInstaller task was updated from 0.1.32 to 0.2.0), this has stopped working - we now get an error stating "Key not valid for use in specified state"

Nothing else has changed since it worked the previous day, so I assume this must somehow be related to the 0.2.0 update. Any help with this would be much appreciated as I'm not sure how to resolve this.

Thanks.

**Comment by bryanmacfarlane** [comment]
I believe they are aware of this and addressing now.

**Comment by jmyersmsft** [comment]
@rjosborne this doesn't look familiar, can you share more from your logs?

**Comment by rjosborne** [comment]
Hi,

Please see the two attached log files - "legacy log" is with the build agent installed exactly as it was the day before - the only difference from when it previously worked is the elements which self updated (including the NuGetInstaller task) overnight last night.

"New log" is after I installed a second build agent earlier this evening with the latest version of the agent in an attempt to rule out any issues with using the 0.2.0 task with what I assume is now the legacy build agent.

For clarity, we are using an in house installation of the build agent hosted on a Windows server 2008 R2 box as opposed to a cloud hosted agent.

[legacy log.txt](https://github.com/Microsoft/vsts-tasks/files/389421/legacy.log.txt)
[new log.txt](https://github.com/Microsoft/vsts-tasks/files/389422/new.log.txt)

**Comment by jmyersmsft** [comment]
@rjosborne I think I know what is going on here. I suspect that if you remove the username and password from your nuget.config it will work. I will follow up with why I suspect that will work later today, and we will try to improve the error messaging there.

**Comment by rjosborne** [comment]
@jmyersmsft many thanks for your help - I've just tested your suggestion and it now works again.

**Comment by zjrunner** [comment]
Looks to have been a bad/invalid username/pass.  It broke on the update because we stopped clobbering the user provided creds to VSTS Packaging with the official set of creds.  It is fixed live now because we went back to clobbering.  In the next release, it will still default to clobbering but users will be able to opt-in to the nuget 3.5.1 flow which will use our Cred Provider to provision credentials just in time.  In this flow any user-provided credentials will be honored by nuget even to the VSTS Packaging service (no clobbering).  It is best to *not* provide credential to the VSTS Packaging service urls in nuget.config and to let the build identity carry forward instead.
