### ISSUE TITLE
bug in cURLUploader.ps1

### ISSUE THREAD

**Issue by StijnVA** [Microsoft/vsts-tasks#2202]
If you are using wildcards in a cUrl task, the _cURLUploader.ps1_ generates a command like:

`curl --stderr - -T {"file1","file2"} destination`

This is not correct, curl will give an error saying **_Couldn't resolve host "file2"_**

the appropriate command should be:

`curl --stderr - -T "{file1,file2}" destination`

If you change line 54 in  _cURLUploader.ps1_ from
 `$uploadFiles = '{"' + [System.String]::Join('","', $foundFiles) + '"}'`
to
 `$uploadFiles = '"{' + [System.String]::Join(',', $foundFiles) + '}"'`

it works fine.

**Comment by bryanmacfarlane** [comment]
Thanks!  Want to do a PR?

**Comment by DavidStaheli** [comment]
It turns out this is fixed in the TypeScript version of this task and the .ps1 version no longer exists.  StijnVA, are you able to update to the new version of the task?  Can I help you do that?

Example I see with the TypeScript version of the task:
`curl -T {C:/a/1/s/Tractionware.Services/Accounts/AccountsService.cs,C:/a/1/s/Tractionware.Services/Accounts/AccountsServiceDataSql.cs,C:/a/1/s/Tractionware.Services/Accounts/ApplicationConstants.cs,C:/a/1/s/Tractionware.Services/Accounts/AuthTokenDecoding/IAuthTokenDecoder.cs....`

**Comment by StijnVA** [comment]
@DavidStaheli yes please. If you could point me to a guide for doing so I would be great-full.

**Comment by DavidStaheli** [comment]
Sorry for the delay, @StijnVA.  Here are the instructions.  Please let me know if you encounter any trouble.

1.	Ensure that your username is in the top-level “Agent Pool Administrators” group to manipulate build tasks.
2.	If your client machine does not already have it, install Node.js 4.x and npm 2.14.20 or later.
3.	If your client machine does not already have it, install the TFS Cross-platform Command Line Interface: `npm install -g tfx-cli`
4.	Extract the attached ZIP to a local directory: [cURLUploader.zip](https://github.com/Microsoft/vsts-tasks/files/409397/cURLUploader.zip)
5.	Login and upload the extracted directory to TFS:

`tfx login --service-url https://yourTFSServer/tfs`

`tfx build tasks upload --task-path myExtractedFolderName`

You should see output similar to this:

> TFS Cross Platform Command Line Interface v0.3.22
> Copyright Microsoft Corporation
> Task at /home/myUsername/myExtractedFolderName uploaded successfully!
