### ISSUE TITLE
RuntimeException when use sonar.analysis.mode=preview

### ISSUE THREAD

**Issue by NikitaEgorov** [Microsoft/vsts-tasks#2249]
```
System.Management.Automation.RuntimeException: Cannot determine if the analysis has finished in order to break the build. Possible cause: your SonarQube server version is lower than 5.3 - for more details on how to break the build in this case see http://go.microsoft.com/fwlink/?LinkId=722407 ---> System.Management.Automation.RuntimeException: Cannot determine if the analysis has finished in order to break the build. Possible cause: your SonarQube server version is lower than 5.3 - for more details on how to break the build in this case see http://go.microsoft.com/fwlink/?LinkId=722407
--- End of inner exception stack trace ---
at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
at Microsoft.TeamFoundation.DistributedTask.Handlers.PowerShellHandler.Execute(ITaskContext context, CancellationToken cancellationToken)
at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.RunTask(ITaskContext context, TaskWrapper task, CancellationTokenSource tokenSource)
```

Use TFS 2015

**Comment by bgavrilMS** [comment]
Hi Nikita, 

Are you using vanilla TFS 2015 or have you installed any update to it ?

**Comment by NikitaEgorov** [comment]
Hi @bgavrilMS 

I use TFS 2015 Update 2.1

**Comment by bgavrilMS** [comment]
Hi Nikita, 

When you run a SQ analysis in either preview mode or in incremental mode, the quality gate is not evaluated. However the task is trying to query the quality gate in order to break the build - and so it fails. 

Note that if you run the build as a PR build, we'll automatically run the SQ analysis in incremental mode and post the issues as code review messages. Let me know if you'd like more details about this. 

Otherwise, may I ask why you want to run in preview mode?

**Comment by NikitaEgorov** [comment]
I want to break pull request build if SQ quality gate not passed

But i don't wont change current SQ state because PR not merged 

And I want to use preview mode to validate PR

**Comment by bgavrilMS** [comment]
Hi Nikita, thank you for your quick reply.

You cannot break the PR build if the SQ quality gate has not passed, because on PR builds we automatically run the SQ analysis in incremental mode (very similar to preview mode). In both incremental and preview mode, the quality gate is not computed! This is a SonarQube limitation. 

I suggest you don't change the sonar.analysis.mode (this is not supported via the tasks) and rely on the PR build to inject code analysis issues as code review comments. You don't need to do anything for this functionality, but take a look at [this blog post ](https://blogs.msdn.microsoft.com/visualstudioalm/2016/06/02/sonarqube-code-analysis-issues-integration-into-pull-requests/ ) we wrote for more details.

**Comment by NikitaEgorov** [comment]
@bgavrilMS could I create Branch policy to Block pull request if PR get Code Analysis issues?

**Comment by bgavrilMS** [comment]
Hi Nikita, 

As far as I'm aware, branch policies are not 3rd party extensible at this point. @chrisrpatterson can confirm. 

We did consider having a more general policy where the PR is blocked until all comments are resolved, however the experience wasn't great, especially when many low priority code analysis issues are discovered. 

If you use the same build both for CI and PR build, you should get pretty close to what you want though. You'll get code analysis issues as messages in the PR. After you merge the PR, the CI build will be triggered and it will fail if the quality gate fails, altering the developer to fix it.

**Comment by chrisrpatterson** [comment]
Branch policies are not currently extensible but I do think the team has some thinking in that area.  The best place to indicate you want this is on uservoice https://visualstudio.uservoice.com/forums/330519-team-services.
