### ISSUE TITLE
ServiceFabricDeploy task does not support Create action for new deployments

### ISSUE THREAD

**Issue by mikanyg** [Microsoft/vsts-tasks#2331]
In order to deploy multiple instances of the same application using different application names, defined in custom application parameter files, the usage of Publish-NewServiceFabricApplication cmdlet from the SF SDK should support the Create action. 

The current task does not support this.

**Comment by ericsciple** [comment]
i'll ping Matt/Eric J.

**Comment by kmkumaran** [comment]
@EricJizbaMSFT to take a look.

**Comment by MikkelHegn** [comment]
Hi Mikael,

A few follow-up questions.
- What are you trying to achieve asking for this functionality?
- Are you referring to the use of the VSTS Service Fabric Application Deployment task (https://www.visualstudio.com/en-us/docs/build/steps/deploy/service-fabric-deploy), or functionality from within Visual Studio?

Thanks.

**Comment by mikanyg** [comment]
Hi Mikkel

I am refering to the service fabric deploy task for VSTS, that I suggested on uservoice some months ago. As I can see in the repo in the deploy.ps1 file, the task is basically wrapping cmdlets found in the Service Fabric SDK.

I was playing around with deploying multiple instances of the same application to a cluster, using different publish and application parameter files, but the 2nd deployment task fails since the application type is already registered and in use (done by the first deployment task in my pipeline). Doing some digging I found that I could use the cmdlet Publish-NewServiceFabricApplication with -Action Create to deploy without registering again.

It would be cool if some of these more advanced scenarios showed up in the corresponding VSTS deployment tasks for service fabric.

(Still crossing fingers for true differential packaging coming to VSTS)

**Comment by MikkelHegn** [comment]
Publish-NewServiceFabricApplication.ps1 is a script we're using for VS and VSTS scenarios, that wraps the whole publishing process of Service Fabric applications. The cmdlets we are wrapping (via a set of SDK provided ps-modules) from the Service Fabric runtime are the following:

1. Copy-ServiceFabricApplicationPackage - Copies a Service Fabric application package to the image store.
2. Register-ServiceFabricApplicationType - Registers a Service Fabric application type.
3. New-ServiceFabricApplication - Creates a Service Fabric application.

(We are doing additional stuff, but the above are the central pieces).

For your specific scenario, you basically only need to run the New-ServiceFabricApplication cmdlet. Since the SF SDK is installed on the hosted build agents, you should be able to run this through a generic PowerShell task in VSTS. https://msdn.microsoft.com/en-us/library/mt125913.aspx

**Comment by mikanyg** [comment]
Hi Mikkel

Thanks for the clarification. My next step was actually to use the powershell task. But since I found the limitation when playing around with the new SF deploy task, I thought it might be a use case that would be easy to bring into the task itself.

Could be an additional option that could be parsed into the cmdlets.

**Comment by kmkumaran** [comment]
Based on the above response, I am marking this thread as closed. Please feel free to reopen if you need further assistance.
