### ISSUE TITLE
Distributing tests based on number of machines

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#2370]
Guys, I found this [article  ](https://blogs.msdn.microsoft.com/visualstudioalm/2016/06/21/remote-testing-distributing-tests-based-on-number-of-machines/) 
I use Build Agent Version 2.105.2 also use  tasks DeployVisualStudioTestAgent ver. 1.0.36 and  RunDistributedTests ver. 1.0.41

I have single assembly include 100 tests  also  have group machine 4  VMs.
I set "customSlicingEnabled"
![2016-08-30 17_47_14-remote testing distributing tests based on number of machines _ microsoft appl](https://cloud.githubusercontent.com/assets/18549964/18093833/f43d9ae4-6ed9-11e6-8722-d8adb75b141a.png)

Result I see runs my test only one machine.
Please suggest what I am doing wrong.

**Comment by acesiddhu** [comment]
@kardinal3000 do you see any warning in build logs?

**Comment by kardinal3000** [comment]
Yep, 
##[warning]Update the build agent to run tests with uniform distribution. If you are using hosted agent there are chances that it is still not updated, so retry using your own agent.

**Comment by acesiddhu** [comment]
We have identified this as a bug in core clr (I assume you are using coreclr agent). if you are using any runsettings/testsettings we might be able to give a workaround till we get a fix. Let me know if you are using runsettings/testsettings

**Comment by infertum** [comment]
Hi acesiddhu. 
I want to describe more deeply use case with distributed test execution.

We are using ms test framework.
We have 100 Web driver tests in one assembly.

We want run tests in group of test agents, using test plans.
Will this approach work for ui webdriver tests ?

The main idea to decrease time of webdriver test execution.

Also as far as I understand we can decrease time of running non-ui tests(unit tests, rest api functional tests, integration tests) by adding parallelization params in testsettings file. 

But this approach with testsettings file will not work for UI tests.

Am I right or I missed something ?
Maybe you can suggest us something?

**Comment by kardinal3000** [comment]
Thanks for answer! I hope you will fix it, as soon as possible. **Yes we are using runsettings/testsettings on the some parts of tests. I will be appreciated if you shared your workaround.** 
But, usually we use Test Agent and RunDistributionTests tasks together. Probably your workaround not be useful, just my thoughts

**Comment by acesiddhu** [comment]
The issue will be fixed in next coreclr agent release. Till then if you want to workaround this you need to add this in your settings file

**Runsettings:** add the bold part in your runsettings

<RunSettings>
<RunConfiguration>
**<CustomSlicing enabled="true" />**
</RunConfiguration>
</RunSettings>


**TestSettings:** add the bold part in your TestSettings
<TestSettings name="TestSettings1" id="5e7c73a5-8e38-4d1e-a402-459dfab945b6" xmlns=\"http://microsoft.com/schemas/VisualStudio/TeamTest/2010\">
                <Execution hostProcessPlatform=\"MSIL\">
                **<CustomSlicing enabled=\"true\" />**
                </Execution></TestSettings>

**Comment by acesiddhu** [comment]
I suggest if you want to try the workaround make a temporary copy of the setting files and use that in Build flow till new agent is released.

**Comment by kardinal3000** [comment]
@acesiddhu  just clarify  in which part I should add the bolt part? and what does it mean bold part
 "


"
I see empty part.

This is my TestSettings1.testsettings
```
<?xml version="1.0" encoding="UTF-8"?>
<TestSettings
  id="5757f364-edaf-4350-9847-1da89fc47b76"
  name="TestSettings1"
  enableDefaultDataCollectors="false"
  xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Description><!--_locID_text="Description1"-->These are default test settings for a local test run.</Description>
  <Deployment enabled="false" />
</TestSettings>

```

**Comment by acesiddhu** [comment]
Can you try this
```
<?xml version="1.0" encoding="UTF-8"?>
<TestSettings
  id="5757f364-edaf-4350-9847-1da89fc47b76"
  name="TestSettings1"
  enableDefaultDataCollectors="false"
  xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Description><!--_locID_text="Description1"-->These are default test settings for a local test run.</Description>
  <Deployment enabled="false" />
<Execution>
<CustomSlicing enabled="true" />
</Execution></TestSettings>
```

**Comment by kardinal3000** [comment]
Thanks a lot for workaround! 
But I observe strange behavior. I use TFS on-premise. I have two VMs (with two test agents **TFSTA8** and **TFSTA7**) when I run my tests they are running only one VM but twice. The second VM did not used

![untitled](https://cloud.githubusercontent.com/assets/18549964/18309885/3c147556-7504-11e6-9ae0-afd682405b16.png)

![1](https://cloud.githubusercontent.com/assets/18549964/18309888/472831a8-7504-11e6-973a-ec78d960b48f.png)

What could it be?
Use BA 2.105.5

**Comment by geoffstew4** [comment]
After adding CustomSlicing to RunSettings we are getting the error below.  If I don't specify the runsettings file then tests run fine but don't distribute across machines.  We also get this error when we try to run using TestPlan instead of TestAssembly.  Any guidance on what to check?


2016-09-08T16:04:02.9480498Z ##[warning]Update the build agent to run tests with uniform distribution. If you are using hosted agent there are chances that it is still not updated, so retry using your own agent.

5 2016-09-08T16:04:03.0886726Z DistributedTests: Environment WinRm Protocol HTTP.
6 2016-09-08T16:04:03.0886726Z DistributedTests: Trying to unregister TestAgents from Test Machines
7 2016-09-08T16:04:03.1667965Z DistributedTests: Task 'UnRegisterAgent' on machine 'spo-iap-auto-03.itron.com:5985' is being run
8 2016-09-08T16:04:03.1667965Z DistributedTests: Task 'UnRegisterAgent' on machine 'spo-iap-auto-02.itron.com:5985' is being run
10 2016-09-08T16:04:03.1667965Z Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
11 2016-09-08T16:04:03.1667965Z Parameter name: deploymentMachine.Credentials.UserName
12 2016-09-08T16:04:03.1667965Z    at Microsoft.VisualStudio.Services.DevTestLabs.Definition.ValidationHelpers.ValidateNullOrWhitespaceParameter(String paramName, String paramValue)
13 2016-09-08T16:04:03.1667965Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunPowerShellAsync>d__15.MoveNext()
14 2016-09-08T16:04:03.1667965Z --- End of stack trace from previous location where exception was thrown ---
15 1016-09-08T16:04:03.1667965Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16 2016-09-08T16:04:03.1667965Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
17 2016-09-08T16:04:03.1667965Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunPowerShellAsync>d__14.MoveNext()
18 2016-09-08T16:04:03.1667965Z    --- End of inner exception stack trace ---
19 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
20 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
21 2016-09-08T16:04:03.1667965Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DtlMachineDeploymentHelper.<>c__DisplayClass33_0.<WaitTillCompletion>b__0(KeyValuePair`2 deploymentTask)
22 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
23 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
24 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
25 2016-09-08T16:04:03.1667965Z    --- End of inner exception stack trace ---
26 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
27 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
28 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
29 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
30 2016-09-08T16:04:03.1667965Z    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
31 2016-09-08T16:04:03.1667965Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DtlMachineDeploymentHelper.WaitTillCompletion(Dictionary`2 taskList, String friendlyNameOfTask, Boolean addToErrorMachines)
32 2016-09-08T16:04:03.1667965Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.DtlMachineDeploymentHelper.<>c__DisplayClass31_0.<RunTaskViaDtl>b__0()
33 2016-09-08T16:04:03.1667965Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
34 2016-09-08T16:04:03.1667965Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
35 2016-09-08T16:04:03.1667965Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
36 2016-09-08T16:04:03.1667965Z    at System.Threading.ThreadHelper.ThreadStart()

**Comment by acesiddhu** [comment]
@kardinal3000 the new agent is released https://github.com/Microsoft/vsts-agent/releases/tag/v2.105.6 can you try with that. you can undo the changes you did in runsettings and testsettings

**Comment by acesiddhu** [comment]
@geoffstew4 The error is not related to this. Can you try using the new agent that is released https://github.com/Microsoft/vsts-agent/releases/tag/v2.105.6 and undo the changes you might have done in runsetting/testsetting

**Comment by SatishThareja** [comment]
@kardinal3000 Did your issue get resolved after using the build agent shared by @acesiddhu .

**Comment by kardinal3000** [comment]
@SatishThareja I used the last version Build Agent 2.106. And Unfortunately, I have the same issue as  I wrote above.

I observe strange behavior. I use TFS on-premise. I have two VMs (with two test agents TFSTA8 and TFSTA7) when I run my tests they are running only one VM but twice. The second VM did not used

**Comment by SatishThareja** [comment]
@kardinal3000 can you share the following logs and send it to devops_tools@microsoft.com:
- build logs
- c:\Dtalogs\DtaExecutionHostlog from both agent machines (clearing off the logs for previous runs)
Addtionally can you let us know if:
- Same tests are executed twice or is it a different set?
- Are both machines used if you do not enable Custom Slicing?

**Comment by SatishThareja** [comment]
@kardinal3000 Please share the logs to help us debug this issue.

**Comment by SatishThareja** [comment]
Closing this issue due to no response.
