### ISSUE TITLE
ServiceFabricUpdateAppVersions.ps1 - Why only allowed to append version number ?

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/vsts-tasks#2377]
We use this project to version our Assemblies and drive our packaging versions to [GitVersion](http://github.com/GitTools/GitVersion) and we would like to use the calculated value from $(Gitversion_NuGet2) variable as our version number for our Service Fabric App Versions.

What's the thinking about only allowing appending within the VSO Task ? Why should it support replacing the entire value ? It just a text field as I understand, it doesn't even care if the value is semver right ?

I'm worried I've missed something about ServiceFabric.

**Comment by ericsciple** [comment]
@EricJizbaMSFT

**Comment by bryanmacfarlane** [comment]
Azure scenario.  @EricJizbaMSFT contributed.  RM should sponsor work

**Comment by EricJizbaMSFT** [comment]
You are correct, the version value does not need to be semver.

We knew there would be a million different ways to version and wanted to keep the task simple to start with. We chose appending rather than replacing because we believed it was less confusing and more consistent with existing behavior.

Before I commit to fixing this, I'd like to understand a little more why you want to do it. I glanced at your link, but I'm still not that familiar with GitVersion. What benefits does it provide you in this specific case? What would be the downsides of using '1.0.0.$(Gitversion_NuGet2)'?

**Comment by johnkattenhorn** [comment]
Hey @EricJizbaMSFT, thanks for responding. 

The only downside I can think of is a nice to have, because we use GitVersion to also version our assemblies it would be nice and neat if they matched based on our commit history.

We also intentionally leave our assembly versions and SF versions at 0.0.0 to signal to us if we see them in the 'wild' that someone has done something bad and not followed process.

Personally I would have left it to the consumer of the VSTS Task to have control over the value, it would have been easy enough to have done the append in a task variable itself if that was the desired behaviour.

Last thanks again for the efforts though, for people like me who PowerShell isn't even a second language it's good to have as much support as possible on the VSTS tasks :-)

**Comment by EricJizbaMSFT** [comment]
Sounds good - we'll add an option to fully replace the version value.

@ericsciple or @bryanmacfarlane I don't have permissions to change labels or assign this to myself, but feel free to do whatever you want to mark this 'approved'. Btw, what does 'RM' stand for?

**Comment by johnkattenhorn** [comment]
@EricJizbaMSFT - That's awesome! Looking forward to trying it out! Let me know if there's anything we can do to help.

**Comment by ericsciple** [comment]
Fix will roll out with m107 which starts to roll in a couple weeks.
