### ISSUE TITLE
AzureRMWebAppDeployment: Virtual Application Parameter is Not Used Properly

### ISSUE THREAD

**Issue by mclark1129** [Microsoft/vsts-tasks#2399]
I am attempting to deploy a ASP.NET Core site to an Azure App Service under a Virtual Application.  I have provisioned an Azure App Service with a virtual app directory **api/**

I configure my AzureRM Web App Deployment Task as follows (Relevant Config Only):

**Web App Name:** my-azure-app-service
*Equates to the root of my app: http://my-azure-app-service.azurewebsites.net/*

**Virtual Application:** api

The application still is deployed to the root application.  If I try to specify the virtual directory in **Web App Name** then I am given an error that the web app could not be found.

It looks like the culprit is in the resulting MS Deploy command that is generated.
`"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="D:\_work\3874f4573\publish.zip" -dest:auto,ComputerName="https://my-azure-app-service.scm.azurewebsites.net:443/msdeploy.axd?site=my-azure-app-service",UserName="$my-azure-app-service",Password=****,AuthType="Basic" -setParam:name="IIS Web Application Name",value="my-azure-app-service/api" -enableRule:AppOffline`

I can create the desired behavior by using publish from Visual Studio.  This results in the following MS Deploy command:

`C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:manifest='<SomeStuff>' -dest:manifest='<SomeStuff>',ComputerName='https://my-azure-app-service.scm.azurewebsites.net/msdeploy.axd?site=my-azure-app-service/api',UserName='$my-azure-app-service',Password='{PASSWORD-REMOVED-FROM-LOG}',IncludeAcls='False',AuthType='Basic' -verb:sync -enablerule:AppOffline -enableRule:DoNotDeleteRule -retryAttempts:20]`

I think the key difference between the two commands is the url specified for **ComputerName**

Task: `https://my-azure-app-service.scm.azurewebsites.net/msdeploy.axd?site=my-azure-app-service`
VS: `https://my-azure-app-service.scm.azurewebsites.net/msdeploy.axd?site=my-azure-app-service/api`

I believe if the task included the Virtual Application parameter when constructing **ComputerName** this would work as expected.

`

**Comment by mclark1129** [comment]
**Update**

My theory about the URL was not correct, even after modifying URL in the task it was still deployed to the root.  It looks like you can control the file structure of the deployment if you build it into the artifact itself because the task uses the `dest:auto`.

E.G. - If I want to host an application under an application called /api/v1, I will need to create the build artifact with the files under /api/v1.  This works, but is not flexible if you're in a situation where you want to control the application structure by environment, or if you modified the release plan and didn't need a new build of the artifact.  Seems like the artifact itself wouldn't need to contain knowledge about the root file structure of the intended deployment

**Comment by vincentdass** [comment]
@mclark1129 , Can u share the version of AzureRmWebAppDeployment ?
APS.Net Core is not currently supported in Azure RM Web App Task. It will be supported in upcoming major version.

**Comment by mclark1129** [comment]
We're currently using 1.0.17.

**Comment by vincentdass** [comment]
@mclark1129 

dest:auto works fine for webapp as virtual application if your package is being generated by VisualStudio. But if package is being generated by some other way msdeploy is not able to understand it. So it deploys it at root folder.
If you  would like to deploy it your virtual application using command line you could use dest:contentPath that will work fine for virtual application as well.

URL that you have compared for Visual studio , It uses soruce and destination as manifest and read configuration from manifest file. So we can't compare two URL's directly.

Reference ContentPath : https://technet.microsoft.com/en-us/library/dd569034%28v=ws.10%29.aspx

use **dest:contentPath=** instead of **dest:auto**

"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="D:\_work\3874f4573\publish.zip" -**dest:contentPath**,ComputerName="https://my-azure-app-service.scm.azurewebsites.net:443/msdeploy.axd?site=my-azure-app-service",UserName="$my-azure-app-service",Password=****,AuthType="Basic" -setParam:name="IIS Web Application Name",value="my-azure-app-service/api" -enableRule:AppOffline
