### ISSUE TITLE
Tasks/AzureFileCopy/task.json - "dataSourceName" options not doumented

### ISSUE THREAD

**Issue by viertaxa** [Microsoft/vsts-tasks#2414]
In the Azure File Copy task there are dynamically loaded picklists implemented. There are several dataSourceBindings:

     "dataSourceBindings": [
        {
            "target": "StorageAccount",
            "endpointId": "$(ConnectedServiceName)",
            "dataSourceName": "AzureStorageServiceNames"
        },
        {
            "target": "EnvironmentName",
            "endpointId": "$(ConnectedServiceName)",
            "dataSourceName": "AzureHostedServiceNames"
        },
        {
            "target": "StorageAccountRM",
            "endpointId": "$(ConnectedServiceNameARM)",
            "dataSourceName": "AzureStorageAccountRM"
        },
        {
            "target": "EnvironmentNameRM",
            "endpointId": "$(ConnectedServiceNameARM)",
            "dataSourceName": "AzureVirtualMachinesV2Id",
            "resultTemplate": "{\"Value\":\"{{{ #extractResource resourceGroups}}}\",\"DisplayValue\":\"{{{ #extractResource resourceGroups}}}\"}"
     }

While it is possible to determine the purpose of the targer and endpointId parameters, neither the dataSourceName or resultTemplate are defined elsewhere, so we are unable to use this to extend custom build tasks.

**Comment by GitHubSriramB** [comment]
DataSourceName corresponds to the name of a data source defined in the service endpoint type (in this case Azure RM). In order to query for all data sources supported by an endpoint type (e.g. AzureRM), you can use the following:
https://<account name>.visualstudio.com/defaultcollection/_apis/distributedtask/serviceendpointtypes?type=AzureRM

ResultTemplate is applied on the response from the data source query. For e.g. in the example that you specified, the result template is applied on the response from the data source query for "AzureVirtualMachinesV2Id", which is essentially response from the following Azure API:
"https://management.azure.com/subscriptions/$(endpoint.subscriptionId)/providers/Microsoft.Compute/virtualMachines?api-version=2015-06-15".
#extraceResource is a Mustache handler specific supported to handle extracting the resource from the response and use it in transforming the result based on the template provided.

We are working on documenting information about data sources/data source bindings. If you have any further query in the meantime, please let us know.

**Comment by kmkumaran** [comment]
Closing it based on @GitHubSriramB response. Feel free to reopen if you have additional queires.

**Comment by ggirard07** [comment]
@GitHubSriramB @kmkumaran the provided link "https://.visualstudio.com/defaultcollection/_apis/distributedtask/serviceendpointtypes?type=AzureRM" is dead. How to access this documentation?
Thanks!

**Comment by ggirard07** [comment]
@GitHubSriramB Any update on the extended documentation you mentioned at the end of your comment 

> We are working on documenting information about data sources/data source bindings. If you have any further query in the meantime, please let us know.

Thanks!

**Comment by darshankumarys** [comment]
We didn't find any APIs for VM Sizes, wen they will be released ?
