### ISSUE TITLE
Quality Gate check in Sonar Task during PR

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#2415]
I don't know if this is even somehow technically possible with the current feature set of Sonar, but currently while running the Sonar Task during a PR it won't check the quality gate. With Sonars default quality gate which checks that no technical dept > 5% is introduced in new code this can lead to the situation that the build for the PR is successful, but the build after the merge of the PR fails. This is especially troublesome if there is a branch policy is in inplace which doesn't allow direct commits to fix this, but instead requires a new PR.

It would be nice if the Sonar task would be able to determine the resulting quality gate during a PR, but still without uploading the results or setting the quality gate in Sonar.

**Comment by bgavrilMS** [comment]
Hi Pascal, 

I am glad you're making advanced use of these build tasks! 

 In PR builds we force SQ analysis to "incremental mode", which means that the result of the analysis are not uploaded to the SQ server and that the quality gate is not computed. This also means that a PR build cannot fail because of the quality gate failure, so a new PR build should be fine ?

I do agree however that there is value in computing the quality gate during incremental analysis and thus allowing PR builds to fail. You'll have to speak to the Sonar Source folks about this. We have discussed it with them a few times as many users ask for this feature, but there were more pressing matters on their backlog at the time.

**Comment by pascalberger** [comment]
Thanks @bgavrilMS. I assumed that it's like this. I've also posted it to the Sonar group: https://groups.google.com/forum/#!topic/sonarqube/FgevBBai-Rc
