### ISSUE TITLE
QUESTION:  On Windows, what task can be used to copy files from the drop folder using a UNC path to a local folder for testing?

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/vsts-tasks#2436]
Does a built-in task exist or is it necessary to create your own?

**Comment by ericsciple** [comment]
copy files is capable

**Comment by bbusacker** [comment]
Then I would respond that it is not working properly.  It complains that it cannot find the path.  I will file a bug.

**Comment by bbusacker** [comment]
This was a permissions issue.  I am running my agent on a machine that is not on the domain but am running it with same username and password as the domain user that can map the UNC path.  I had to also add just a local user with same username and password to the share and then everything worked.  Not sure if a better error message could be generated rather than just path not found.   

Is this always the way permissions work.  I thought if you had a local user that had same username and password as domain user authentication would work.  This was not the case for me.

**Comment by ericsciple** [comment]
I'm not sure whether a better error message is feasible. If you fs.statSync the dir from node, what error code does it return? If ENOENT then not found is all we know.

I believe that's the way it works. Knowing the user name isn't enough, the domain is also required. Otherwise I believe it is falling back to the target computer as the "domain".
