### ISSUE TITLE
Question: Difference between Powershell and Powershell3 execution environments

### ISSUE THREAD

**Issue by viertaxa** [Microsoft/vsts-tasks#2473]
I have two questions regarding the Build Task execution environments. 

What is the difference between Powershell and Powershell3? On my system, the host version for Powershell reports as 4.0, but the newer tasks in this repo are using Powershell3 with the VSTS SDK over Powershell.

This leads to my second question: What will the support of Powershell vs Powershell3 be going forward? I would like to write my tasks for the execution environment that will be the most supported long-term.

**Comment by bryanmacfarlane** [comment]
The execution handler basically means what plugin on the agent will handle executing the script specified and returning output the agent engine.  There are actually handlers plugins in the agent:

https://github.com/Microsoft/vsts-agent/tree/master/src/Agent.Worker/Handlers

The initial powershell handler had lots of problems from our 1.x agent.  We include it for compat.  We created the powershell3 handler which runs ps tasks out of proc for robustness and uses powershell.  We called in powershell3 because that's the min ps to run them.

See the ps3 lib for the advantages.  It's the path forward:

https://github.com/Microsoft/vsts-task-lib

The guidance is to write tasks using the vsts-task-lib.  Use node if you need to write once cross platform.  If you're automating a windows technology (especially ones ps based) then you can write in ps.

**Comment by viertaxa** [comment]
Great. Thanks for the clarification. It's looking like I might have to utilize the AzurePowerShell functionality over powershell3 due to the vNext agent included in TFS 2015 Update3 not supporting the Service Endpoint "data" property. (Get-VstsEndpoint). My understanding is that this operates within the older Powershell handler. 

Would it be safe to use a slightly newer agent version with an on-premise TFS system? (IE TFS 2015 Update 3 has 1.95.3 and I would need 1.97 to utilize the ps3 handler.) I'd like to be able to write the plugin using the new paradigm, but that incompatibility is holding me back.

**Comment by bryanmacfarlane** [comment]
Assigning to Eric for question.

I believe the QU3 agent set the data.  It's later versions of the ps3 handler which reads it.  The ps3 lib should be 'linked' into your task (copied at build time etc...) so your task carries the lib.  I believe a task carrying the latest ps3 lib will work in a QU3 agent (1.95.3).  Eric can confirm for sure.

On a side note, there shouldn't be an issue using a 1.97 agent against QU3.  We work hard on compat.

**Comment by ericsciple** [comment]
I checked the source code just now. The powershell3 task execution handler in 2015 U3 sets endpoint auth and endpoint URL but does not set endpoint data.

**Comment by viertaxa** [comment]
Thank you for the input. I appreciate the help. I think the best route forward for me will be to install a second build agent of the requisite version for the output I need (1.98 off the top of my head.) unless someone specifically recommends against it.

**Comment by bryanmacfarlane** [comment]
Makes sense.
