### ISSUE TITLE
Copy Publish Artifact: "Artifact Type" input label is unclear

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-tasks#2477]
On the "Copy and Publish Build Artifacts" task, the **Artifact Type** input name is not intuitive.  It doesn't describe the artifact type.  It describes the copy/publish destination.  It should be renamed to **Destination**.

**Comment by ericsciple** [comment]
I'm inclined to think "artifact" terminology is important since it used across the system to mean something - e.g. Release syncs artifacts, or the artifacts tab on the build summary page, or file share artifact retention policy vs other type of artifact retention policy. "Destination" is overlooking the fact that artifact really means more within the system. Even if publishing to a file share, more is going on than just copying files.

**Comment by DavidStaheli** [comment]
Agreed that "artifact" is important to use across the system.  But this input doesn't describe the artifact or its type.  It describes where the artifact will be placed: on this server, or a file share.  Asking the user for the "Artifact Type" doesn't correlate with whether the artifact will be placed on a file share or stored on the server.

**Comment by ericsciple** [comment]
I'll defer to Chris/Bryan. I still think "artifact type" is good verbiage since "artifact type" has meaning throughout the system - but Chris/Bryan would have a better long term vision

**Comment by DavidStaheli** [comment]
@chrisrpatterson are you okay if I change **Artifact Type** to **Artifact Location** to describe whether it will be placed on the server or a file share?

**Comment by chrisrpatterson** [comment]
No i tis artifact type not the location.
