### ISSUE TITLE
vNext build not completing when long running

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vsts-tasks#2492]
When I have long running job, I'm finding erratic performance on the job allowing it continue to run. For instance, I have a powershell job that might take 4 hours to run and after approx 2 hours it shows job cancellation and failure on the last step, but no powershell error being thrown. 

When running the exact same task manually in ISE on the machine, it takes the required time to run and completes with no issue. 

I was trying to replace the need to launch scheduled jobs on a machine, but am finding the long running processes erratic behavior has caused a lot of issues in me being able to rely on this for running several powershell jobs that have long processing times. 

I have verified I have the timeout setting set to 0 in the build settings. 
I am running this on TFS 2015 Update 3 local on premise edition. 
I believe the current agent version is 14.95.25229.0 (metadata on VSOAgentService)

Any recommendations? I can't speed up this particular job more

**Comment by ericsciple** [comment]
What is the error?

**Comment by sheldonhull** [comment]
I can't find an error, just seems to terminate. I will enable debug and see
if I can get more output.

Not sure if there is connectivity logic that continues to try when agent
machine is unresponsive due to heavy load. Do you have any insight on that?

**Comment by ericsciple** [comment]
Is there any error issue logged on the build summary page (remove everything from the URL after the build ID in the query string)?

One thing you can try is scheduling the build at a different time. My guess is, if there is connectivity issues (e.g. servers scheduled to reboot during the middle of the night) then you could be running into network issues specific to the time of day.

If the agent fails to renew the job token, then you should see an issue like "job abandoned because agent failed to renew lock" on the build summary page.

Another thing you could check is the _diag folder at the root of the agent directory. If you open the agent diag log or worker diag log, and search for "exception" you should be able to find an exception if something was logged from the agent/worker infrastructure. You can also zip the log and send to ersciple and i'll fwd along to the right folks (at microsoft com).

**Comment by DavidStaheli** [comment]
Hi @sheldonhull, is this still an issue for you and something we can help with?  Otherwise, I will close the issue for now.  Thanks.

**Comment by sheldonhull** [comment]
No, not an issue at this time. I will update if I find further detail
warranting your attention. Thank you!

**Comment by DavidStaheli** [comment]
Thanks @sheldonhull!
