### ISSUE TITLE
SonarQube failing build on pull request

### ISSUE THREAD

**Issue by dazfuller** [Microsoft/vsts-tasks#2508]
I've noticed that a change made on the 20th July through pull request #2108 disables the ability to fail a build if the build is triggered as part of a pull request (commit: bad40d791ea32f421d6ef39f8603855d9f08c2a5 Tasks/SonarQubePostTest/SonarQubeBuildBreaker.ps1).  This is a feature we were using as we wanted pull requests to be unable to complete if the build was failing the SonarQube quality gate.

Is there a way to re-enable this feature perhaps through an option?

**Comment by bgavrilMS** [comment]
Thank you for reporting this Darren. I'll look into it today and come back to you.

**Comment by bgavrilMS** [comment]
The build breaker option seems to work fine in normal builds. It never worked in PR builds - this is due to a SonarQube limitation. 

In a PR build we run the analysis in "issues mode", i.e. the analysis is not recorded in the SQ database and more importantly, the quality gate is NOT computed. The issues are written in a file which we process and then we inject them into the code review associated with the PR (although this feature is currently broken and I am working on fixing it ASAP). Not running a full analysis during a PR is important because it would create too much noise in the tech debt trends.

**Comment by dazfuller** [comment]
I'd believed that this was working previously, unless we've had a secondary reason as to why the build was failing as well (which is not beyond the realm of possibility).

In that case I guess I'll have to rethink the way it's implemented.

Thanks, I'll consider this as a do-not-fix resolution and close the issue.
