### ISSUE TITLE
azure file copy exceeds size limitation of 2147483648 byte

### ISSUE THREAD

**Issue by javier-alvarez** [Microsoft/vsts-tasks#2519]
.zip exceeds size limitation of 2147483648 bytes. ' For more info please refer to https://aka.ms/azurefilecopyreadme
2016-09-14T16:56:39.0444259Z ##[section]Finishing: AzureBlob File Copy

This seems like a limitation on some int value. How can I fix this?

**Comment by niadak** [comment]
Hi javier-alvarez,
Allowed source size in AzureFileCopy task is limited to 2GB. We will try to fix this ASAP. Please let us know if you are blocked on this or not? You can copy sub folders to get unblocked.

**Comment by javier-alvarez** [comment]
Yes this is a big blocker. I had to change to use the file share service and the performance is much worse. I would like to copy to blobs asap but my build output is more than 2GB in some cases. How long do you do you think it will take for the fix to get into my VSO instance?

**Comment by bryanmacfarlane** [comment]
@kmkumaran  - FYI, in other places (source control, build server drops, file container etc...) what we do file by file and since an individual package can be very large we break files into 4MB chunks.  By doing that instead http chunking, we also get retries at the chunk level.  Very large file moves are susceptible to networking blips as well since the size naturally increases the time.

**Comment by niadak** [comment]
Hi javier-alvarez,
We will fix this issue ASAP. I will update here when the fix is available in VSO. thanks for reporting the issue.

**Comment by niadak** [comment]
Hi javier-alvarez,
We have fixed the issue. The fix should be available in VSTS by 3 weeks (approx). I am closing the issue. Please feel free to reopen if the issue did not get fixed by 3 weeks.
