### ISSUE TITLE
Session variables do not support commas

### ISSUE THREAD

**Issue by wulfland** [Microsoft/vsts-tasks#2521]
If I add Session variables to a PowerShell script like this:

`$AppPoolPassword=$(AppPoolPassword)`

commas and blanks my not occur in the variable. This is bad for passwords and other strings you do not control. It results in failing releases in some environments with strange errors (see [this post](https://writeabout.net/2016/09/02/fix-tfs-vsteam-release-management-error-found-value-abcd-with-no-corresponding-key/)).
If I add the variables like this:

`$AppPoolPassword=’$(AppPoolPassword)’`

the script fails. I can see in the log, that the variable gets passed in correctly (`InputSessionVariables=$AppPoolPassword='****'`) but in the scripts, where the variable is used the value keeps its quotes. This breaks DSC configs and you cannot use the variable inside a string. I would expect to pass the string in with quotes and that it does not keep the quotes when it is assigned to the variable.

**Comment by pavanadepu2** [comment]
@wulfland, The general usage of session variable is $value1=$(val1). Or $value1='$(val1)' in case variable val1 has a space or comma in it. The task treats the value of $value1 as it is specified during the task authoring. It won't truncate the quotes at the time of assignment. 

If any quotes are specified during the task authoring then DSC configuration script author should make sure to truncate such quotes before using it,

In your case, use $AppPoolPassword.Trim("'") instead of $AppPoolPassword in the DSC script.

**Comment by wulfland** [comment]
@pavanadepu2, cluttering the DSC configs with .Trim() at the end of all variables seems like a workaround to mee. Wouldn't it be better too implement the trim in the task?

**Comment by pavanadepu2** [comment]
@wulfland, thanks much for the feedback. We will add this requirement to our product enhancements backlog.
