### ISSUE TITLE
Deploy AzureRM Web App Error

### ISSUE THREAD

**Issue by vs6681** [Microsoft/vsts-tasks#2536]
Hi Everyone,

We are observing one issue during azure webapp publish vso step, every time we get below error in couple of our website.

An error occurred when the request was processed on the remote computer. Error: An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\bin'

Any help ?

**Comment by Ajay-MS** [comment]
@vs6681  Can you try once following approach if it works for you -
1.  Go to Azure portal and stop webapp.
2.  Deploy webapp
3.  Restart webapp again.

If you still face this issue let me know and mail logs at RM_Customer_Queries@microsoft.com.

**Comment by zechariahks** [comment]
Hi Ajay,

we have Take App Offline option in the task. Doesn't this option Stop the app before syncing the files?

**Comment by Ajay-MS** [comment]
@zechariahks 

App offline puts a app_offline.htm file under root folder of your webapp application, Asp.net runtime checks for root of application when it finds app_offline.html it stops processing new request for application and redirects request to app_offline.html. Since now there will be not request is redirected to application no dll should be in use and ideally this should also work.
But app_offline fails sometimes probably due to some race condition. 

So for above issue I want that this problem is occurring very race or every time . If very  rare and app_offline is not working you can unblocked with above steps i have mentioned, else you can update me will look into it.

**Comment by Ajay-MS** [comment]
@vs6681 
I am closing this issue assuming you are not facing this issue now. If you again face this issue open this issue again and share debug logs at RM_Customer_queries@microsoft.com
