### ISSUE TITLE
release environment variable not taking string with ";"

### ISSUE THREAD

**Issue by vs6681** [Microsoft/vsts-tasks#2567]
Hi I have release definition which has task that execute the integration test after deployment. we are observing that Override TestRun Parameters variables whose values are coming from envrionment variables has ";" in it and it is splitting the connection string.. 
 
Like I have variable SqlConnection which has value = Server=tcp:XXXXXXXXXXX.database.windows.net,1433;Database=Approvals;User ID=XXXXXXX;Password=XXXXXXX;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;

And when it is getting replaced we found that **sqlConnection is Server=tcp:h080a0ob9k.database.windows.net,1433** and remaining is not coming.

Please let us know how to handle this ? I tried putting value in 'XXXX' and "XAXAXA" but same issue.

**Comment by camous** [comment]
getting exactly the same issue : http://stackoverflow.com/questions/39510402/override-testrun-parameters-with-value-including-semi-colons-in-visual-studio-te

Microsoft engineer suggested to split each chunck in a specific parameter. acceptable workaround for connectionstring with known number of element. Can be tricky for unknown one (such SQL for example)

**Comment by camous** [comment]
waiting for a better solution not changing the existing test source code, I've ending up using a powershell task overriding XML runsettings file before tests being actually fired. Dirty quick script, neither error handling or check if parameter actually exists.

https://github.com/camous/vsts-powershell/blob/master/Set-RunSettings.ps1 
![image](https://cloud.githubusercontent.com/assets/8566299/18876640/c2181a88-84ca-11e6-8c6f-5edb2c1ed26e.png)

Parameters have to be prefixed by "__" in order to be recognize between all systems ones
![image](https://cloud.githubusercontent.com/assets/8566299/18876725/0d6a28e6-84cb-11e6-8f18-8c5ea22cab1b.png)

**Comment by kmkumaran** [comment]
Invoke-VsTest which is consuming the overrideTestrunParameters doesn't seem to handle special characters if present in environment variables.

@allendm-msft to take it further.

**Comment by nigurr** [comment]
Hi,

This issue was fixed recently. This will be available in next [build agent](https://github.com/Microsoft/vsts-agent/releases) release.

With new fix, you can escape with `\` ex: `sqlserver\;8080  =>   sqlserver:8080`

**Comment by nigurr** [comment]
Closing this issue and please re open if it's still not fixed.

**Comment by tehjrow** [comment]
I'm still having this issue, did the fix ever get released?

**Comment by vs6681** [comment]
Not sure

Regards,
Vikas
