### ISSUE TITLE
Is it possible to create a sourceDefinition that parses XML instead of JSON?

### ISSUE THREAD

**Issue by viertaxa** [Microsoft/vsts-tasks#2580]
Is it possible to create a sourceDefinition that parses XML instead of JSON?

Given the following example from the existing tasks, I've been able to extend this to a few other Azure APIs.

```
"sourceDefinitions": [
    {
      "target": "resourceGroupName",
      "endpoint": "https://management.azure.com/subscriptions/$(authKey.SubscriptionId)/resourcegroups?api-version=2015-01-01",
      "selector": "jsonpath:$.value[*].name",
      "authKey": "$(ConnectedServiceNameARM)"
    }
  ],
```

However, when interacting with the Blob Storage REST API, the return type is XML rather than JSON. 

Is there a way to do essentially:

```
"sourceDefinitions": [
    {
      "target": "resourceGroupName",
      "endpoint": "https://{BlobQueryHere}",
      "selector": "xmlpath:$.Blobs[*].Metadata.Name",
      "authKey": "$(ConnectedServiceNameARM)"
    }
  ],
```
Note that I'm just using the selector above as an example.

Then end goal here is to allow a user of the build task to select a given blob from a picklist to be consumed in the build. 

Thanks for any info you can provide!

**Comment by GitHubSriramB** [comment]
Yes. Result selector can also be an XPATH query. For e.g. Azure Classic endpoint type supports data sources that use XPATH query.
{
“name”: “AzureWebSiteNames”,
“endpointUrl”: “$(endpoint.url)/$(endpoint.subscriptionId)/services/webspaces/$(WebSiteLocation)Webspace/sites”,
“resultSelector”: “xpath://Site/Name”
},

For more details on data sources you can refer to following blog:
https://blogs.msdn.microsoft.com/sriramb/2016/09/15/service-endpoints-data-sources/

**Comment by viertaxa** [comment]
Great! Thank you. Is there a method to postpone the querying of the souceDefinition until a given variable is populated? 

For example, I want to select a Resource Group and then display the VNets within that resource group. The API queries themselves are easy, however TFS displays an error when there is no RG selected since the query for the VNets will fail without a resource group in the URL. Once a RG is selected, the query will work fine, but the page will display an error whenever loading the build definition. 

Using a visibleRule to hide the VNet picklist untill a RG has been selected does not alleviate the issue. 

Can you make any suggestions as to how to keep this error from displaying?

Thank you!

**Comment by GitHubSriramB** [comment]
Which version of TFS are you on? We have made improvements with the task drop-downs in VSTS and these improvements will be available in Dev15. 

One of the improvements is to not populate the drop down until it is clicked. With this you should not see any errors until RG is selected.

Also, would suggest using dataSourceBindings in your task to populate task drop-downs instead of using sourceDefinitions. Pl. refer to blog on usage & features. We will not be making any enhancements to sourceDefinitions based queries. We will however support the existing sourceDefinitions functionality.

**Comment by viertaxa** [comment]
We are running TFS 2015 Update 3. Thanks for the info. Looks like I'll need to wait until TFS15.

**Comment by jahirj** [comment]
Is it possible to have cascade dropdown in custom build task

**Comment by rajatagrawal-dev** [comment]
You can use visibleRule property so that a particular field will be visible based on some condition. For example you can set that field B will be visible if and only if field A has value xyz.

Please see [Azure App Service deploy task.json](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureRmWebAppDeployment/task.json) for another example. Here you can see that 'serverfarmid' input field is visible if 'webappname' field has value of 'invalidwebappname'.
