### ISSUE TITLE
Task Azure SQL Database Deployment shows "The remote server returned an error: (500) Internal Server Error" while from within VS it works fine

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/vsts-tasks#2737]
We have Azure SQL Database Deployment task in the middle of our RMO definition and it fails with error:
```
FilePath= Find-VstsFiles LegacyPattern D:\_work_caas\95a7cdab5\PyRq - Daily\drop\Data.Schema\bin\Release\Data.Schema.dacpac
packageFile= D:\_work_caas\95a7cdab5\PyRq - Daily\drop\Data.Schema\bin\Release\Data.Schema.dacpac
PublishProfilePath = Find-VstsFiles LegacyPattern D:\_work_caas\95a7cdab5\PyRq - Daily\drop\Data.Schema\Properties\PublishProfiles\Int.publish.xml
Publish profile path = D:\_work_caas\95a7cdab5\PyRq - Daily\drop\Data.Schema\Properties\PublishProfiles\Int.publish.xml
##[error]Status         : ProtocolError
##[error]Response       : System.Net.HttpWebResponse
##[error]Message        : The remote server returned an error: (500) Internal Server Error.
##[error]Data           : {}
##[error]InnerException : 
##[error]TargetSite     : System.Net.WebResponse GetResponse(System.Net.WebRequest)
##[error]StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
##[error]                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
##[error]HelpLink       : 
##[error]Source         : Microsoft.PowerShell.Commands.Utility
##[error]HResult        : -2146233079
```
However, publishing from withing VS2015.3 shows way more meaningful error:
```
(58,1): SQL72014: .Net SqlClient Data Provider: Msg 50000, Level 16, State 127, Line 12 Rows were detected. The schema update is terminating because data loss might occur.
(47,0): SQL72045: Script execution error.  The executed script:
An error occurred while the batch was being executed.
```

Full log: https://mpsit.visualstudio.com/DefaultCollection/PIExp/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?definitionId=4&releaseId=808&_a=release-logs

**Comment by abatishchev** [comment]
Release to out Daily env works fine from within both RMO and VS. However any deployment attempts to Int from RM fail with HTTP 500, and works fine from VS.

**Comment by abatishchev** [comment]
I believe this might be related to the recent outage of SQL Azure in West US region. DNS records were changed, some other internal staff I'm not really familiar with. I opened an ICM ticket to resolve that. For now all services that rely on API to manage SQL Azure are end up with HTTP 500.

**Comment by Ajay-MS** [comment]
@abatishchev 

In response task is not giving an understandable message I will create a bug for that and will be fixed with next deployment,. 
Next, you are facing issue that "The schema update is terminating because data loss might occur". In most of cases this error occurs if you did some changes in you schema in dacpac which can cause some data loss. 

In your database project there is checkbox for this you can uncheck checkbox for "Block incremental deployment"  it if you surely want those changes. Refer below image.

![datalossmightoccur](https://cloud.githubusercontent.com/assets/16772764/19075794/237b9946-8a64-11e6-8539-97f5c8608b21.PNG)

**Comment by abatishchev** [comment]
hi Ajay, yes, I was facing various errors (from data loss to missing extended properties) which I was able to learn only from the output of VS, in contrast RMO always shows 500.

**Comment by Ajay-MS** [comment]
@abatishchev  

Thanks for reporting this issue. We will fix this issue soon.

**Comment by Ajay-MS** [comment]
@abatishchev 

Using RMO it was failing on creating firewall rules failed before executing your dacpac but creating firewall should also giving understandable message which is here you getting as object of System.Net.HttpWebResponse. We have created internal bug for this. Since your release is succeeding now I am closing this issue and tracing it as part of internal bug. If you again face this issue feel free to reopen this bug again.

**Comment by rohit-batra** [comment]
@abatishchev 

Hi Alexander,

We use REST Apis to Create Firewall Rule & post deploy Operations to Delete Firewall.
As noted by you there were 500s due to an outage, the script was failing out while trying to Create Firewall Rules.
If that part was working correctly, you would have got data loss error, which we do not suppress.
You can try that again(Since there is no outage right now) and will notice that sqlpackage.exe throws data loss error 
(In case there is an issue there which you want to report , please run release with System.Debug as true & share logs)

Thanks & Regards
Rohit Batra

PS :- Although SqlPackage throws Data Loss Error , in some cases we have observed that this error is not that verbose.
This is due to the way we handle error from sqlpackage.exe errors & we have a bug opened to capture more details.

**Comment by abatishchev** [comment]
Hi Ajay and Rohit,
Thanks for detailed and thoughtful response!
Yes, the outage has been mitigated, my server loved back to the right control ring, now both Portal and RMO work fine.

P.S.
Can you please email me (alexbat@) the links to those two bugs so I could subscribe?
