### ISSUE TITLE
New Agent vs Server Tasks - Automatic Grouping seems wrong. 

### ISSUE THREAD

**Issue by JoeBrockhaus** [Microsoft/vsts-tasks#2748]
It looks like the tasks that are disabled are being grouped into their own 'agent' queue, and then action tasks are grouped in their own agent queue as well. 

This results in multiple agent execution batches at runtime, when there should only be one. 

![image](https://cloud.githubusercontent.com/assets/5933609/19042728/bba11e0c-8952-11e6-87c2-d55b1917b19a.png)
![image](https://cloud.githubusercontent.com/assets/5933609/19042773/f5bc287a-8952-11e6-9771-605bb36453f6.png)

**Comment by bansalaseem** [comment]
Joe, 

We don't have any automatic grouping of tasks and all the grouping is done by the user itself. 

We have heard few feedbacks where people did not get that the drop down in the add tasks action is mainly to create a new phase and based on that feedback, in the latest code we have changed the text of the drop down & have added separator so that is more clear. 

In case you still observe some magic happening, please do share the repro steps so that we can investigate it. 

Regards
Aseem Bansal

**Comment by JoeBrockhaus** [comment]
I'll try to repro it again. I was able to consistently across various browsers/sessions while I was troubleshooting the AzureRmWebApp deploy task. 

The release had 2 task group steps prior to the feature showing up. There were no groups shown. I clicked Add Task -> Agent, and this is when the 'magic' happened: The two existing steps were grouped as 'Agent Tasks' and the new agent task was similarly grouped under another  'Agent Tasks' group. I could not drag the new task into the other or otherwise change/unify/rename the grouping(s). 

I originally thought the automatic grouping of the original tasks (presumably saved with an old schema, right?) was a result of them both having been disabled. However, the same behavior occurred when one was enabled: New 'duplicate' agent group. If I add another new agent task, it gets added to the new group (importantly: Not its own new group, as the first time around). If I delete the new group, the automatic grouping goes away and now I just have the two original tasks in no group. 

I wagered a guess that there was something out of sync causing this issue, and seems like it has something to do with the (somewhat confusing UX, if intended, of) auto-creation and removal of groups of the two types (presumably, though I now think behavior conflicts with automatically creating a new group for new tasks..), or the process of updating and reverting the underlying configuration schema (automatically grouping existing tasks, etc). 

See what I mean about magic? 

sent from a phone

-----Original Message-----

**Comment by bansalaseem** [comment]
Thanks Joe for your feedback, We have done 2 fixes to address this issue. 

1. We have started showing the containers by default. So even if you have 1 container with 2 tasks in it, we have started the default container. 

2. We have remained the Add Tasks -> Agent option to clearly indicate that it will add a new container so that user select the drop down of Add tasks only if the user wants to add a new container. Otherwise the tasks will get added to the selected container. 

Please do play with the latest UI and share whether you still face any confusion. 

Regards
Aseem Bansal
