### ISSUE TITLE
CoApp

### ISSUE THREAD

**Issue by magol** [Microsoft/vsts-tasks#2835]
I try to create a NuGet package using [CoApp](http://coapp.org/) and `*.autopkg`
I know it is a dead project, but it is the best alternative for C++ projects (that I know of)

I have installed CoApp on the agent machine, and try to use a PowerShell script to genereate the NuGet.
If I run the PowerShell script localy on the agent machine, everything works. No errors and the nuget package is generated. But if I let TFS 2015 Build run the PowerShell script, I get a error that it do not found `Write-NuGetPackage` (the cmdlet from CoApp).

How do I do to use the cmdlet installed on the agent machine? Or is it any beter way to generate a NuGet package for C++?

**Comment by zjrunner** [comment]
Where is CoApp installing Write-NuGetPackage?  My guess is it is wiring it up through your profile load or user account as you logon the machine, but you are running the Build Agent as a service (likely Network Service) so you aren't going to see your user hooks. 

Since the question is focused on getting a powershell task to call powershell cmdlets installed on a machine, and not something about packaging specifically, I'm clearing the Area:Packaging label also.

**Comment by magol** [comment]
It is installed in `C:\Program Files (x86)\Outercurve Foundation\Modules\CoApp`

Is it any way to add the Module to TFS so that all build agents are getting the module?

**Comment by zjrunner** [comment]
Removing packaging again, not a packaging question really (about agent manipulation)

**Comment by magol** [comment]
I have solved the problem.
According to [the installation instructons](http://coapp.org/tutorials/installation.html), following must be run after installation:
```PowerShell
[System.Environment]::SetEnvironmentVariable("PSMODULEPATH", [System.Environment]::GetEnvironmentVariable("PSMODULEPATH", "User") , "User")
```

In addition, the installation must be performed in a separate PowerShell instance.
