### ISSUE TITLE
NuGetPublisher tasks fails when nothing to publish

### ISSUE THREAD

**Issue by jmezach** [Microsoft/vsts-tasks#2985]
We've noticed that on VSTS currently when running the NuGetPublisher task it fails when it doesn't find any NuGet packages to publish, whereas with TFS 2015 Update 3 it just ignores it and continues silently.

I'm not sure why this change was made. At the moment some of the teams I've been working with are using "the TFS behaviour" so that they can run both debug and release builds to separate feeds. What we're doing is having the NuGet Packager task output the NuGet packages to a configuration specific folder (ie. packages\$(BuildConfiguration)). Then we have two NuGet Publisher tasks configured to publish packages from packages\debug to the debug feed and packages\release to the release feed. This has worked just fine for us given the fact that we currently don't have a way to let build tasks run conditionally.

On VSTS however, this setup doesn't work since then either the debug or the release build fails due to the NuGetPublisher task not finding any packages to publish (which is expected).

My guess is that this behaviour will also come to TFS On-Prem when TFS "15" ships, so I'm wondering how we can keep supporting this scenario?

**Comment by zjrunner** [comment]
I dug into this a bit -- looks like this happened back in july (commit e0c721b06a47ccd6153e953dabf47bd8cfedbbc4) when the task was moved from powershell to node (and updated in preparation for newer nuget.exe releases).  At this point the release is locked, and since we haven't heard of the concern since the time it went into the cloud release it won't be possible to pull back for a change.

Could you put both folders into the same single task? Your pattern match to find nupkgs can take multiple patterns so you'd be able to encode several $(var) rooted paths to your different folders.  The empty check is only done after all patterns are processed, so it should get you past the no-packages-found error.

https://www.visualstudio.com/en-us/docs/build/steps/package/nuget-publisher

**Comment by jmezach** [comment]
I'm not sure if this will help us much. Perhaps we could merge both NuGet Publisher tasks into one and have them match both debug and release packages, but then how would we make sure that those packages are pushed to the right feeds? From what I understand I can only configure one target feed to publish packages to with the NuGetPublisher task.

**Comment by zjrunner** [comment]
ah, I missed that you needed them going to different feeds and weren't using versioning as a differentiator.  We can talk internally about a flag to enable what you are after for VSTS, but due to timing it isn't going to make the TFS delivery in-box.  Your options there will be to push a newer version of the task to your collections that has the fix (post-update), or to mimic the task logic in a custom task (similar burden to pushing an updated task so I would think you'd do the former)

**Comment by Mittchel** [comment]
@zjrunner do you have an estimation of when this will be available in VSTS? @jmezach told me that in Q4 conditional build tasks are planned to be released, which probably makes this 'fix' obsolete.

**Comment by zjrunner** [comment]
the VSTS flag?  not yet (ETA).  Are there folks in here that would use it in VSTS (not just TFS)?  Given how long it has been out there in VSTS already I don't want to push a fix and more options if it isn't going to be used, especially when I think the spirit behind the state is valuable.  Actually, about conditional build tasks -- don't they already have ControlOptions to ContinueOnFailure (I imagine these probably still set your overall build to yellow/red and that is what you want to avoid even though it ran the other steps fine?)

**Comment by Mittchel** [comment]
@zjrunner we actually have a few customers on VSTS, yes. But most of them are on TFS though. 

And you are correct; ContinueOnError is available on task level, but also on level of multi-configuration. The latest one still keeps everything failing, but if we enable ContinueOnError on the build task the build will get yellow/orange which we indeed would like to avoid. 

https://www.visualstudio.com/en-us/articles/news/features-timeline

'Conditional tasks' is scheduled for Q4 2016, so maybe we should wait a little for this. This might solve everything at least for VSTS.

**Comment by jmezach** [comment]
@zjrunner Although we can work around it by setting the ContinueOnError flag that isn't really a long term solution because if pushing a package to a feed fails it will also be ignored.

@ptoonen What is your take on this?

**Comment by zjrunner** [comment]
@bryanmacfarlane - is this what 'conditional tasks' was implying (run or skip on a condition, still let the build go green), and are those still a Q4 planned feature?

**Comment by alexmullans** [comment]
There's an option now in the task to "Continue if no packages match the "Path/Pattern to nupkg" that should do what you're expecting.
