### ISSUE TITLE
Unexpected ##vso[task.setvariable]value behavior with Task Groups

### ISSUE THREAD

**Issue by GeorgeTsiokos** [Microsoft/vsts-tasks#3116]
There's a behavior difference between a build containing two PowerShell tasks and a build containing a Task Group with the two same PowerShell tasks.

A build variable, `Pass1` is set to `build variable`.

Here are the two PowerShell inline scripts:
Script 1
```PowerShell
Write-Host "Here's $(Pass1)"
Write-Host "##vso[task.setvariable variable=Pass1;]HelloWorld"
```
Script 2 (Arguments: `$(Pass1)`)
```PowerShell
Write-Host "here's args: $args"
Write-Host "here's $(Pass1)"
Write-Host "here's $Env:Pass1"
```

__Expected__ output for a build with two tasks (debug is true):
```
2016-11-18T15:43:08.9556405Z Here's build variable
2016-11-18T15:43:08.9836430Z ##[debug]Processed: ##vso[task.setvariable variable=Pass1;]HelloWorld
```
and
```
2016-11-18T15:43:09.8146428Z here's args: HelloWorld
2016-11-18T15:43:09.8486420Z here's HelloWorld
2016-11-18T15:43:09.8486420Z here's HelloWorld
```

__Unexpected__ output for a build with a task group (`debug = false`):
```
2016-11-18T15:44:24.1943543Z Here's build variable
```
and
```
2016-11-18T15:44:25.2743560Z here's args: build variable
2016-11-18T15:44:25.2753553Z here's build variable
2016-11-18T15:44:25.2793550Z here's HelloWorld
```

__Unexpected__ output for a build with a task group (`debug = true`):
```
Here's build variable
Processed: ##vso[task.setvariable variable=Pass1;]HelloWorld
```
and
```
here's args: build variable
here's build variable
here's HelloWorld
```

This was discovered when I upgraded my build to use Task Groups.

**Comment by GeorgeTsiokos** [comment]
__Temporary workaround__: creating build variables with the same name as the task group parameters and passing the build variable value to the parameter using the `$(variableName)` syntax resolved the issue.

**Comment by harshil93** [comment]
@GeorgeTsiokos When you create a task group containing these two tasks, it will show Pass1 as a input to the task group. Are you setting that `build variable` ? 

The inputs to the task group are resolved before the build/release is created, so if you are setting Pass1 to `build variable` and create a build, wherever you have used $(Pass1) inside your task group will be replaced with `build variable`. Then when the tasks run, the variable Pass1 is set and since $env:Pass1 is the only one which isn't replaced, it echoes out the right value.

**Comment by harshil93** [comment]
Earlier thread on the same thing.
https://github.com/Microsoft/vsts-tasks/issues/2439

**Comment by GeorgeTsiokos** [comment]
@harshil93 yes. I believe the variable substitutions prior to the execution of the steps, especially where `##vso[task.setvariable` is called, is causing the usage confusion.

**Comment by harshil93** [comment]
Wrote a blog post explaining this.

https://blogs.msdn.microsoft.com/harshillodhi/2016/11/29/vststfs-understanding-task-groups-and-its-various-use-cases-with-setvariable-logging-command/

**Comment by GeorgeTsiokos** [comment]
That definitely clarifies whats going on, thank you!

**Comment by deka** [comment]
Sorry, solution is not good "to set a variable inside Task Group and use it inside Task Group" !
It's a workaround, not a good solution ...
•This is hacky scenario since any variable used inside of Task Group is exposed as an input which has to be filled with some value. Fill the input with the same variable name as the input7
•You may not need to define this variable in your Variables section, you will just need to make sure that you are setting it in one of your tasks in Task Group before consuming it in the same Task Group.
•When the Task Group is expanded $(filePath) in tasks will be replaced by $(filePath) and you will be setting filePath in one of your tasks before consuming it.

**Comment by Arithmomaniac** [comment]
> Wrote a blog post explaining this.
> 
> https://blogs.msdn.microsoft.com/harshillodhi/2016/11/29/vststfs-understanding-task-groups-and-its-various-use-cases-with-setvariable-logging-command/

Updated link: https://mitra.computa.asia/articles/msdn-vststfs-understanding-task-groups-and-its-various-use-cases-setvariable-logging

**Comment by michaelpisula** [comment]
Is there any hope for a good solution to the "set variable inside Task Group" problem? The solution presented in the article does not seem to work anymore with DevOps Server (the tasks do not resolve the replaced $(foo) for some reason).

**Comment by kirillkanyukov** [comment]
Oh my God! You've saved my ass:))) I have spent four days looking how to set pipeline variable in powershell wondering why "##vso[task.setvariable variable...." doesn't work!
THANK YOU SO MUCH!
Great workaround solution!!!

**Comment by genesis-barrios** [comment]
@Arithmomaniac Do you have an updated link? @kirillkanyukov can you share your solution?
