### ISSUE TITLE
Ability to set number of re-runs for functional tests

### ISSUE THREAD

**Issue by rloliveirajr** [Microsoft/vsts-tasks#3170]
My team is using VSTS RM for a while now and in our release we run integration tests which has some flaky tests. Given the flakiness of our tests we would like to have the capability to rerun failed test cases a couple of times to ensure the failure is a real failure. 

Do you have plans to implement this feature? If not, how can me and my team help to build this feature?

Thanks,
-Roberto

**Comment by nigurr** [comment]
It's in the backlog however we can't commit on timelines at this point.

**Comment by rloliveirajr** [comment]
My team can work with you to leverage this feature. How that sounds to you?

**Comment by nigurr** [comment]
@PBoraMSFT adding product team to review the same

**Comment by matthew-horrocks** [comment]
This seems like quite an important feature and one that our team would love to see implemented.

In our case, we have an automated Selenium test suite in which tests will occasionally fail due to a problem at our cross-browser testing provider. Currently we need to re-run our entire test suite, just to re-run these "flaky" tests; not an ideal situation given how long our test suite takes to run.

I'm happy to provide any assistance required.

**Comment by PBoraMSFT** [comment]
Hi Matthew,
Yes, this is on the backlog and we will be working on it in upcoming sprints.

**Comment by matthew-horrocks** [comment]
@PBoraMSFT Is there any publicly available information as to the VSTS roadmap? It would be great to have an idea of when this and other features might be implemented.

**Comment by PBoraMSFT** [comment]
@matthew-horrocks - features timeline is published at https://www.visualstudio.com/en-us/articles/news/features-timeline. Note that the granularity is at a higher level, so all individual feedback items will not show up there.
