### ISSUE TITLE
Maven task publish test results behavior changed with no documentation.

### ISSUE THREAD

**Issue by KjartanThor** [Microsoft/vsts-tasks#3333]
I just upgraded to TFS 2017 and with it got a new version of the Maven task. We are using the Maven task to publish test results from webservice tests run using SoapUI.

In the 2015 version of the task the publishJUnitTestResults function passed a false value for the mergeResults parameter when calling TestPublisher.publish. In the 2017 version the value is changed to true.

The result of this change is that previously we got a seperate named test run result for each SoapUI project in the build. After upgrading to TFS 2017 we got a single genericaly named test run containing all of the test results. When each SoapUI project contains in some cases more than 100 test this can make spotting changes in results very difficult.

I have not found any documentation of why this change was made, but ti would be better if I could set this as a parameter to the Maven build task.

**Comment by nigurr** [comment]
Hi,

Sorry for the inconvenience. It should have been documented well.
By default, we made Merge report as true because of performance issues.

If you require test reports to be published individually, you can `uncheck` the publish test results from Maven task and add `Publish Test Results` task to achieve the same. 

`Publish Test Results` task has more options to control the same.

**Comment by KjartanThor** [comment]
Thank you :-) I just tested this out and it works as I want it too.
