### ISSUE TITLE
Jacoco/Gradle - No code coverage results found to be published

### ISSUE THREAD

**Issue by jasonbrome** [Microsoft/vsts-tasks#3352]
Gradle multi-project build - have enabled Jacoco, but receive the following error:

"No code coverage results found to be published. This could occur if there were no tests executed or there was a build failure. Check the gradle output for details."

Looking at the build server, I see CCReport43F6D5EF folders immediately under the two child project folders that contain test cases.

VSTS Agent version = 2.110.0
Gradle Task = 1.0.71

Log file for gradle task with system.debug = true:
[4_gradlew build.txt](https://github.com/Microsoft/vsts-tasks/files/683442/4_gradlew.build.txt)

**Comment by kaadhina** [comment]
Can you confirm that the code coverage reports are not actually present under the CCReport folder. If they are present and still the reports are not getting published, please send us the contents for us to try at our end.
Else, can you please send us the modified build.gradle file after the Code Coverage data is appended?

**Comment by jasonbrome** [comment]
There are two CCReport43F6D5EF folders - one for each child project that contains test cases.  These folders exist within the child project folder at the same level as the build folder - not within the build folder.  Each of these two folders does have a jacoco.exec file within it.

[build.gradle](https://github.com/Microsoft/vsts-tasks/files/695327/build.gradle.txt)

**Comment by tanvi-soni** [comment]
If you are using VSTS, can you give us access to your VSTS account so that we can directly debug there. Can you please mail further details at devops_tools@microsoft.com

**Comment by jasonbrome** [comment]
Thanks - I just followed up with an email to devops_tools@microsoft.com.

**Comment by jasonbrome** [comment]
... and I just received a undeliverable message from postmaster@microsoft.com with the following preliminary information:

Couldn't deliver to the following groups:	 
tri@microsoft.com, vscsscomm@microsoft.com, vsate@microsoft.com	 

Let me know if the message was received on your side - or if there is another alias that I should use to address the message.

**Comment by tanvi-soni** [comment]
Yes, we have received your email

**Comment by vimegh** [comment]
@jasonbrome As per discussion on email, you were facing this issue as Code Coverage was not getting published due to jacoco Report getting skipped. We are expecting that you will be providing us a sample multimodule gradle project in order to further debug this issue. Please let us know if there is any update on that.

**Comment by vimegh** [comment]
@jasonbrome I am closing this issue on github for now as the main cause for this issue was that the jacoco report creation was getting skipped. You can further send us the sample project at devops_tools@microsoft.com in order for us to help you out in resolving your problem. Please feel free to reopen the issue, in case required.

**Comment by jasonbrome** [comment]
@vimegh I just emailed over a zip containing a sample multi-module gradle project that still exhibits this behavior.
