### ISSUE TITLE
Azure SQL : DacpacTask 1.4 fails when {Username}@{ServerName} is specified for the user

### ISSUE THREAD

**Issue by muttech** [Microsoft/vsts-tasks#3408]
It looks like vsts-tasks/Tasks/SqlAzureDacpacDeployment/Utility.ps1 in #3263 
was updated to append $serverName IF there is already an @ in the $sqlUsername.  That seems backwards and causes it to fail with:

##[error]Unable to connect to master or target server 'DBNAME'. You must have a user with the same password in master or target server 'DBNAME'

```
if($sqlUsername)
        {
            if($sqlUsername.Contains('@'))   <== Should that be NOT contains?
            {
                $sqlUsername = $sqlUsername + "@" + $serverName 
            }
```

**Comment by Ajay-MS** [comment]
@muttech 

In task input for Azure SQL dacpac task, input for SQL server and username are separate. So username should be provided without **@servername** . Can you help me is there any reason for providing username in **username@servername** format. If yes, will surely take it into consideration.

In provided snippet of code, this condition in being added for reason following reason -
if username itself contains @ symbol. E.g. username is - sql@dmin.  To handle such case we have to explicitly add @servername.  So we have to pass sql@dmin@servername to sqlpackage.exe

` if($sqlUsername.Contains('@'))   
            {
                $sqlUsername = $sqlUsername + "@" + $serverName 
            }`


Since your point is also a valid point one can provide username@servername and taskshould not fail at this condition , will add that condition too in next sprint.

**Comment by muttech** [comment]
@Ajay-MS the variable for username in the release was configured that way many months ago (I honestly don't remember if there was prior documentation showing that, or I just added the @servername to it - although I don't know why I would have decided to do so without seeing it elsewhere) - and it worked until mid-day yesterday, which led to the discovery of the task changing from 1.2 to 1.4 and that change being introduced.

I honestly had no idea that you could create a username with a @ in it, so that's a more interesting use-case to me.

Thanks for the explanation!
