### ISSUE TITLE
"Publish using Web Deploy" = false not working in "Azure App Service Deploy" task

### ISSUE THREAD

**Issue by kirkone** [Microsoft/vsts-tasks#3429]
Hello,

I have some troubble with my deployment to Azure using the `Azure App Service Deploy` task.
Currently ther is an issue with the casing of the `app_offline.html` using msdeploy. So I tryed uncheck the `Publish using Web Deploy` switch under `Additional Deployment Options`. The result is not what I expected becouse in the logs I can see that msdeploy is used regardless.
The parameter is getting to the script correctly as you can see in this line of the log:
```
2017-01-16T08:14:16.1659882Z ##[debug]UseWebDeploy=false
```
but later on in the log:
```
2017-01-16T08:14:18.0864045Z Running command: @echo off 
2017-01-16T08:14:18.0864045Z "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe"  ...
```
I looked in the code of this task and maybe the misbehavior comes from here: [azurermwebappdeployment.ts ](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts#L97)
I am not shure, but is this code here [utility.ts](https://github.com/Microsoft/vsts-tasks/blob/588387ac2fb3caf73c6f7e1f0f1eec069b6363f7/Tasks/Common/webdeployment-common/utility.ts#L69) not always returns true on an Windows mashine regardles of the given parameter?

Maybe I got something wrong here. Can someone check this behavior and give some feedback?

Thanks for your help,
KirK

**Comment by vincentdass** [comment]
@kirkone , Thanks for your feedback and code reference.
Yes, the above behavior is expected. Many packages (Mainly ASP.NET) are generally created from Visual studio Build and only using MSDeploy, it will be properly extracted.

General structure of Package: 
![image](https://cloud.githubusercontent.com/assets/20121508/21978278/ed732498-dbff-11e6-8aac-51f60f8b4662.png)
The actual content resides in the nested folder structure. (which will be present in root folder of App Service)
![image](https://cloud.githubusercontent.com/assets/20121508/21978302/09511f08-dc00-11e6-83f1-19dfb6e31217.png)

If KuduDeploy is used for such package, it will just copy the top folder (instead of root folder) and app service wont work as expected.

KuduDeploy (When WebDeploy option is false) is invoked only for Non-Windows agent.

We regret for the inconvenience and please use Stop-Start App Service as a workaround until the fix is made. You can also use Swap-Slot for Zero downtime deployment.

**Comment by kirkone** [comment]
I am not totaly convinced about this behavior.
You are right about the output of an MSBuild based projekt but there are so many other options for getting files to deploy. In example `dotnet build` or `node.js.`
I thinkt it would be nice to have an build in tast which can deploy to azure regardless of the kind of input. Maybe I did not see the whole thing but why we should not be able to use Kudu deploy on Windows agents? If my input file structure in not correct I schould not blame the deployment task for this.

Referring to #3425 Kudu deployment is IMHO the only way to get something like this.

Greetings,
KirK

**Comment by kirkone** [comment]
Hi,

after a little tinkering I came up with a solution for my needs. I added the option to use App_Offline.htm in my own Build Tasks here: [PublishWebPackage.ps1](https://github.com/kirkone/vsts-dnx-tasks/blob/master/VSTS.DNX.Tasks.PublishWebPackage/PublishWebPackage.ps1)
By implementing this I also worked around the casing problem with App_Offline.htm and asp.net core projects.

I am not sure if I should close this Issue because I am still of the opinion this would be a nice feature for this task here.

Thanks for all your work anyway, you all do excellent work.

KirK

**Comment by mvvsubbu** [comment]
The reasoning behind picking MsDeploy on windows is

"When Publish Using Web Deploy is false user is not really specific about deployment tool to use. In these scenario we have possibility few users giving default MsDeploy generated package which may not be in right format. So to do best case effort we choose to use MsDeploy on Windows and hence for them as well it might pass."

There is an issue tracking AppOffline template feature requirement, so I am closing this.
