### ISSUE TITLE
AzureFileCopy fails when copying to premium storage VM

### ISSUE THREAD

**Issue by jesfer** [Microsoft/vsts-tasks#3499]
When trying to copy files to an Azure VM that uses premium storage the AzureFileCopy task apparently creates a temporary page blob storage and unless you are VERY lucky with your file sizes you get this error:

File size 1.31KB is invalid for PageBlob, must be a multiple of 512 bytes

Apparently the 512 bytes thing is inherent to page blobs but it renders the AzureFileCopy task useless for deployment to premium storage based VMs.

Would be nice if the task can be updated to handle this issue but if that is not possible it should be clearly stated in the documentation that copying to premium storage machines is not supported.

**Comment by satender2017** [comment]
Even i was trying to do the same thing,got the same error
File size 11.38KB is invalid for PageBlob, must be a multiple of 512 bytes.
Actully ,for SIT eneviroment we are using standard storages based VM,so it was succesfull for SIT,but for PROD we are using premium storage based VMs and the task failed for PROD.

Would be really nice if task can handle the premium storage based VMs also.
Is there any workaround for this?

**Comment by satender2017** [comment]
It will be really nice if some can specify any workaround for the above mentioned problem, looks like its not possible to copy the files which are not multiple of 512 bytes by using AzureFileCopy task.

**Comment by RoopeshNair** [comment]
@satender2017 
Premium Storage supports page blobs. They are used to store persistent, unmanaged disks for VMs. Unlike standard Azure Storage, Premium Storage does not support block blobs, append blobs, files, tables, or queues.

Any object placed in a premium storage account will be a page blob. The page blob snaps to one of the supported provisioned sizes. **This is why a premium storage account is not intended to be used to store tiny blobs.**

It is not the AzureFileCopy task restriction, You can verify this by uploading your files in portal directly, you should see the same error.

Thanks

**Comment by satender2017** [comment]
@RoopeshNair @bryanmacfarlane 
Thanks for inputs, We already know and understand that Premium Storage supports page blobs which have some limitation in term of size of files(allows files which are multiple of 512 bytes).
My objective is Automatically copying the build artefacts to PREMIUM storage based Azure VM. Here we are targeting CI & CD, using the same AzureFileCopy task we are able to deliver on the SIT environment which uses standard one and we know that we don't have any such restriction on standard one.

But knowing the fact Premium Storage have size restriction as it supports page blobs, the AzureFileCopy task should be capable of  handle this issue and have the capability to handle this.

I went through the below link to understand it more:-
https://docs.microsoft.com/en-us/azure/storage/storage-use-azcopy
Here I came across this line
**"•If you are using a Premium storage account, which supports only Azure page blobs, the pass /BlobType:Page as an additional argument."**

So if you are saying that it can handle Premium storage account by specifying the additional argument, then it should work, otherwise it should be clearly stated in the documentation that copying to premium storage machines is not supported rather than specifying what needs to be done for Premium storage account.

**Comment by RoopeshNair** [comment]
@satender2017 - we do set blob type as page if it is premium storage. 

Refer to Line #125 in the file: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureFileCopy/AzureFileCopy.ps1

As mentioned earlier it is not a restriction in the AzureFileCopy task.

**Comment by satender2017** [comment]
@RoopeshNair -Even I have already gone through it. Here my concern is very clear.

**Objective of AzureFileCopy task is to automatically copying the files on Azure VM or Azure Blob.** So it should work for all type of storage account knowing the limitation of every storage account .We cant cannot say  that there is  no  restriction in the AzureFileCopy task as its limitation of premium storage account. **The AzureFileCopy task should be smart enough to handle that or else should be clearly stated in the documentation that copying to premium storage machines wont work with this.**

If you are saying that it can handle Premium storage account by specifying the additional argument, then it should work, otherwise there is no point of specifying that and it should be clearly stated in the documentation that copying to premium storage machines is not supported rather than specifying what needs to be done for Premium storage account.

Just an example, if some website is not working on one web browser but working on another browser, then we have change something in that application so that it can work for both the browser.
The same thing goes for AzureFiletask, otherwise mentioned that it has some limitation with premium account.

Right now its working for standard storage account only.
Requesting you to reopen this issue.

@bryanmacfarlane-Request you please provide some inputs on this and if you can add this in the milestone: TFS.vNext (onPrem).

**Comment by RoopeshNair** [comment]
@satender2017  the ask is not clear, are you saying you will provide an file with an arbitrary file size (not in multiples for 512 bytes) and it should get uploaded to premium storage account?

**Comment by RoopeshNair** [comment]
@satender2017, Can you try uploading the file to the Azure Premium Storage in portal and let us know if it works. Thanks

**Comment by satender2017** [comment]
@RoopeshNair -My question is very clear, all I am saying is that if your document says that AzureFileCopy will work for Premium storage account, then it should be capable for copying all the files irrespective of file's size.
If that is something not possible then please update the below document saying that it only allows files which are multiple of 512 bytes:-
https://docs.microsoft.com/en-us/azure/storage/storage-use-azcopy
