### ISSUE TITLE
It would be useful if the "Run Functional Tests" build step would report its test results in real time.

### ISSUE THREAD

**Issue by matthew-horrocks** [Microsoft/vsts-tasks#3564]
It would be useful if the "Run Functional Tests" build step would report its test results in real time.

We have some large test suites which can take > 10 hours to complete. Not having these results in real time makes it hard to gauge the stability of builds as we can't see the outcome of the tests for 10 hours!

If a number of tests are failing, then we'd know that something has gone terribly wrong and we need to cancel the build and investigate.

There's obviously a workaround of "deploy more test machines" but that's not always a suitable or applicable solution.

**Comment by PBoraMSFT** [comment]
@matthew-horrocks: Thank you for the suggestion - I have added it to the backlog and closing this issue here. I would also recommend making this suggestion on user voice https://visualstudio.uservoice.com/forums/330519-team-services/category/145281-test, so that other users that may be interested in it can vote as well.
