### ISSUE TITLE
Coded UI Framework - DTAExecutionHost.exe Crashes

### ISSUE THREAD

**Issue by Cva2904** [Microsoft/vsts-tasks#3583]
Hi All,

I am facing the below issue when scheduling the build Build using Test Agent.

Test agents have been running fine for a month then suddenly started crashing on VM Test Agent.

System is displaying the message "DTAExecutionHost.exe has stopped working".

Thanks in advance,
Siva.

**Comment by Cva2904** [comment]
Hi @SatishThareja,

I have seen your comments on issues #2213.

Could you please share the executable, so that I patch it.

Thanks in advance.
Siva.

**Comment by vimegh** [comment]
@Cva2904 If you are using TFS 2015 U3 with coresponding Update 3 Test Agent ans are seeing the issue after reboot with the convert exception shown in #2213
![image](https://cloud.githubusercontent.com/assets/16918564/22874927/ba536384-f1ee-11e6-8949-57b998621a9d.png)


Then, can you try what Satish has sugessted in #2213 that is Set Update Test Agent option to true in Deploy Test Agent Task.
Queue a new build. While queuing the build, add a build variable '__ ShouldPatchMSI __' and set it to 'true'. (remove spaces in the parameter name)
After the Deploy Test Agent Step completes, DTAExecutionHost executable will be updated with the required fix and should not throw exception on reboot.

If not: then please share, so that we can further investigate: 
1. C:\DtaLogs\DtaExecutionHost.exe.log (after clearing the older logs)
2. %temp%\TestAgentConfig.Log

Thanks.

**Comment by Cva2904** [comment]
@vimegh 

i have tried the same.

@SatishThareja was talking about a exe that has to be patched.

I have tried sending mail to devops_tools@microsoft.com, but i am gettign postmaster error.

Could you please share the exe file.

Thanks

**Comment by nigurr** [comment]
@Cva2904 we did receive your mail :)
Can you uninstall Test Agent from the machine and install manually from here https://go.microsoft.com/fwlink/?LinkId=615472 or from MSDN install Test Agents 2015 Update 3.

This should have the fix for this issue. please let us know if you are still facing the issue

**Comment by nigurr** [comment]
Please let us know if it fixed your issue

**Comment by Cva2904** [comment]
@nigurr 

The above solution is working for some times and is not working some times.

I will explain in detail that things I am performing.

I am scheduling multiple build definitions on the same remote machine, that are working fine earlier and started failing from a month or so throwing the error "DTAExecutionHost.exe is stopped working".

i have performed the same steps provided by you and the build definition are getting passed some times and failing some times.

I am not seeing any error logs for the build definition.

Please let me know if you need further information on this.

**Comment by nigurr** [comment]
@Cva2904 If the process gets crashed, it should generate logs in Events. Can you please send the `Event Viewer\Windows\Application` logs 
and you can find process logs in `C:\DTALogs\` folder

**Comment by Cva2904** [comment]
@nigurr 

Please find attached DTA logs

[DTAExecutionHost.exe.docx](https://github.com/Microsoft/vsts-tasks/files/786881/DTAExecutionHost.exe.docx)

**Comment by nigurr** [comment]
@Cva2904 Can you please clear the log and attach the only failed case log. 
Additionally please report crash logs [Event Viewer logs]?

**Comment by Cva2904** [comment]
@nigurr 

it was done by mistake...

**Comment by Cva2904** [comment]
@nigurr 

i am unable to upload the document.

**Comment by nigurr** [comment]
please send us the mail devops_tools at microsoft dot com

**Comment by Cva2904** [comment]
@nigurr 

DTA log file is getting updated as we are executing different builds on the same machine.

[DTAExecutionHost.DOCX](https://github.com/Microsoft/vsts-tasks/files/789301/DTAExecutionHost.DOCX)

**Comment by Cva2904** [comment]
@nigurr 

i have mailed dtaexecutionhost error logs.

**Comment by nigurr** [comment]
Closing this issue as it's not getting reproduced. please reopen if needed

**Comment by NiharikaIqor** [comment]
Hi I am getting the same error while queue the solution.

Please help me
![error](https://cloud.githubusercontent.com/assets/27345462/24953167/505f41c8-1f48-11e7-8249-be1a0d694f37.jpg)
