### ISSUE TITLE
Display Name property from XUnit test result xml file

### ISSUE THREAD

**Issue by gustavgahm** [Microsoft/vsts-tasks#3620]
I use the _Publish Test Result_ task to publish a TestResult.xml file (genereaded by xunit) in my build. When i look at the test result in vsts only the name of each test method is displayed. I would very much like the Name property as well.

![image](https://cloud.githubusercontent.com/assets/382210/22971206/42feb51c-f375-11e6-9521-980fdb651aa7.png)

The xml could look like this:

```
<test name="CustomerFactory, Should throw argument null exception if options is null" type="CustomerFactoryTests" method="Test1" time="0.001489" result="Pass" />
```

**Comment by PBoraMSFT** [comment]
@gustavgahm: Thank you for the suggestion - I have added this to the backlog. 
I also recommend raising this issue on user voice https://visualstudio.uservoice.com/forums/330519-team-services/category/145281-test so that other users that may be interested can vote for it too. 
I will close this issue as we are not tracking backlog items here.

**Comment by gustavgahm** [comment]
Thank you! I have now created an entry on user voice. https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/18405742-display-name-property-from-xunit-test-result-xml-f
