### ISSUE TITLE
SQL Database deploy to Azure fails when re-creating the DB

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/vsts-tasks#3657]
Using locally installed SSDT / SqlPackage.exe, I can correctly deploy a pre-built .dacpac file to an pre-existing SQL Azure server + db. I've set the publish profile to completely re-create the database on deploy.

However, when I try to do this through VSTS, whilst the database is successfully dropped from the server, the new one is not created, with the following error: -

```
Database '<database name>' already exists. Choose a different database name
```

**Comment by VDanylevskyi** [comment]
I also faced with this problem.
After deleting DB using Remove-AzureRmSqlDatabase or Invoke-Sqlcmd (drop), I can not re-create DB using SqlPackage.exe, I have the same error:
`Database '<database name>' already exists. Choose a different database name`

After several minutes I be able to re-create DB. 
Maybe exists a way how to force updating the list of resources in Azure.

**Comment by isaacabraham** [comment]
I've also tried using the latest SqlPackage exe from NuGet (via the Microsoft.Data.Tools.Msbuild package) but it still has the same problem.

**Comment by VDanylevskyi** [comment]
I found one workaround that works for me. In order to avoid such problem I do following:
1. Delete an original database from the Azure (AzureDBName)
2. Create BACPAC using SqlPackage.exe from a local server
3. Import BACPAC using SqlPackage.exe to the Azure, but use a temporary name for the DB (AzureDBName_2017_02_14_9_15)
4. Rename the temporary DB (AzureDBName_2017_02_14_9_15) to the original name (AzureDBName)

**Comment by niadak** [comment]
@isaacabraham , The issue mostly because of Azure SQL latency during drop database. 
Are you able to deploy to an existing database with same publish profile directly use SqlPackage.exe?

If you are still blocked, can you please try the following:
1. Add one more "Azure Sql Database Deployment" task with inline script to Remove the database before the deployment task.

You can follow @VDanylevskyi's workaround using the same task with inline SQL script inputs.

**Comment by isaacabraham** [comment]
Yeah that does seem to be the problem. I actually don't see it with S1 databases - just with Basic. I could do that workaround - another workaround I've thought of is to deploy two databases *without* using "drop and create", but **with** "drop objects not in source": -

1. A completely empty database DACPAC, which should remove the old database tables etc. etc. without doing a drop/recreate.
2. Then deploy the real DACPAC, which could then safely deploy over a clean DB.

What do you think?

**Comment by niadak** [comment]
Yes. This is a good and more systematic work around i would say.
Please let us know if you need any other help regarding this. Please fell free to close the issue otherwise.

Thanks a lot for reporting the issue.
