### ISSUE TITLE
Abort Tests belong to Others is not reasonable

### ISSUE THREAD

**Issue by nickeyyan** [Microsoft/vsts-tasks#3755]
Hi VS Team,

We're using "VSTS Task - Run Functional Tests" to run our test cases. Sometimes due to Agent issue or network issue, test case execution aborted. After we checked the result, we assume that aborted test cases should be under failed. But now it under others with excluded test cases. It will make misunderstanding there. Is it possible to add abort category or make the aborted test cases under failed?

Thanks,
Nickey

**Comment by SadagopanRajaram** [comment]
Mapping which test outcomes show up in failed v/s others is on our backlog. You can help us prioritize this higher by posting this feature suggestion to UserVoice: https://visualstudio.uservoice.com/forums/330519-team-services/category/145281-test so that we can prioritize suggestions based on user votes.
