### ISSUE TITLE
FTP Upload Service Endpoint variable

### ISSUE THREAD

**Issue by carlosinit** [Microsoft/vsts-tasks#3758]
Hello,

I tried to make the field "FTP Service Endpoint" of the FTP upload task use a variable defined in the environment. I need to pick a different endpoint for each of the environments.

I could save my configuration with the use of the variable without any problem but at run-time I get issues.

I tried to put the friendly name in the variable and it says that it cannot find the endpoint.

I checked the debug logs and saw that what it was expecting was more the id of the endpoint, so I tried that then and it still didn't work. Same error message.

Is this usage even supposed to work?

Thanks in advance for your replies

**Comment by DavidStaheli** [comment]
Hi @carlosinit, thanks for asking.  Just last week, @yacaovsnc enhanced the FTP Upload task so that connection details can be specified inline instead of using a service endpoint.  This will let you set the URL, username, and password using variables.  If you're interested, [here](https://github.com/Microsoft/vsts-tasks/pull/3646) is the pull request.

Are you running TFS on-premises, or Team Services?  If Team Services, this enhancement _should_ be in production by next week (March 15).  If that is too late, or if you are running TFS on-premises, I can send you a zip file with instructions on how to install it using `tfx`: a Node.js-based command line utility.

**Comment by carlosinit** [comment]
Hi @DavidStaheli,

It is on Team Services that I face this problem. But your solution will indeed fix it! I will use it as soon as deployed.

Thanks a lot for your feedback
