### ISSUE TITLE
question:  how to upgrade a built-in task

### ISSUE THREAD

**Issue by amccool** [Microsoft/vsts-tasks#3768]
I need to update vstest, I am at 
\tasks\VSTest\1.0.32  on premise tfs 2015

what is the process for upgrading this build task?

**Comment by ds-ms** [comment]
Download this repo. 
run `npm install`, then build the task using `node ./make.js build --task <task_name>`
Install tfx-cli
Generate a PAT from your onPrem setup.
then run `tfx build tasks upload --task-path _build\Tasks\<task_name> --serviceUrl <url_to_your_onPrem_Setup> --token <PAT>`
This will update it to the latest version.

**Comment by bryanmacfarlane** [comment]
be careful though, you're picking up code in development if you build master.  You're better off picking up the latest release branch.

Also realize you're in untested land often.  In theory the minimum agent version is correct and should prevent you from uploading a task that demands a later server/agent.

closing since not a specific issue with a task in this repo.
