### ISSUE TITLE
Unable to disable publishing to tfs

### ISSUE THREAD

**Issue by peteakalad** [Microsoft/vsts-tasks#3863]
There is no option to disable the publish to TFS.  I want to be able to disable the publishing to TFS, to do a number of separate test tasks (one parallel, one not) and then merge the results via a separate publish tests task.

I've manage to easily do the same with an adapted version of this task with a boolean flag in the reporting section of the config to turn publishing on/off - cant see why similar couldn't be included in the base MS release.

**Comment by peteakalad** [comment]
wrong task

**Comment by peteakalad** [comment]
yes I adapted the task to disable to publishing..

**Comment by gasparnagy** [comment]
@jklaus I reviewed the VsTest task and it is not possible to disable publishing, because the publishing itself is done by the external assemblies the tasks invokes and there is no input to skip it (it is hard coded basically).

For me the problem was that I do the publishing myself (I develop a tool, SpecSync that does that), and since the VsTest task is also publishes the results, they appear twice in the "Tests" tab of the build. 

I finally tweaked the VsTest task in a way that it does not pass the build information to the compiled assembly, so the published Test Run will not be connected to the build and this way it does not appear in the "Tests" tab. 

If that would help anyone, you can find this tweaked task (called "Visual Studio Test for SpecSync") in the *free* extension [SpecSync Tools](https://marketplace.visualstudio.com/items?itemName=SpecSolutions.specsync-tools). Although "SpecSync" is in the name, you can also use it without SpecSync if this behavior is useful for you.
