### ISSUE TITLE
HOSTED VS2017 Has Preview 3 of dotnet core cli instead of final version preventing builds STILL.

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/vsts-tasks#3898]
After almost a month we still can't build dotnetcore applications properly on vsts because even with HOSTED VS2017 build agent we still get back 1.0.0-preview3-004056 instead of V1.0.0 as the version number which causes restore and build errors that aren't there with the proper version of dotnet core on it.

I've verified that there is no global.json file hanging around and it builds perfectly here in vs.net and at the command line with the right version installed.

**Comment by duckwaffle** [comment]
I'd also like to add to this, currently experiencing issues with dotnet restore on (extremely basic) solutions created with vs2017 on the vs2017 hosted queue.

When running the dotnet restore task on an ASP.NETCore project created in Visual Studio 2017, the process fails to resolve project references for .netstandard projects that are referenced by the head project.

At the begging of the restore process, the following error message is shown for each .netstandard project that is included in the solution:

`C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross\FormsMvvmcross.Server.Core\FormsMvvmcross.Server.Core.csproj(83,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

dotnet restore then continues to restore packages for the head netcore project as normal, then ends with the following error messages:

`C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Unable to resolve 'C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross.Models\FormsMvvmcross.Models.csproj' for '.NETCoreApp,Version=v1.1'. [C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross.sln] C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Unable to resolve 'C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross.Server.Core\FormsMvvmcross.Server.Core.csproj' for '.NETCoreApp,Version=v1.1'. [C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross.sln]`

I have tried the exact same build steps on the Hosted 2015 agent, and dotnet restore works perfectly fine, however the build tasks fail because the agent does not understand the new csproj format of the dotnet core project.

**Comment by ericsciple** [comment]
@JohnGalt1717 when you queue your build to the Hosted VS2017 pool, can you add a cmdline step at the top of your build definition:
file: dotnet
arguments: --version

I get `1.0.0`. Are you saying you get `1.0.0-preview3-004056`?

**Comment by bryanmacfarlane** [comment]
per @ericsciple comment, I still can't repo.

Here's what I get when I do that:

```bash
2017-03-22T17:51:54.9286497Z ##[section]Starting: dotnet --version
2017-03-22T17:51:54.9306495Z ==============================================================================
2017-03-22T17:51:54.9306495Z Task         : .NET Core (PREVIEW)
2017-03-22T17:51:54.9306495Z Description  : Build, test and publish using dotnet core command-line.
2017-03-22T17:51:54.9306495Z Version      : 0.4.1
2017-03-22T17:51:54.9306495Z Author       : Microsoft Corporation
2017-03-22T17:51:54.9306495Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2017-03-22T17:51:54.9306495Z ==============================================================================
2017-03-22T17:51:55.9234330Z [command]C:\Program Files\dotnet\dotnet.exe --version
2017-03-22T17:51:56.0105221Z 1.0.0
2017-03-22T17:51:56.0215334Z ##[section]Finishing: dotnet --version
```

**Comment by JohnGalt1717** [comment]
Sorry meant to reply this afternoon. It started working with the exact same configuration and check-in this morning.

James Hancock
603.289.7972
________________________________

**Comment by bryanmacfarlane** [comment]
OK.  Thanks for confirming.

Sorry for the issues you've had with the VS2017 rollout.  As a team we've taken the issues seriously and we're improving our image process and the ability to onboard preview versions of VS early.

**Comment by JohnGalt1717** [comment]
Great news!  Thanks!
