### ISSUE TITLE
Azure Resource Group Deployment task - Add "Test-​Azure​Rm​Resource​Group​Deployment"

### ISSUE THREAD

**Issue by mathieu-benoit** [Microsoft/vsts-tasks#3948]
With the Azure Resource Group Deployment task having the option in the Action field to invoke "Test-​Azure​Rm​Resource​Group​Deployment" could be very interesting, especially when we do CI/CD, we could validate the ARM Templates before exposing them as artifacts for the CD.
What do you think?

**Comment by degant** [comment]
This sounds interesting. But I don't think I quite got what you are looking for @mathieu-benoit. 

If you want the ARM template to be validated before it brcomes an artifact for the release definition you'd have to verify and reject it in the build definition. 

I'm not exactly sure why validation would be needed in the Azure Resource Group Deployment Task because if you have an issue in the ARM template, the CD is going to fail with or without the Test-AzureResourceGroupDeployment step in your release definition.
 
For me, validating changes in the ARM template seems like a value add so I guess having the script run and test the gated build would be good to have. But then again this can simply be done by using the Azure Powershell script task and providing the script inline or from your artifacts.

Please feel free to correct my understanding of your scenario.

**Comment by mathieu-benoit** [comment]
Hi @degant, thanks for the follow up.
That's exactly my point, I don't want to let the CD (Release Definition) failed, I would like to be able to see/catch trivial error (syntax, etc.) via Test-AzureResourceGroupDeployment during my CI (Build Definition) and for example notify people by email at each commit which could failed because of the ARM Templates. 
It's like using StyleCop, FxCop, etc. or other tools to check syntax, coding rules, etc. with programming languages like C#, Java, etc.

So what I'm currently doing is adding an Azure PowerShell step in my CI (Build Definition) to invoke Test-AzureResourceGroupDeployment over my ARM Templates. But again, I was/am wondering if it could be something wrapped by the Azure Resource Group Deployment task... just wondering.

Thoughts?

**Comment by degant** [comment]
> So what I'm currently doing is adding an Azure PowerShell step in my CI (Build Definition) to invoke Test-AzureResourceGroupDeployment over my ARM Templates. But again, I was/am wondering if it could be something wrapped by the Azure Resource Group Deployment task... just wondering.

What you are doing seems like the right way to do it. Wrapping it in the Azure Resource Group Deployment Task wouldn't make sense because you'd want only the Test-AzureResourceGroupDeployment to run during  CI and the New-AzureResourceGroupDeployment to run during CD. Right?

**Comment by dmccaffery** [comment]
Does the Deployment mode of "Validation only" not already do this?

https://github.com/Microsoft/vsts-tasks/blob/3e778c26d592fd5e6fc513e4eebee404984520eb/Tasks/AzureResourceGroupDeployment/task.json#L167

Although I found that this mode completely ignores parameters files and thus will fail if the template defines a parameter that does not have a default value. Correct me if my understanding of this is wrong.

This passes:

```sh
az group deployment validate --parameters @azuredeploy.parameters.json --template-file azuredeploy.json --resource-group dev-sandbox
```

If I use the same template and parameters with "Validation only" as a deployment mode, I get an error suggesting that a required parameter was not specified, which is what makes me believe one of the following:

1) My understanding of the "Validation only" deployment mode is completely off target
2) The parameters file is ignored and only the template itself is verified, which has limited use if all parameters do not specify a default value.

**Comment by mathieu-benoit** [comment]
Hey @dmccaffery, thank you for the heads up, that's exactly what I was looking for! I was looking at the "Action" field and not the "Deployment mode" field. You got it thanks. I'm closing this opened issue accordingly.
I will now need to play with it. Thanks for your remark about the parameter file.
