### ISSUE TITLE
Get Sources always misses out a specific folder

### ISSUE THREAD

**Issue by bthomsons** [Microsoft/vsts-tasks#3992]
I have just set up TFS 2017 with a backup of our TFVC repository but when the build agent runs a build, at the get sources task, it **never** gets the sources for one specific folder and only that folder.

I created a build from scratch and mapped over to our workspace directory in source. 

![image](https://cloud.githubusercontent.com/assets/20319781/24910918/304bb9ca-1ec1-11e7-90cb-d1d2f2b5195b.png)

This is the command that I can see being run on the build console:

```
##[command]tf vc get /version:48472 /recursive /overwrite C:\TFSAgent\_work\1\s /loginType:OAuth /login:.,******** /noprompt
```

However, if I log onto the agent and run the following from the cmd promt:

```
tf vc get /version:48472  C:\TFSAgent\_work\1\s\ /login:"[user,pass]" /noprompt /recursive
```

The folder in question is downloaded.

The folder structure is like this

Source Root
 \Folder1
 \Folder2
 \\**MissingFolder**
 \Folder3
 \etc
  
Missing folder did have some explicit permissions on it but I have removed those and the service user which the agent runs on has permission anyway.

The agent is on premise and runs on windows under a service user which has full permissions on our source.

TFS Version: 15.112.26307.0
Agent Version: 2.112.0

**Comment by ericsciple** [comment]
this sounds like the issue detailed in the troubleshooting doc

**Comment by ericsciple** [comment]
https://www.visualstudio.com/en-us/docs/build/troubleshooting#team-foundation-version-control-tfvc

**Comment by ericsciple** [comment]
Closing the issue here since this is not an issue with any task in this repo. Get-sources logic is currently baked into the agent. The [agent repo is here](https://github.com/Microsoft/vsts-agent).

If the troubleshooting section doesn't point you in the right direction, please open an issue on the agent repo. The agent doesn't communicate back to TFS as your service account. It uses the TFS-built-in build identity. Check permission for that identity... details in troubleshooting doc.
