### ISSUE TITLE
Set variables in pipeline for use later 

### ISSUE THREAD

**Issue by tarunaroraonline** [Microsoft/vsts-tasks#3996]
How can I assign a value to a variable in a task for use in another task?

I have a variable called vmPassword, I am generating a random password in the powershell task. I want to assign the value to this build variable for use in the following task to pass as a parameter to Azure resource manager deployment.

**Comment by ericsciple** [comment]
you can use the task.setvariable [command](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md)

i would recommend setting it as a secret variable and then pass into the downstream task via a task input field using macro syntax, e.g. `$(vmPassword)`

it's on the backlog to add the commands into the main documentation on visualstudio.com. i'll ping appropriate folks offline to +1 that work.

please reopen if that doesn't solve your issue.

**Comment by tarunaroraonline** [comment]
Doesn't seem to be working I am afriad. 

1. Created a testvar in the variables section and assigned a value 'blah blah'
2. Added a commandline task that echos the value of $(testvar)
3. Added a powershell task that overwrites this value... 
 
`##vso[task.setvariable variable=testvar;]testvalue`
 
4. Added a commandline task that echos the value of $(testvar)

 **Expected** - The value of $(testvar) in step 4 should be printed as 'testval' 
 **Actual** - The value of $(testvar) in step 4 is printed as 'blah blah' 
 
 The powershell below, does not update the tesvar value to testvalue. 
 `##vso[task.setvariable variable=testvar;]testvalue`

Am i doing something wrong?

**Comment by tarunaroraonline** [comment]
@ericsciple I don't have permissions to open the issue again, so tagging you directly here for notification.

**Comment by ericsciple** [comment]
@tarunaroraonline You need to call write-host or wrap in quotes to get the value to flow over STDOUT. `#` starts a comment in powershell. See the powershell-script-specific example near the top of the doc.

**Comment by tarunaroraonline** [comment]
@ericsciple sorry i overlooked that. That indeed fixed the issue i had. I am able to update the value. +1 to provide an easier way for doing this from the UI.

**Comment by abhinavongithub** [comment]
@ericsciple I am also trying to do the same.
I am creating a variable in the azure pipeline and setting its value to 123.
Now what I want, I want to change its value from PowerShell.

Write-Host "##vso[task.setvariable variable=testvar]Abhinav"
Write-Host "No problem reading $(testvar)"
Instead of printing Abhinav it always prints 123.

My simple ask is how can I change the value of testvar from PowerShell?

Thanks in advance.





![Capture](https://user-images.githubusercontent.com/38713688/55393483-f9ed3200-555a-11e9-9837-2dd66ef5c493.JPG)

**Comment by eisenhowerj** [comment]
I'm here for the same reason as the comment above. How can I update a pipeline variable?

Essentially, I don't want to kick off my build if $(variable) hasn't changed since the last time it was run. I have a script at the very beginning of my pipeline that generates a hash; if $(compare.md5) matches, exit 1 to halt the job....if it doesn't match, update the pipeline variable and continue to next step.

**Comment by abhinavongithub** [comment]
we can change this pipeline variable through the REST API.
https://docs.microsoft.com/en-us/rest/api/azure/devops/release/definitions/update?view=azure-devops-rest-5.0
Please use above link to update the variable.

**Comment by swonge** [comment]
Thanks for the pointer, it seems only work within the same agent. When I try to prompt from the another agent within the same stage, the original value set under pipeline variable will be shown

**Comment by ArieHein** [comment]
you should potentially change the value at the end of a pipeline when youre sure it was successful

**Comment by bayological** [comment]
Try Write-Host "##vso[task.setvariable testvar=Abhinav]"
