### ISSUE TITLE
SourceBinding  on vsts build task

### ISSUE THREAD

**Issue by cooljig89** [Microsoft/vsts-tasks#4008]
Hi Guys, 

I am a first time VSTS extension developer. My Current task is to build a simple VSTS Build task. 
I am stuck in source binding. Following is what I am trying.

Following is my Input

{
            "name": "KeyToSearch",
            "type": "string",
            "label": "Key to search",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "Key"
        },
        {
            "name": "Keys",
            "type": "pickList",
            "label": "Keys",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "List of keys"
        },

I would like to sourcebind the Keys field with public API, (API which does not require any authentication).
Lets says for example.
https://jsonplaceholder.typicode.com/posts
https://jsonplaceholder.typicode.com/comments

My Source Definition.

"sourceDefinitions": [
         {
            "target": "Keys",
            "endpoint": "https://jsonplaceholder.typicode.com/$(KeyToSearch)",
            "selector":"jsonpath:$.[*].body",
            "keySelector": "jsonpath:$.[*].id"
        },

I have used http://jsonpath.com/? to make sure jsonpath is correct for api I am trying. (Above one are just example).
Problem is I can not test the real one, is it even making API call. ? Is authkey compulsory?  or what I am missing here. 

Any help will be greatly appreciated. 

Thanks.

**Comment by cooljig89** [comment]
HI @pavanadepu2,  Any update/guidance  would help me continue my development for VSTS build task.
Appreciate your help.

**Comment by pavanadepu2** [comment]
@cooljig89, I am currently looking into your scenario. Please give me sometime, will get back to you with the required guidance.

**Comment by cooljig89** [comment]
Thanks @pavanadepu2   willl be looking for response.
Your response will guide me on how to proceed and architecture my/companies need.

**Comment by Fizcko** [comment]
Hi @cooljig89,

First of all you have to create a "Generic Endpoint" with the following settings :

In "Connection Name" enter "Json Place Holder".
In the "Server URL" setting enter "https://jsonplaceholder.typicode.com". Then validate.
Note you can fill the fields username and password if the target site need basic authentication.

Now you have to had a new "input" in your "task.json" like this :

```
"inputs": [{
		"name": "KeyToSearch",
		"type": "string",
		"label": "Key to search",
		"defaultValue": "",
		"required": true,
		"helpMarkDown": "Key"
	},
	{
		"name": "connectedServiceJsonPlaceHolder",
		"type": "connectedService:Generic",
		"label": "Json Place Holder Endpoint",
		"required": true,
		"helpMarkDown": "The Json Place Holder Endpoint."
	},
	{
		"name": "Keys",
		"type": "pickList",
		"label": "Keys",
		"defaultValue": "",
		"required": true,
		"helpMarkDown": "List of keys"
	}]
```

Then in your "sourceDefinitions" settings modify like this :

```
"sourceDefinitions": [
{
	"target": "Keys",
	"endpoint": "/$(KeyToSearch)",
	"selector":"jsonpath:$.[*].body",
	"keySelector": "jsonpath:$.[*].id",
	"authKey": "$(connectedServiceJsonPlaceHolder)"
}]
```

Hope this can help you.

**Comment by Fizcko** [comment]
Hi @cooljig89,

First of all you have to create a "Generic Endpoint" with the following settings :

In "Connection Name" enter "Json Place Holder".
In the "Server URL" setting enter "https://jsonplaceholder.typicode.com". Then validate.
Note you can fill the fields username and password if the target site need basic authentication.

Now you have to had a new "input" in your "task.json" like this :

"inputs": [{
		"name": "KeyToSearch",
		"type": "string",
		"label": "Key to search",
		"defaultValue": "",
		"required": true,
		"helpMarkDown": "Key"
	},
	{
		"name": "connectedServiceJsonPlaceHolder",
		"type": "connectedService:Generic",
		"label": "Json Place Holder Endpoint",
		"required": true,
		"helpMarkDown": "The Json Place Holder Endpoint."
	},
	{
		"name": "Keys",
		"type": "pickList",
		"label": "Keys",
		"defaultValue": "",
		"required": true,
		"helpMarkDown": "List of keys"
	}]

Then in your "sourceDefinitions" settings modify like this :

"sourceDefinitions": [
{
	"target": "Keys",
	"endpoint": "/$(KeyToSearch)",
	"selector":"jsonpath:$.[*].body",
	~~"keySelector": "jsonpath:$.[*].id",~~
	"authKey": "$(connectedServiceJsonPlaceHolder)"
}]

Hope this can help you.

Note : In all my tests "keySelector" never works and display a empty list.

**Comment by GitHubSriramB** [comment]
Apologies for the delay.

@cooljig89 - I see that you are missing defining authKey in the source definition. This has to point to the endpoint Id to use for getting the source definition. It would typically correspond to the endpoint input for the task (e.g. $(connectedServcieJsonPlaceHolder) like specified by @Fizcko in example above). Can you try if the issue gets resolved with this? If not, could you share the endpoint type contribution that you have & also share the visualstudio account name to investigate further?

@Fizcko - we currently do not support source definitions for "Generic Service Endpoint". You would have to define a custom endpoint in order to use source definitions.

In general, data sources is a better way to model functionality of querying external service REST APIs using endpoints. We will be continuing to enhance data sources. Source definition is there essentially for compatibility reasons, but we will not be enhancing it going forward.

Here's details on data sources:
https://blogs.msdn.microsoft.com/sriramb/2016/09/15/service-endpoints-data-sources/

You can take a look at BitBucket extension for how dataSource can be defined & consumed within task using dataSourceBinding:

https://github.com/Microsoft/vsts-rm-extensions/blob/7d4384a6c775688a99812738837435f8fb4675f6/Extensions/BitBucket/Src/vss-extension.json
