### ISSUE TITLE
Service Fabric local cluster release with vsts

### ISSUE THREAD

**Issue by SeanStayn** [Microsoft/vsts-tasks#4088]
Hey,

we use a local cluster on Windows Server and we use VSTS to manage our projects and to use continuous integration (CI) and continuous deployment (CD). CI works great with VSTS, but I don't know, how I can setup the CD with the local cluster. VSTS is in the cloud, the local cluster is local.

Our questions: 
- It is possible to combine VSTS CD with a local cluster?
- How is the right structure of the "Cluster Endpoint" in the Release configuration? 

Thank you

**Comment by bishal-pdMSFT** [comment]
@SeanStayn VSTS CD can only work if VSTS has access to your local cluster. You can setup reverse proxy and open up firewall ports so that VSTS can access your local cluster over internet.
The cluster endpoint should be of form tcp://<cluster-url>:<port>. port is usually 19000 for programmatic access.

**Comment by SeanStayn** [comment]
Thank you
