### ISSUE TITLE
[error] JAVA_HOME is not set - Xamarin forms for Android 

### ISSUE THREAD

**Issue by izefler** [Microsoft/vsts-tasks#4150]
Hello, I need help!

I am using VSTS with a private server on OS Windows Server with only prerequisites for compiling windows applications and xamarin for android.

The problem occurs in the APK signing task, as shown:

![image](https://cloud.githubusercontent.com/assets/2823190/25433093/93dc5ff6-2a5d-11e7-90d3-f845387bbd78.png)

The settings of environment variables have been performed, and configured manually in the capabilities of the agent.

**Comment by DavidStaheli** [comment]
Hi @izefler , if you have already set the JAVA_HOME environment variable, the problem is likely that it isn't actually set for the user that your build agent is running as.  One way to verify this is to add a **Command Line** task to your build and have it run the `set` command (image below), which will output the build agent's list of environment variables to your build log.  It will likely indicate that JAVA_HOME isn't set for the user your build agent is running as.  Please let us know if that's the actual problem in case we need to investigate other options.  Thanks!

![image](https://cloud.githubusercontent.com/assets/1767415/25433627/0ac80df6-2a57-11e7-9c3f-bb94c0450d1d.png)

**Comment by izefler** [comment]
Hi @DavidStaheli,

The variable in the log does not actually display when executing the task command as requested.

I have already asked the infrastructure team to set up at the user level, and run a new test.

I'll contact you as soon as I try again.

Thank you.

**Comment by izefler** [comment]
Hi @DavidStaheli.

Problem solved, thank you!

**Comment by fourthzone** [comment]
@izefler wow thanks for telling the solution. I appreciate......
