### ISSUE TITLE
Azure App Service Deploy XML Transformation ctt.exe Not Taking Effect

### ISSUE THREAD

**Issue by jamesaarondevlin** [Microsoft/vsts-tasks#4160]
Hi there,

I've started trying to implement the new XML Transformation feature found in version 3.* of the Azure App Service Deploy task.

I have made some progress and can see during the release that ctt is being called to perform the transformation. In this instance I am trying to transform Web.config according to Web.Regression.config. This environment is named 'Regression'.

![image](https://cloud.githubusercontent.com/assets/1043985/25470828/6a8dad7a-2b67-11e7-9b89-98a1eb75a841.png)

Why would ctt.exe need to be called twice?

![image](https://cloud.githubusercontent.com/assets/1043985/25470707/ccf3561e-2b66-11e7-914f-b5c298f822b5.png)

However when I double check my Web.config on the SCM site it appears to be using the default Web.config files as if it were unchanged.

Thanks for your time looking at this issue.

**Comment by jamesaarondevlin** [comment]
After investigating further I found that the token $(ReplacableToken_ was being inserted into the Web.config file of the deployed artifact during the deployment process.

I then found [this post on Stackoverflow](http://stackoverflow.com/questions/3629850/replacabletoken-when-using-web-config-transform) which lead me to add /p:AutoParameterizationWebConfigConnectionStrings=False to my MSBuild task in the build which created the artifact.

After making this change, rebuilding and re-releasing my transforms had taken effect.

**Comment by vincentdass** [comment]
@jamesaarondevlin , thanks for reporting the issue and the workaround.
We doubt to add this flag in our build template as it will break many existing customers.
It becomes more user specific to include it in additional arguments.
Instead, We planned to raise a message explicitly in logs and help message.

Just a quick question, how did you create a package with transform config file ?
Did you remove the <DependentUpon> tag for your transform config in .csproj file ?

And, XML transformation is applied twice, because it will traverse through your package and if it finds valid config file and main config file, it applies the transformation.
In your case, the transformation is applied on **PackageTmp** folder and **pakageTmp/bin** folder.

**Comment by jamesaarondevlin** [comment]
@vincentdass I agree with your conclusion to add a warning message and appreciate the quick reply.

You are correct regarding the csproj file. As a previous step in my work I removed the DependsUpon tag from each Content tag for my transform files. 

![image](https://cloud.githubusercontent.com/assets/1043985/25507632/8cfd1ea2-2bf0-11e7-9c1e-d65268b6c1cc.png)

Without this step ctt.exe would not get called during the execution of the Azure App Service Deploy task.

**Comment by vincentdass** [comment]
#4125

**Comment by vincentdass** [comment]
#4125

**Comment by vincentdass** [comment]
Help string and warning messsages are added and the fix will be available in upcoming deployments.
