### ISSUE TITLE
Run functional test task split the trx files and code coverage in the attachments

### ISSUE THREAD

**Issue by AlexARoche** [Microsoft/vsts-tasks#4243]
Hi all,
We are facing an issue using TFS 2015 (on-premise) with "Run funcional test task". When the task finishes the test execution of our dlls, we see in the test results attachments several trx files (one per dll). Do we have any way to generate just one trx/codecoverage file? As VSTest tasks is already doing?
We are using Run functional test task version 1.0.28

![image](https://cloud.githubusercontent.com/assets/28107621/25743029/90b6dc70-3192-11e7-92fe-d109e49840b3.png)

Regards,
Alex

**Comment by nigurr** [comment]
Hi,

Thanks for suggestion. Currently we produce individual TRX file per slice. 
Please add your suggestion https://visualstudio.uservoice.com/forums/330519-team-services and vote for it. Will happy to improve the experience.

**Comment by jrodrigv** [comment]
Hi,

I'm also quite interested on this feature. 

It is quite annoying to have several trx generated per solution, because then I will need to check each of them to review its test output.

In my opinion the output from the Fuctional Test Task Run should be as close as possible to the output from the VSTest task.

**Comment by nigurr** [comment]
@PBoraMSFT FYI

Please do give feedback/suggestions through UserVoice.
