### ISSUE TITLE
Azure App Service Deploy Task: Part of UI is missing

### ISSUE THREAD

**Issue by Sheludchenko** [Microsoft/vsts-tasks#4252]
Few days ago i discovered that part of UI is missing for Azure App Service Deploy task.
E.g. i'm unable to change config transformation options.
![image](https://cloud.githubusercontent.com/assets/11521541/25747904/d843280e-31b1-11e7-8bf4-a3a9bba8f89c.png)

I've tried it on two VSTS accounts and three browsers (Chorme, IE and FF).

**Comment by arjgupta** [comment]
Hi @Sheludchenko , please select the azure subscription and the app service name that you want to use, the other inputs will appear accordingly.

**Comment by Sheludchenko** [comment]
Hi @arjgupta. Thanks for your reply. I was able to see additional options.
But I have to reselect application each time I want to edit additional options.
![image](https://cloud.githubusercontent.com/assets/11521541/25751030/503c4476-31bc-11e7-8454-8d45160f7231.png)

**Comment by arjgupta** [comment]
Hi @Sheludchenko , if you select an app name from the app service name dropdown, then you will be able to edit additional options without having to reselect application, but if you use a Variable like in the screenshot, then it won't work. We are working on fixing this issue. It will fixed in the next couple of days.

**Comment by arjgupta** [comment]
Hi @Sheludchenko , a fix for this issue has been deployed. I am closing this issue. Please feel free to reopen it if you continue to face problems with the task.
