### ISSUE TITLE
Azure Sql Database Deployment fails to login when passwords contain a dollar sign

### ISSUE THREAD

**Issue by farlee2121** [Microsoft/vsts-tasks#4379]

**Comment by mvvsubbu** [comment]
Thanks for reporting can share release logs by setting system.debug to true

**Comment by farlee2121** [comment]
The draft build history disappeared and I'm out of build minutes for the month. I'll have to get you specific error logs at a later time

**Comment by rajatagrawal-dev** [comment]
Couldn't repro it. Please reopen if you face the issue again.

**Comment by cbrianball** [comment]
I just ran into this, it appears to only be an issue if the first character of the password is a dollar sign ($). This wasn't an issue when deploying a dacpac file, but when I added another step and selected the "SQL Script File" type option, that's when I ran into the error.

I updated the password have the dollar sign ($) as a character other than the first character and I didn't run into an issue.

Steps to reproduce:
1. Create variable to store the password (doesn't matter if it's secure or not), but make sure the first character is a dollar sign ($)
1. Add a `Azure SQL Database Deployment` task
1. Configure the task with the correct subscription, server, database, and admin login
1. Use the variable created in Step 1 for the password
1. Fill out any other required fields
1. Save the release definition
1. Execute the release definition

I don't know if this is technically a bug or not since I would guess you could use a PowerShell variable (if you are going to use an environment variable or something similar) for your password.

**Comment by tomasherceg** [comment]
This issue should be reopened - the problem still persists (at least when I specify the credentials using Connection String).
I am getting "Login failed for user 'xxx'" when the connection string contains the dollar sign. 
Once I change the password not to contain the dollar sign, the task works perfectly.
