### ISSUE TITLE
Slot Swap to Production fails with Error: Conflict

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/vsts-tasks#4457]
Getting this error on all of my deployments:

> 2017-06-02T20:28:24.0234037Z ##[section]Starting: Manage Azure App Service - Slot Swap
2017-06-02T20:28:24.0244050Z ==============================================================================
2017-06-02T20:28:24.0244050Z Task         : Azure App Service Manage (PREVIEW)
2017-06-02T20:28:24.0244050Z Description  : Start, Stop, Restart, Slot swap or Install site extensions for an Azure App Service
2017-06-02T20:28:24.0244050Z Version      : 0.2.8
2017-06-02T20:28:24.0244050Z Author       : Microsoft Corporation
2017-06-02T20:28:24.0244050Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=831573)
2017-06-02T20:28:24.0244050Z ==============================================================================
2017-06-02T20:28:24.3394091Z e8c1fefe-7fa1-4ce0-9a7b-a8c13b97ca7f exists true
2017-06-02T20:28:24.4980765Z Requesting swap slot for Web App : onenotebug
2017-06-02T20:28:26.0799465Z Successfully updated deployment History at https://onenotebug-staging.scm.azurewebsites.net/deployments/71496435304792
2017-06-02T20:28:27.7215524Z Successfully updated deployment History at https://onenotebug.scm.azurewebsites.net/deployments/71496435304792
2017-06-02T20:28:27.7225585Z ##[error]Error: Failed to swap slots for Azure Web App: onenotebug. Error: Conflict
2017-06-02T20:28:27.7275582Z ##[section]Finishing: Manage Azure App Service - Slot Swap

Any idea what to do?

**Comment by kevinluvian** [comment]
I encountered this issue, and solved it.
my problem was the slot I want to swap is turned off, so I turned it on before swapping it

**Comment by Tadimsky** [comment]
Hmm it did look like my staging slot was stopped. I started that and tried deploying and it seems to have succeeded!
Is that what you saw too?
I have a load test that runs against staging first though so not sure how that succeeds but the slot is down...

**Comment by kevinluvian** [comment]
yeah thats what i mean ;)

**Comment by Tadimsky** [comment]
Great - thanks @kevinluvian!

It would be good if the task could figure this out and start the app if it will fail if it is not running.

**Comment by RoopeshNair** [comment]
Task can't differentiate whether the slot was intentionally turned-off or due to some other reason. So Task auto turning-on the slot is not an option.

You can add Azure App Service Manage: to start the slot so that you don't run into this issue.

**Comment by Tadimsky** [comment]
Ok @RoopeshNair but then we should at least improve the error message or have this error listed somewhere on some support document.
> 2017-06-02T20:28:27.7225585Z ##[error]Error: Failed to swap slots for Azure Web App: onenotebug. Error: Conflict

Does not tell me anything about what happened and why it failed. It's not clear that the slot is not running, nor that it is the staging slot instead of production especially since it has just deployed to staging and run a load test against it.

**Comment by northtyphoon** [comment]
I encountered the same issue. The error message is not very helpful. Is the error returned from App Service? Does the error contain any detail? If yes, the vsts task should output it. If not, you guys need to provide the feedback to App Service team to add error detail.

**Comment by RoopeshNair** [comment]
Appreciate your feedback, we are looking into improving the error message

**Comment by ggirard07** [comment]
I don't get it, why is it not supported?
In my flow i wanted to:
1. Take my production slot offline to prevent db changes while performing the new version deployment
2. Deploy to my staging slot
3. Start my staging slot to perform database migration
4. Swap slot to complete the deployement

But this is not possible as swapping an offline slot (in my case my old production slot) is not supported.
The only solutions I have are:
1. Start my old production slot in order to be able to swap: this will allow my users to access the old version prior to swap, which I definitely don't want.
2. Use a third slot containing a dummy maintenant page to ensure my production is always started: perhaps not so bad but it means I need yet another artifact in my release pipeline.

Why is this a limitation? Is this due to some technical points with the load balancer?
Because on a user perspective I currently don't understand why this will be forbidden...

**Comment by RoopeshNair** [comment]
@ggirard07, 

>1.  Take my production slot offline to prevent db changes while performing the new version deployment
> 2. Deploy to my staging slot

Not sure I got your query. are you saying during deployment both staging and production will be down?

**Comment by ggirard07** [comment]
@RoopeshNair Yes at first sight that is what I tried to do, until I noticed there was no way to customize the page served to clients while web app is offline.

My question now is simply: Why is it not permitted to swap an offline slot?

**Comment by vincentdass** [comment]
@ggirard07 , This is by design to deny swap slot for stopped App Service.
One of the reason is Zero down-time deployment. Swapping the stopped app service is a contradiction here. You can also contact Azure App Service team to get more detailed info.

You can also take your production slot down by placing `app_offline.htm` file in root folder.

**Comment by tom-stones** [comment]
I have a multilayer application with webjobs and webfunctions that are triggered by servicebus messages.  It is not safe for my application to have production and staging slots pulling from the queue at the same time - it could lead to sequencing issues.  I've tried stopping the production slot, starting the staging slot then switching, but that isn't allowed.   If we must have a rule here then should it not be that the staging slot should be running before the switch, rather than the current rule that both must be running before the switch?

**Comment by slawomir-brzezinski-at-clarksons** [comment]
We are having the issue as well, and the workaround found by our team-member is to rather use a change to firewall rules to cut the traffic to the service, without stopping the service, so that the task can succeed.

Re [vincent1173's comment](https://github.com/Microsoft/azure-pipelines-tasks/issues/4457#issuecomment-346873940): 
> the reason is Zero down-time deployment. Swapping the stopped app service is a contradiction

The justifications attempted with the above statement seem to be rather vague to argue with, but I'd like to try to reason with them:

> _'reason is Zero down-time deployment'_

Zero down-time is a property of a change, not the CI infrastructure. Then perhaps you mean here that _"Azure DevOps' "Slot Swap Task" doesn't support changes that require down-time"_. Then, that's hardly a _reason_, but rather a limitation of the Azure pipeline task, so something that should be considered to add.

> _"Swapping the stopped app service is a contradiction"_ _(author's note.: to Zero down-time)_
To say "it's a contradiction" is some subjective way to label this. To look at it from the other subjective side, I'd rather say that an observation of a stopped service suggests **there is a downtime already**, so the CI pipeline doesn't do much service to reducing the downtime by denying to actually bring the other slot up that would have stopped the downtime. I'd say that it would actually make sense to allow the user to ignore this, to be able to use a single, battle-proven pipeline to cover all update needs (what if, for example the service is stopped due to a defect in the old version, and the new version fixes it?).

Now, I appreciate the task raising it as a potential problem might serve of value to some, but it would really be good if this was at least configurable, ideally per-release, to choose to ignore this situation, which would give an elegant solution to 'exceptionally' support deployments-with-downtime.

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Re [vincent1173's comment](https://github.com/Microsoft/azure-pipelines-tasks/issues/4457#issuecomment-346873940): 
> the reason is Zero down-time deployment. Swapping the stopped app service is a contradiction

The justifications attempted with the above statement seem to be rather vague to argue with, but I'd like to try to reason with them:

> _'reason is Zero down-time deployment'_

Zero down-time is a property of a change, not the CI infrastructure. Then perhaps you mean here that _"Azure DevOps "Slot Swap" Task doesn't support changes that require down-time"_. Then, that's hardly a _reason_, but rather a limitation of the Azure pipeline task, so something that should be considered to add.

> _"Swapping the stopped app service is a contradiction"_ _(author's note.: to Zero down-time)_

To say "it's a contradiction" is some subjective way to label this. To look at it from the other subjective side, I'd rather say that an observation of a stopped service suggests **there is a downtime already**, so the CI pipeline doesn't do much service to reducing the downtime by denying to actually bring the other slot up that would have stopped the downtime. I'd say that it would actually make sense to allow the user to ignore this and carry on to stop the downtime.

Now, I appreciate the task raising it as a potential problem might serve of value to some, but it would really be good if one was able to use a single, battle-proven pipeline to cover all update needs (what if, for example the service is stopped due to a defect in the old version, and the new version fixes it?).
To be backwards compatible, this could default to the current behavior, but it could be configurable per-release to choose to ignore this situation, which would give an elegant solution to 'exceptionally' support deployments-with-downtime.
