### ISSUE TITLE
variables included in Instructions parameter of manual intervention task could not be recognised in the alert email

### ISSUE THREAD

**Issue by Yanjingzhu** [Microsoft/vsts-tasks#4516]
In [this ](https://www.visualstudio.com/en-us/docs/build/concepts/process/phases#server-phase)document, "You can use built-in and custom variables to generate portions of your instructions." 
But the variables in Instructions did not be replaced by its value in my email.
There is the related thread:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/1a2f815a-1b6e-4b02-a33b-9a81258d39da/release-variables-are-not-being-expanded-in-email?forum=tfsbuild

**Comment by chandan-anjani** [comment]
Hi, TFS2017U1 does not have this feature (variable expand support in MI instructions). 2017u2 has this feature. In above message release definition name and environment names only expanded. $(Agent.Name) not expand because server phase does not contain agent. $(Release.Artifacts.{webredirect}.DefinitionName) not expand because this is not in variable format. If you try same variable in powershell, you will get error.
