### ISSUE TITLE
Xamarin.iOS build task fails due to comma ',' in certificate name.

### ISSUE THREAD

**Issue by nevalenny** [Microsoft/vsts-tasks#4558]
As reported by users in Mobile Center when we use msbuild for the task it fails:

```
[command]/bin/rm -f _xcodetasktmp.plist
[command]/bin/cp -f /Users/ci/agent/vstsagent/_work/1/s/.certs/ios_cert.mobileprovision /Users/ci/Library/MobileDevice/Provisioning Profiles/355441d3-5dv4-46ce-819e-5c8z92e3a66a.mobileprovision
[command]/Library/Frameworks/Mono.framework/Versions/4/bin/msbuild /Users/ci/agent/vstsagent/_work/1/s/SadPirates.sln /p:Configuration=Beta /p:Platform=iPhone /p:BuildIpa=true /t:Rebuild /p:CodesignKeychain=/Users/ci/agent/vstsagent/_work/1/s/_xamariniostasktmp.keychain /p:Codesignkey=iPhone Distribution: The Sad Pirates, LLC (ZQ1PUR9RGF) /p:CodesignProvision=355441d3-5dv4-46ce-819e-5c8z92e3a66a
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1006: Property is not valid.
Switch:  LLC (ZQ1PUR9RGF)

For switch syntax, type "MSBuild /help"
##[error]Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/4/bin/msbuild failed with return code: 1. For guidance on setting up the build definition, see https://go.microsoft.com/fwlink/?LinkId=760847.
```

**Comment by jamesatgithub** [comment]
got same error with configuration of Release, but same repo with Ad-Hoc configuration build well

**Comment by madhurig** [comment]
We have determined this happens when using "msbuild" option in the task inputs due to bug https://github.com/Microsoft/msbuild/issues/471. We are investigating a way to apply the workaround in the task.

**Comment by jamesatgithub** [comment]
@madhurig when will this fix be available on Mobile Center?

**Comment by nevalenny** [comment]
@jamesatgithub in Mobile Center we hotfixed that problem by rolling back to `xbuild` tool. Try to resave your branch configuration. The new VSTS task is planned to go live in a week or so.

**Comment by jamesatgithub** [comment]
@nevalenny thanks I can confirm the hotfix works!

**Comment by ckrempp91** [comment]
This is still a problem with on-premise TFS update 2, when using msbuild it does not quote properly for the Codesignkey property. I added a comment to the [original issue](https://github.com/Microsoft/msbuild/issues/471#issuecomment-331577784) as well because it seems like spaces are treated as delimiters as well.

**Comment by madhurig** [comment]
@ckrempp91: These changes didn't make it into TFS 2017, they are included in TFS 2018. You can try building the task and uploading to your TFS server using the  tfs-cli: https://github.com/Microsoft/tfs-cli 

Thanks,
Madhuri

**Comment by ckrempp91** [comment]
Sorry for the delayed response @madhurig, I finally got some timed and tried out your suggestion. I was able to work around the issue, per your suggestion, but I did encounter a few issues though:

1. Instead of using the TypeScript file, I had to package the `xamarinios.js` file instead (I am unsure if TypeScript is able to run on macOS, but my machine would not allow it)
2. I had to add the node_modules manually to the build task because the .js file was not able to properly load them. (From the research that I can gather this seems to be a limitation of the node requirements and will be addressed in a later version)
3. The .js file had the same issue with the comma so I had include a fix:
Here is the original Sign Identity code (within the js file) - 
`buildRunner.argIf(signIdentity, signIdentity)`
Here is the change that I had to make to get MSBuild to work correctly -
`let escapedSignIdentity = '/p:Codesignkey=' + signIdentity.replace(/,/g, "%2C");
buildRunner.argIf(signIdentity, escapedSignIdentity);`

In case anyone else has the same problem what I did to upload the build task into the on-premise TFS 2017 (Update 2) server was this:

1. You will need to have the tfs-cli installed on your computer, setup information can be found [here](https://github.com/Microsoft/tfs-cli/blob/master/README.md)
2. I followed the documentation outlined [here](https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md) to create a temporary build task using this command:
`tfx build tasks create`
3. I copied the GUID `id` that was generated.
4. Pasted all of the contents of the Xamarin.iOS build task (code can be located [here](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/XamariniOS)) into the build task folder that was generated within the second step.
5. I then placed the copied GUID `id` into the `id` filed of the copied `task.json` file located within the generated build task folder.
6. I changed the `name`, `friendlyName`, `description`, and `version` on the `task.json` file to different values to allow for easy and unique identification of the build task.
7. I logged onto the macOS build agent to look at the ..\\myagent\\_work\\_tasks\XamariniOS{SomeGUID}\ folder for the node_modules downloaded from the standard Xamarin.iOS build task, and copied those into the new build task folder.
8. Replace the `xamarinios.ts` with the `xamarinios.js` file located on the macOS build agent. 
--**Make sure to include the fix to the js file that was outlined in the upper part of this comment**--
Here is an example of the files that should be within your build task folder:
![image](https://user-images.githubusercontent.com/15944499/34801895-7d92b070-f630-11e7-9a7a-83a48e402c34.png)
9. Now that your build task is ready you can perform the following command:
`tfx build tasks upload --task-path ./{BuildTaskFolderName}`
If your `Service URL` and `Personal Access Token` have not been saved, then you will need to provide them for the upload.
10. If you receive a message saying the upload was successful, then you will see the new task under the "Build" category of the available build tasks with the name you provided.

**Comment by madhurig** [comment]
@ckrempp91: Thanks for the details. The .js file has to be uploaded to the server, the build agent only runs the .js and can't run the .ts.
