### ISSUE TITLE
Is there any hardcoded dependency to the order of PSModulePath

### ISSUE THREAD

**Issue by ebrucucen** [Microsoft/vsts-tasks#4697]
When I get another build agent to the pool, it started giving an error on `Install-Module Pester` of the PowerShell script I am running. Inspired by one of the [SO answers](https://stackoverflow.com/questions/36582305/why-testexplorer-in-vs2015-failed-to-load-pester-module) suggested changing order of the PSModulePath to point where PSGet is,  which did work surprisingly. Just curios, is this a bug, by design? 
```
Install-Module : The term 'Install-Module' is not recognised as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At C:\agent\_work\1\s\DeploymentScripts\build.ps1:5 char:5
+ Install-Module pester -Force
```

**Comment by ericsciple** [comment]
@ebrucucen closing the issue here. I don't think this is related to the CI infrastructure or any task in this repo. Please reopen if I'm mistaken.

It sounds like powershell's module autoloading is not working. My guess is some module higher up in your psmodulepath is interferring with the module autoloading feature of powershell. And it doesn't sound like the offending module is delivered by the agent (i dont think it is, since you were able to fix by adjusting your psmodulepath).
