### ISSUE TITLE
AzureRmWebAppDeployment: Task.json contains invalid dictionary ("options")

### ISSUE THREAD

**Issue by JohannesDrexler** [Microsoft/vsts-tasks#4706]
There is a problem with the file "vsts-tasks/Tasks/AzureRmWebAppDeployment/task.json" (#4626).
This file contains a dictionary at line 194 with an empty key. Is this intended to be this way?

I have a script that downloads/builds and uploads the tasks from this repo into a TFS and this Powershell-script is failing when reading this task.json (ConvertFrom-Json is having problems with the empty key at line 195). I do that to log what task is beeing processed and check if this is a newer version than the one already in the TFS.

**Comment by rajatagrawal-dev** [comment]
Hi @JohannesDrexler 
I guess we did not expect it to cause any issues and it served our purpose(not sure but the actual reasoning could have been something else).
Maybe you can try a different parser in your powershell script for now. For example you can try installing 'Newtonsoft.Json' module and use 'ConvertFrom-JsonNewtonsoft' (which I read allows empty keys) instead of ConvertFrom-Json. See if it works.
But I don't think we'll treat it as a bug unless we discover some more serious drawbacks.

**Comment by JohannesDrexler** [comment]
Using 'Newtonsoft.Json' and 'ConvertFrom-JsonNewtonsoft' this works
