### ISSUE TITLE
Azure File Copy Task does not appear to remove the WinRMCustomScriptExtension

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#4840]
The Azure File Copy task is able to setup WinRM and it does this through a custom extension.  However, it does not appear to remove it once finished.

This means that if someone else comes along and tries to use a custom script extension they get the error:

> Multiple VMExtensions per handler not supported for OS type 'Windows'. VMExtension 'customScriptArtifact-183362431' with handler 'Microsoft.Compute.CustomScriptExtension' already added or specified in input.

An example of this issue:

https://github.com/Azure/azure-devtestlab/issues/251

Should the task remove the extension once completed?

**Comment by sachinma** [comment]
@RoopeshNair should we start doing it?

**Comment by RoopeshNair** [comment]
@gregpakes, Fair feedback, we are working on a newer version of the Azure File Copy task which relies on VM extension instead of WinRM to copy the files. We will look into cleaning it up, post deployment. However it will be a while before we can get to it.

As a workaround, for now, you can uninstall the extension using script, if found.
