### ISSUE TITLE
Azure Resource Group Deployment task can't handle space in parameter override value

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-tasks#4864]
I am trying to pass a SQL connection string from a variable into a template override parameter for the Azure Resource Group Deployment task v2.* and the connection string has a space in the value.

![image](https://user-images.githubusercontent.com/4112046/28557202-9d20158a-70d0-11e7-9865-b34090a529f7.png)

I get this error when the deployment executes
```
2017-07-24T06:28:31.3651327Z ##[debug]Overriding Parameters..
2017-07-24T06:28:31.3651327Z ##[debug]Overriding key: pfxBlob
2017-07-24T06:28:31.3651327Z ##[debug]Overriding key: ConnectionString
2017-07-24T06:28:31.3651327Z ##[debug]Overriding key: 
2017-07-24T06:28:31.3661320Z ##[debug]There was an error while overriding '' parameter because of 'TypeError: Cannot read property 'type' of undefined'.
```

If I take the space out of the SQL connection string the issue goes away.  Even though I was able to work around this (change "User ID=..." in my connection string to "UID=..."), but it seems like a bug.

**Comment by ds-ms** [comment]
Enclose the value in quotes, if it has spaces. 
You should supply parameters in override parameters as `-ConnectionString "$(ConnectionString)"`.

This is because, the agent upon execution replaces the $(ConnectionString) with the actual value. 
For example, if your connectionString was "abc def" the string we receive upon execution would be 
`-ConnectionString abc def`. Our parser would consider `abc` and `def` to be 2 different literals and we end up assigning only the first literal to this key. Upon execution, the value of the connectionString would be only `abc` when you're expecting `abc def`. When you enclose it within quotes, `abc def` would be treated as a single literal.

**Comment by gregjhogan** [comment]
@dm-ms I tried putting single quotes around it and the single quotes went into the value.  Are double quotes handled differently than single quotes?

**Comment by ds-ms** [comment]
Yes. We only assume double quotes for strings; Although this is a use case we can take care of in the task. But it's not handled as of now.

**Comment by gregjhogan** [comment]
I think how it works now is ridiculously confusing.
