### ISSUE TITLE
Edit BuildNumberFormat from release VSTS

### ISSUE THREAD

**Issue by don18** [Microsoft/vsts-tasks#5036]
Hi,

I would like to add my own versionnumber to the build number format of a release. [Release-$(MyVariable)-$(rev:r)]

I have a build that starts a release when completed.
The build has the VersionNumber in a package that I want to use in $(MyVariable).
So when the release is created or if it is finished it has to have a title like Release-2017.3-1.

Is this possible? Or is there a way that I can customize or influence the BuildNumberFormat of the release with my own variable after trigger by a build.

**Comment by bansalaseem** [comment]
You can create release names from build numbers, build branches as mentioned here. 

https://www.visualstudio.com/en-us/docs/build/concepts/definitions/release/index#numbering

If you can assign 2017.3 to your build number, then you can use it in the release name.

**Comment by don18** [comment]
Thanks for your reply.
But that means that I have to create a variable for the build and update it before the build is queued?

**Comment by bansalaseem** [comment]
I am treating the build numbers as a black box w.r.t. release names, so if you have the correct values in the build number, then you will able to use it in the release. 

We do have a concept of draft release where we allow you to change the variables and those changes gets reflected in the release names. For example: - I can have a format mask $(System.TeamProject).$(Foo)Release-$(rev:r) and I can define the value of Foo in the draft release and then the release will have name like VSOnline.BarRelease-1. But since you seem to be creating releases on completion of builds, I am assuming that this approach will not work for you.
