### ISSUE TITLE
"Deploy Azure App Service" task not actually deploying a migrated ASP.NET MVC Core 2.0 web app

### ISSUE THREAD

**Issue by DeveloperUniversity** [Microsoft/vsts-tasks#5111]
Hi, I've documented this issue extensively on StackOverflow:

[https://stackoverflow.com/questions/45851749/vsts-continuous-deployment-of-asp-net-mvc-core-2-0-app-to-azure-web-apps-not-dep](https://stackoverflow.com/questions/45851749/vsts-continuous-deployment-of-asp-net-mvc-core-2-0-app-to-azure-web-apps-not-dep)

In brief, after 100 successful releases to Azure Web Apps Web Sites using VSTS CD, I migrated my ASP.NET MVC Core 1.1.2 web app to ASP.NET MVC Core 2.0.  Now, the "Deploy Azure App Service" says it is performing a deployment, however nothing is *actually* getting unzipped and deployed to the staging slot.

I provide access to log files and log excerpts, screenshots, etc. on the StackOverflow question.

At first, I was 100% convinced this was specific to my scenario.  However, after reading carefully through logs I'm less convinced this is me and growing in my concern that this task is not ready for ASP.NET MVC Core 2.0 apps.  In fact, your readme.md at this URL:  

[https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureRmWebAppDeployment/README.md](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureRmWebAppDeployment/README.md)

... says ...

" The task works for ASP.NET, ASP.NET Core 1 and Node.js based web applications."

If taken literally, there's no mention of support for ASP.NET Core 2.0.

**Comment by KrishnaAdityaB** [comment]
@kmkumaran @vincentdass 
Quick question - Does the Deploy Azure App Service task support ASP.NET Core 2.0?

**Comment by DeveloperUniversity** [comment]
One new pertinent detail as I continue to debug this.

The new (preview) App Service Editor shows that the .zip file has been moved to the /wwwroot folder, **however it does not unzip it.**

![6](https://user-images.githubusercontent.com/19307883/29681040-2319c33a-88cc-11e7-82cf-4cee2e265fb2.png)

**Comment by vincentdass** [comment]
@DeveloperUniversity, Can you please share the debug logs for both Build and Release?
To enable debug logs, set '**system.debug**' variable to '**true**' in both Build and Release Definition.
Once you trigger the Build, on successful completion, Release will also be triggered.

Please share both the logs. If you want to share them in private, send the same to `RM_Customer_Queries.@Microsoft.com`

**Comment by DeveloperUniversity** [comment]
@vincentdass Here's a screencast that displays the build and release steps and the steps I'm taking to reproduce this, etc. AND the logs w/ the debugging flag added:

https://youtu.be/qKFd1XrCK5s

Build Logs w/ debug flag
https://1drv.ms/u/s!AvZL4t4dMuo5lq0fYpt0toHyW_vifA

Release Logs w/ debug flag
https://1drv.ms/u/s!AvZL4t4dMuo5lq0eQt7XwgAClI3Y6w

**Comment by vincentdass** [comment]
@DeveloperUniversity , thanks for the logs and video, really appreciated. 👍 
It looks like you are already archiving the published folder in `.NetCore Publish` Task.
![image](https://user-images.githubusercontent.com/20121508/29832350-856abf16-8d05-11e7-9fbf-819c579e4a14.png)

Since, `Add Project Name to publish path` is enabled, the zip is named as `<WebProjectName>.zip`
![image](https://user-images.githubusercontent.com/20121508/29832380-a8f35812-8d05-11e7-8ad1-38a8ddc15139.png)

Archive Task (next to Publish task) again archives the published zip resulting in Nested Zip Structure.

On Release Side, Azure App Service Deploy Task takes a single zip as input and extracts only the given package. So the inner package (Actual content to be deployed) is not extracted to App Service.

There are multiple ways to resolve this issue:
One way is to remove Archive Task from Build definition and use Publish Artifact task to publish `WebProjectName.zip` as artifact. Since your release definition, Package Input is `BeastMuffin-CI\drop\*.zip`, the package from artifact will be matched with given regex and will be deployed to App Service.

Please feel free to ping, if any assistance required.

**Comment by DeveloperUniversity** [comment]
That was it.  THANK YOU for taking the time to understand and resolve the problem.

Off to the next hurdle ...
