### ISSUE TITLE
DTAExecutionHost.exe Error : System.Exception: NUnit Adapter 3.7.0.0:

### ISSUE THREAD

**Issue by debasisj** [Microsoft/vsts-tasks#5127]
Hi,
We are trying to run Selenium tests with Nunit framework. However when build and run tests on the remote agent, getting error - DistributedTests: UnExpected error occurred during test execution. Try again.

Close inspection of log  - DTAExecutionHost.exe Error: 0 : ExecutionTaskStateModel.AbortSlice : System.Exception: NUnit Adapter 3.7.0.0: Test discovery complete

Build sequence - 
NuGet restore 
Build Solution 
Deploy test agent 
Run Tests on remote 
Publish 

Target .NetFrameWork - 4.5.2
TestAgent Version 2017/2015 - both case failed
NUnit.3.6.1

Here is DTA log 
[DTAExecutionHost.txt](https://github.com/Microsoft/vsts-tasks/files/1254889/DTAExecutionHost.txt)

**Comment by debasisj** [comment]
I have now updated nUnit to 3.7 but getting same issue.. any idea?

**Comment by prawalagarwal** [comment]
Hi @debasisj,

From your previous logs : vsts-agent-win7-x64-2.119.1\_work\2\s\packages\NUnit3TestAdapter.3.7.0\tools\NUnit3.TestAdapter.dll is getting picked up as the adapter, which means your task is restoring 3.7 adapter instead of 3.6.1. Have you tried running the tests locally directly from vstest.console by providing this adapter? If this works and task is still failing, please clear/delete the DTAexecutionhost logs, run the scenario again and reach out to us at devops_tools[AT]microsoft[dot]com with the execution host logs.

Thanks

**Comment by prawalagarwal** [comment]
Closing this. Please re-open if you are still facing the issue.
