### ISSUE TITLE
Run functional tests - test results includes an unrelated past test run

### ISSUE THREAD

**Issue by xenalite** [Microsoft/vsts-tasks#5283]
After a CI test run failed, I examined the test results. They included an unexpected test run from months ago (see completed date for the top one), as well as the current one.
This is the first time I saw an issue like this. The 2 test runs are from 2 different test VMs as well.

![image](https://user-images.githubusercontent.com/4509839/30270249-ca191012-96e3-11e7-896d-275c1bc88a62.png)

Using latest VS15 test agent.
We are on VSTS since about a month ago. The other test run might be coming from a time prior to VSTS migration, when we were still on TFS, and the release ID matched.

**Comment by whichrakesh** [comment]
Hi Oskar,
Can you please provide the name of your VSTS account?

**Comment by xenalite** [comment]
@whichrakesh 
rcss-02-willistowerswatson

**Comment by whichrakesh** [comment]
We investigated the issue and found that the test run data that you have imported to VSTS have associations with releases prior to migration. As the releases data have not been migrated and now that the releases are getting created from the start, this is causing the corresponding old test runs associated with the release ID to show up. As you queue more releases, you would be seeing other old test runs as well. I have sent a mail to your ID with the detailed investigation.

**Comment by xenalite** [comment]
@whichrakesh 
Is there going to be a fix for this issue to perhaps only associate the latest release ID with the test run, or should this issue be closed?
We might have to remove old test runs prior to the migration to prevent further false-negative test failures.

**Comment by whichrakesh** [comment]
These are some of the ways to fix this.
- You can set a retention policy for the test runs before migration so that these get deleted. This is the best and the fastest solution if you don't need the old test runs data as it will take care of removing the other metadata corresponding to the test run.
- We can delete the test runs which have old invalid releases associated with them.
- We can set the release ID of the test runs which have past releases associated with them to a dummy release Id so that you don't see these in any future releases. For this, we need to update the run statistics of releases which have already been assigned the old test runs.

**Comment by xenalite** [comment]
@whichrakesh 
We set retention policies for old test runs.
Thanks.
