### ISSUE TITLE
Get value of variable dynamically AzureRgDeploymentTask

### ISSUE THREAD

**Issue by Mauzer93** [Microsoft/vsts-tasks#5477]
I am using the Azure Deployment task to deploy our ARM template to Azure, but I am struggling on reading the value of a vsts dynamically.

When using version 1, I used the following command to get the value of a variable dynamically:
commonStorageAccountConnectionString  (Get-Variable -Name '$commonStorageAccountConnectionStringSecretName' -ValueOnly)

Now I am upgraded to version 2 and this powershell syntax does not work anymore... (Because it is made in NodeJs instead of PowerShell I asume?)

Is there a way to get it working in version 2?

**Comment by sachinma** [comment]
You can just specify $(commonStorageAccountConnectionStringSecretName)

**Comment by Mauzer93** [comment]
That does not work. 
The value of the commonStorageAccountConnectionStringSecretName is for example: testSecret.
I have a vsts task that downloads all secrets from the key vault.
This vsts task will expose one secret => testSecret.

If I pass it like this: $(commonStorageAccountConnectionStringSecretName), than the secret name itself is used as value. (testSecret)

What I really want is something like this:
$($(commonStorageAccountConnectionStringSecretName))
but this result in a string $(testSecret) being used, instead of the actual value of the secret...

**Comment by sachinma** [comment]
Double expand is generally not available within the framework today. Another tip: If you are using a custom task for downloading secerts from key-vault; then you can consider using AzureKeyVault task which sets the secert variables correctly for the next task to consume. 

Also If $(commonStorageAccountConnectionStringSecretName) i.e. testSecret in the example is a pre-known value to you and it is not a secret itself, you can directly specify $(testSecret) in the task. Something like this is what we recommend in AzureKeyVault task. Otherwise you will have to insert one PS task in between and use that to do the second Get-Variable.

**Comment by ds-ms** [comment]
You could directly add key vault references to your template as well, to avoid the downloading and referencing separately phase.
Here's a link to some [documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-keyvault-parameter)

**Comment by Mauzer93** [comment]
Thanks for the replies. I have chosen to hard code the variable name in the override parameters step.
