### ISSUE TITLE
Executes the PS script on the remote machine asynchronously returns response

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#5549]
I am using  Task  "PowerShellOnTargetMachines"  and when I run my PS script on the remote machine I have to wait response from remote PS session.  

Why I cannot see output (logs) of my script throughout its implementation?
When session is done I will get all output of my script.

I tried to figure it out. 

You use cmdlet `Invoke-PsRemote` which the
return `DeploymentResponse`  - this object contains all the logs related to deployment and remote infra structure service.  This file `Microsoft.TeamFoundation.DistributedTask.Task.Deployment.dll ` contain class `InvokePsOnRemoteCmdlet`  where has the method `RunPowerShellAsync` - It executes the PS script on the remote machine asynchronously returns response.

Could you please explain what exactly this mean -  "asynchronously returns response"  - returns response in real time?

How can I redirect the pipelines from  `Invoke-PsRemote` to my current session in TFS 
Example: `$deploymentResponse = Invoke-Command -ScriptBlock $psOnRemoteScriptBlock | %{Write-Host "##[command]$($_.DeploymentLog)" 2>&1}`

Thanks in advance!

**Comment by Ajay-MS** [comment]
@kardinal3000 

Live logging is currently not being supported with "PowerShellOnTargetMachine" task.  I suggest you try PowerShell task with Deployment Group in order to take advantage of live logging. [Getting started for DG.](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/deployment-groups/)
