### ISSUE TITLE
Deploy Test Agent fails (unzip failed, unable to stop dtaexecutionhost)

### ISSUE THREAD

**Issue by ISAF87** [Microsoft/vsts-tasks#5556]
Our Deploy Test Agent task is stuck on two issues:

Unable to stop DTAExecutionHost. 
Details : 'A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Are you sure you want to perform the Stop-Process operation on the following item: DTAExecutionHost(5696)?'. For troubleshooting, refer https://aka.ms/remotevstest.

When I stop the process manually and trigger a new release in TFS:
2017-10-04T11:21:56.8490579Z ##[warning]Task 'TestAgentConfiguration' for machine <machine> Error : System.Exception: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'file:///C:\TestAgent\TfsAssemblies\Newtonsoft.Json.dll' or one of its dependencies. The system cannot find the file specified."
2017-10-04T11:21:56.8490579Z ##[warning]Task 'TestAgentConfiguration' for machine <machine> Log : 

The task creates the folder: C:\TestAgent and copies a zip file to it. However, it fails to unzip, causing the above exception. (The missing dll is in that zipfile)

We are running TFS 2017 UPD2, and use the VS2017 test agent

**Comment by abhishkk** [comment]
@ISAF87 unzip failure is happening only after DTA task stucks?

Can you share following logs to devops_tools@microsoft.com?
**For Unable to stop DTAExecutionHost issue**:
1. Add/set 'system.debug' variable to true in your build/release definition and share the logs folder.
2. Share DTAExecutionHost.exe.log from test agent (usually its present at C:\DtaLogs)

**For unzip failure issue**:
As you mentioned that you are manually stopping the process after you get 'Unable to stop' issue. Re-trigerring the build causes unzip failure. Can you share logs for this run too? (here also release logs and DTAExecutionHost.exe,log after setting 'system.debug' variable to true)

**Comment by vimegh** [comment]
@ISAF87 Closing the issue now as there is no response, please feel free to reopen if you are still facing the issue. In that case please share logs as advised by @abhishkk . Thanks.

**Comment by ISAF87** [comment]
We dug through the powershell scripts used in the tasks. We resorted to more silently kill the DTAExecutionhost process, if it is even running. As the existing code crashes if it doesn't run (or is not able to stop it for some other reason). If for any reason the stop DTAExecution host part fails, it will not unzip the folder.

Regardless of: stopping the dtaexecutionhost process, or the unzip step results, it will try to load the assemblies to continue the deploy task agent. Which is impossible, as after all, the assemblies are not unzipped. In my opinion, this task is programmed poorly.

**Comment by cltshivash** [comment]
@ISAF87 We have had onboarding issues with the DTA task due to the remote deployment and the dependency on the Test Agent SKU. We have been working on the path forward for the functional testing scenarios in the VSTS pipeline and the blog post https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/ should provide details on it. 

Once the multi agent phase is available broadly in build, we would deprecate the RFT/DTA tasks and recommend using the vstest task for both unit test and functional testing scenario.

**Comment by guillegr123** [comment]
Just to share more details on the workaround that I think @ISAF87 described, I've done the next modifications in the PowerShell scripts of the DeployVisualStudioTestAgent task:

- File: VerifyTestAgentInstalled.ps1
  Added -Force argument to the command `Stop-Process $dtaProcess -ErrorAction SilentlyContinue`
  This prevents the error: "A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Are you sure you want to perform the Stop-Process operation on the following item: DTAExecutionHost(5696)?"
- File: TestAgentConfiguration.ps1
  Added -Force argument to the command `Stop-Process -Name "DTAExecutionHost" -ErrorAction SilentlyContinue`
  This prevents the error: "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'file:///C:\TestAgent\TfsAssemblies\Newtonsoft.Json.dll' or one of its dependencies. The system cannot find the file specified."

The `-Force` argument forces the process to be stopped without asking for a user confirmation (https://stackoverflow.com/a/3143511/806975).

In my case, the scripts were located at "C:\agent\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.1.35" on the build server. I know it is not the best way to modify the files there, but was a desperate measure. Although the new [VSTest task is already available](https://docs.microsoft.com/en-us/vsts/build-release/test/getting-started-with-continuous-testing?view=vsts), it only allows to run the tests via a build Agent, which I don't have in the machine where I need to run the task.
