### ISSUE TITLE
Unable to build Xamarin.iOS build on VSTS

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [Microsoft/vsts-tasks#5565]
![untitled](https://user-images.githubusercontent.com/10863510/31228809-62e2ed24-a9fc-11e7-961e-fcaaf28297d1.png)

This is the error I am getting. It's a Xamarin forms application and I am trying to have CI for Xamarin.iOS app.

**Comment by pjquirk** [comment]
Could you post that error log as text instead of an image? Some of the error is cut off, and it would also make it more searchable.

**Comment by sawankumarbundelkhandi** [comment]
@pjquirk Here is the exact error - https://gist.github.com/sawankumarbundelkhandi/daa1b1b03a5075cca424011ac62722de

**Comment by pjquirk** [comment]
For posterity, the error encountered is:

>The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by pjquirk** [comment]
I'm assuming your project is targeting .NET Core since this error commonly is a result of loading .NET Core projects targeting VS 2017 with older build tools.  Try the following:
- Use MSbuild instead of xbuild. The latter is deprecated and likely doesn't support the 'new' project format for .NET Core.  This is an option in the Xamarin.iOS task.
- Use VS 2017 to build the project.  If you're using hosted VSTS, you can use the 'Hosted VS2017' agent queue when setting up your build definition.

**Comment by sawankumarbundelkhandi** [comment]
@pjquirk Thanks. It worked.
