### ISSUE TITLE
Distribute by Class/Tests/Assembly across multiple machines

### ISSUE THREAD

**Issue by bhavesh729** [Microsoft/vsts-tasks#5675]
It would be great if there was 3 ways to distribute tests (in the form of a radio button or similar in the Run Functional Task UI)

- Distribute by Class
- Distribute by tests
- Distribute by assembly

.. and then based on the option we select, we design our UI tests accordingly for optimum performance. The level of idempotency of each test would then depend on where the state of the application is setup/teardown -
 either in ClassInitialize/ClassCleanup OR TestInitialize/TestCleanup OR Assemblyinit/AssemblyCleanup. 

This would be very useful for long running UI tests that are hard to optimize just because of the application workflow depth.

**Comment by PBoraMSFT** [comment]
@bhavesh729 - thank you for the feedback. I would like to call out a couple of things:
1. We are moving away from the 'Run Functional Tests' (RFT) task. All the capabilities of RFT task are available in 'Visual Studio Test version 2 task' (VSTest v2), so we recommend you to move to that.
2. In the VSTest v2 task, we already have the ability to distribute based on 
a. Tests and number of agents (simple distribution)
b. Based on past running history (for most efficient utilization of agents).

We are also looking at providing a mechanism for custom distribution, so that other cases are covered generically and solves the idempotency issue you mentioned above. I will be happy to discuss our approach with you as we finalize the plans here. Will you be okay to have a skype chat with me? If so, please send me an email at pbora AT microsoft DOT com so that I have your email contact.

**Comment by bhavesh729** [comment]
@PBoraMSFT Thanks for pointing that out. We are currently using TFS 2017 Update 1 (on premise), so currently are missing the VSTest v2 task. (although the plan is to upgrade soon).
Also I will be happy to discuss more. Thanks!

**Comment by PBoraMSFT** [comment]
This has been copied to backlog. Closing this out as we don't track backlog items here.
