### ISSUE TITLE
dotnet restore cannot auth against VSTS NuGet feed

### ISSUE THREAD

**Issue by lukepuplett** [Microsoft/vsts-tasks#5722]
Regards the new dotnet VSTS build tasks in 2.* (preview).

Not sure what the etiquette is about cross-posting, but I reported this over on the NuGet hub but one of my DevOps dudes recommended posting here, too.

https://github.com/NuGet/Home/issues/6109

~

Ultimately between me and our DevOps guys, we find the authentication mechanism for NuGet quite opaque and so when it goes wrong, we run out of ideas fast.

You can see that I quickly revert to using the NuGet.exe command line to try and restore, with no luck. At one point I got a "402 Payment Required" error which was significant in its difference to a flat 401.

As a general point, over the last few years, auth has become a very big pain and productivity killer for me and my colleagues across numerous consulting contracts now. I think as a programming community we really oughta be doubling-down on our efforts to make this stuff JustWork™ and go to pains to explain how it works and provide a means to log out detailed messages (just) from the auth systems.

A nice NuGet feature is the write-out of the feeds used and config files used at the end in the summary. Could this concept be used when it comes to the auth and identity options available and which was chosen and why?

Thanks for any assistance.

(Back Monday)

Luke

**Comment by jotaylo** [comment]
If you're only running on Windows build agents we recommend using the NuGet build task instead of the dotnet build task. 

If you set the system.debug variable in your build to true, you'll get a slightly more chatty overview of the auth logic, but it's admittedly not very readable without the source code for reference.

Does your build service account have permission to read from the feed you're using? The build service account is unable to authenticate using the nuget credential provider, it uses a token (provided by the build process) for authentication.

**Comment by keithrob** [comment]
Dead thread.
