### ISSUE TITLE
Cannot Change DotNet Publish Directory to Something Specific

### ISSUE THREAD

**Issue by jcdickinson** [Microsoft/vsts-tasks#5846]
## Environment
- Server - VSTS: k2tfs, cloud, 115
- Agent - Hosted: Hosted VS2017

## Issue Description

It is impossible to run `dotnet publish -o` and have the files go to a specific directory. The project name is always appended, this makes commands such as the following impossible:

```sh
dotnet publish -c Release -o obj\Docker\publish
```

Which is absolutely required to work *as quoted* if you wish to use Docker debugging in Visual Studio locally - that is the command that Visual Studio executes itself (cannot be changed).

It might be best to put [this leaky abstraction](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DotNetCoreCLI/dotnetcore.ts#L302) behind a toggle, or disable it for relative paths (`dotnet publish` uses the project directory and not the pwd if `-o` is a relative path).

## Workaround

Publish to a temp directory and copy the files to the correct one.

**Comment by sachinma** [comment]
This toggle is available in the 2.* version of the task with the label "Add project name to publish path" You can uncheck it to have the behavior you desire. 
The reason for having this option was because the task accepted multiple projects. And in that case it would be desirable to have each publish go to a separate folder.
