### ISSUE TITLE
PowerShell v2 (preview) task: Inline option does not offer arguments

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-tasks#5914]
The version 2 version (currently in preview) of the `PowerShell` task does not offer arguments if the inline script option is chosen.
This is required e.g. for passing in secrets, which can only be passed in as arguments.

**Comment by daveVSTS** [comment]
Apologies for the late response.  I am looking into this now.  I will get back to you in the next few days.

**Comment by ericsciple** [comment]
you can use macro syntax or env block in yaml (backlog item to add to designer)

**Comment by ericsciple** [comment]
or for public variables you can use powershell syntax to access the environment variable

**Comment by daveVSTS** [comment]
We intentionally removed this because of security concerns.  There is still work before we move this out of preview.  We wanted to prevent the easy path from leading to secret values getting logged/traced.

The best way to pass secrets is to use the env input. There is a backlog item to add this to the designer, which we will have before moving v2 of this task out of preview. Short of that, you can use the macro syntax to inline the variables into their script (or use $env:MY_VARIABLE_NAME within the script to access public variables).

**Comment by bryanmacfarlane** [comment]
The env block can be set in yaml.

@ericsciple - do we have a yaml sample how to use the env block?

That allows the script to use envvars instead of arguments which can get logged in various systems and options.

**Comment by bergmeister** [comment]
Release definitions cannot be defined in YAML at the moment. I am afraid this is not a solution at the moment.

**Comment by bergmeister** [comment]
@daveVSTS @bryanmacfarlane 
Release definitions and task groups cannot be defined in YAML at the moment. I am afraid this is not a solution at the moment.
