### ISSUE TITLE
Can note reliable output any messages from powershell scripts

### ISSUE THREAD

**Issue by DynConcepts** [Microsoft/vsts-tasks#6018]
Very strange...

Documentation shows usage of "Write-Host" for outputting messages...but I am running *remote* PowerShell ["PowerShell on Target Machines" task], and any usage of Write-Host causes an exception [not complete unexpected].

So I tried "Write-Verbose $message - Verbose" and I do get partial output. It appears to be an issue with the stream not being flushed properly....early messages come through fine, but putting a bunch of them near the end of the script, only some come out....

So, what is the proper way to have PowerShell executing on a Remote machine and still get the ability to have log messages, including those types like: https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

**Comment by rajatagrawal-dev** [comment]
Hi @DynConcepts 
Can you try Write-Output and see if that causes the same behavior as well? If you have a dummy script where you face this issue, please share the script as well. You can also add a variable system.debug and set its value to true in the release definition. This will give you more detailed logs. Please check if the logs are missing here as well.

**Comment by DynConcepts** [comment]
Thanks for the info... Using Write-Output caused some very interesting results. I would like to share the script and logs with you, but can not do so here [public forum]. Please send contact information to: david.corbin@dynconcepts.com and we can exchange the information there....

**Comment by rajatagrawal-dev** [comment]
@DynConcepts You can mail your logs at RM_Customer_Queries@microsoft.com. We discovered some problems with Write-Output as well just a couple of hours ago. So I think the safest bet is Write-Verbose as of now. Do include the script and logs of the release when you used Write-verbose.

**Comment by DynConcepts** [comment]
SENT.

**Comment by rajatagrawal-dev** [comment]
Hi @DynConcepts 
You described 2 problems:
1. Logs did not come in correct order
2. Verbose logs were missing

Both of these are valid problems and have corresponding bugs filed which are being tracked. 
For the first issue, the reason I believe is that we flush the streams one-by-one and so the logs appear in that order too. Apparently stream redirection does not work either. We'll try to fix it in the future.

For the second issue, please see this related issue #3406. There is a bug on IIS team. Since you are using IIS commands like Get-WebAppPoolState, you are facing this issue. Please refer the issue for possible workarounds (like using (Get-Item IIS:\AppPools\KGMAppPool).State). You might have to use 'Import-Module WebAdministration' to access the IIS:\\.

**Comment by rajatagrawal-dev** [comment]
Closing this as it will be treated as enhancement and worked upon later.

**Comment by DynConcepts** [comment]
Since this issues is closed, it loos like a Support ticket will need to be generated as the client needs a working solution for TFS-2017 RTM
