### ISSUE TITLE
How to really run tests in parallel, or troubleshoot when they don't

### ISSUE THREAD

**Issue by cordialamit** [Microsoft/vsts-tasks#6066]
Hi,
Wanted to check why vsts task doesn't run tests in parallel.
I have two assemblies holding unit tests and checked "run in parallel" option in vsts task but it still executes sequentially.

Can someone please help here:
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=7376351&_a=summary

Thanks
Amit

**Comment by ShreyasRmsft** [comment]
Hi @cordialamit, this parallelization option that you have selected is meant if you're tests are present on more than one assembly. It is not meant if all tests are present in the same assembly. The help link for the option calls this out and explains the type of parallelization. 

Are your tests present in more than one assembly?

**Comment by ShreyasRmsft** [comment]
Hi @cordialamit, any updates?

**Comment by cordialamit** [comment]
Hi,

Yes these tests are present in two assemblies and that’s why I expected them to run in parallel.

Thanks
Amit

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ShreyasRmsft** [comment]
Hi @cordialamit, can you re-run the build with system.debug set to true and share the logs.

Also how are ascertaining that the tests aren't being run in parallel? Is it based on execution time difference when the option is enabled and otherwise?

**Comment by ShreyasRmsft** [comment]
Hi @cordialamit, any updates

**Comment by cordialamit** [comment]
Sure. Here is the build with system.Debug=true

https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=7583630&_a=summary

Thanks
Amit

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ShreyasRmsft** [comment]
@cordialamit 

The task is passing the correct settings for running the tests in parallel

2018-01-10T19:06:28.0968470Z ##[debug]Running VsTest with settings : 
2018-01-10T19:06:28.0968664Z ##[debug]<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
2018-01-10T19:06:28.0968859Z ##[debug]<RunSettings>
2018-01-10T19:06:28.0969034Z ##[debug]  <RunConfiguration>
2018-01-10T19:06:28.0969226Z ##[debug]    <TargetPlatform>x64</TargetPlatform>
2018-01-10T19:06:28.0969412Z ##[debug]    <MaxCpuCount>0</MaxCpuCount>
2018-01-10T19:06:28.0969805Z ##[debug]  </RunConfiguration>
2018-01-10T19:06:28.0969998Z ##[debug]</RunSettings>

<MaxCpuCount>0</MaxCpuCount> This being the appropriate setting.

Again how are you ascertaining that the tests aren't being run in parallel? Is it based on execution time difference when the option is enabled and otherwise?

**Comment by cordialamit** [comment]
Yes, its based on execution time. No two tests ran at the same time while there they are in different assemblies

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ShreyasRmsft** [comment]
@cordialamit can you try using this with the [Visual Studio Test Platform Installer task](https://docs.microsoft.com/en-us/vsts/release-notes/2017/nov-28-vsts#test ) to get the latest platform version? This feature may not have been supported in the version you are on and even if it doesn't work we'll get more logs from the latest platform version with system.debug set to true.

**Comment by ShreyasRmsft** [comment]
@cordialamit Closing this issue, please reopen if the tests are not run parallelly even on the latest test platform version
