### ISSUE TITLE
Run Functional Tests Task intermittently gets stuck

### ISSUE THREAD

**Issue by NickHarvey2** [Microsoft/vsts-tasks#6071]
## Issue Description

When running our tests remotely using the [Run Functional Tests Task](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/RunDistributedTests), the task intermittently gets stuck. The build log just repeats `DistributedTests: Test run '######' is in 'InProgress' state.` until it is eventually aborted.

### Build log
`...`
`2017-12-19T06:36:30.1042924Z DistributedTests: Test run '109175' is in 'InProgress' state.`
`2017-12-19T06:36:40.1513757Z DistributedTests: Test run '109175' is in 'InProgress' state.`
`2017-12-19T06:36:50.1984716Z DistributedTests: Test run '109175' is in 'InProgress' state.`
`2017-12-19T06:37:00.2455515Z DistributedTests: Test run '109175' is in 'Aborted' state.`
`2017-12-19T06:37:10.2770166Z ##[warning]DistributedTests: Test run is aborted. Logging details of the run logs.`
`2017-12-19T06:37:10.3863884Z ##[warning]DistributedTests: New test run created.`
`2017-12-19T06:37:10.3863884Z Test Run queued for Project Collection Build Service.`
`2017-12-19T06:37:10.3863884Z `
`2017-12-19T06:37:10.3863884Z ##[warning]DistributedTests: Test discovery started.`
`2017-12-19T06:37:10.3863884Z ##[warning]DistributedTests: UnExpected error occured during test execution. Try again.`
`2017-12-19T06:37:10.3863884Z ##[warning]DistributedTests: Error : Some tests could not run because all test agents of this testrun were unreachable for long time. Ensure that all testagents are able to communicate with the server and retry again.`
`2017-12-19T06:37:10.3863884Z `
`2017-12-19T06:37:10.3863884Z ##[warning]DistributedTests: Test run aborted. Test run id: 109175`
`2017-12-19T06:37:10.4957781Z ##[error]System.Exception: The test run was aborted, failing the task.`
`2017-12-19T06:37:10.8551528Z ##[error]PowerShell script completed with 1 errors.`

**Comment by NickHarvey2** [comment]
Relevant DTAExecutionHost.exe.log:
[DTAExecutionHost.exe.log](https://github.com/Microsoft/vsts-tasks/files/1571887/DTAExecutionHost.exe.log)

**Comment by janpieterz** [comment]
#6073 might be related to this. Do normal unit tests work for you @NickHarvey2 ?

**Comment by NickHarvey2** [comment]
You mean do tests work when run with the task "Visual Studio Test (Run tests with Visual Studio test runner)" ? If so, yes, they work fine.

Also, this was intermittent before (seemed to occur when multiple builds were trying to run tests remotely at the same time on the same box), but then it started happening consistently with each build. I rebooted the box, and that seems to have fixed the problem for now, but I don't really like that as a long term fix.

**Comment by ShreyasRmsft** [comment]
Hi @NickHarvey2,
After going through the DTAExecutionHostLogs it's evident that the DTAExecutionhost.exe process on the remote machine is crashing because it is unable to find a dll

DTAExecutionHost.exe Error: 0 : Main.InitializeAndStartExecutionHost. Exception occured during initialization/start: System.IO.FileNotFoundException: Could not load file or assembly '**Microsoft.VisualStudio.TestPlatform.ObjectModel**, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I have a few hunches as to why this might be happening but will need your help to pinpoint the cause:
1) Check whether this dll is present inside the testAgent folder.
2) Also if possible enable fusion logs on the remote machine and we can get to know where its trying to pick up this dll from.
3) Also note that RFT does not support running multiple builds that point to the same remote machine at the same time.

**Comment by nigurr** [comment]
@NickHarvey2 
Sorry for the trouble. it's known issue and it's fixed here - https://github.com/Microsoft/vsts-tasks/pull/5623/files
This will be available for on-prem @TFS 2018 Update1.

Thanks for your support

**Comment by Shahyads** [comment]
I have the same problem. Is there any workaround for TFS 2017?
