### ISSUE TITLE
How can i debug azure function in azure portal.

### ISSUE THREAD

**Issue by singhbibek** [Microsoft/vsts-tasks#6103]
I don't see any debug process through i can debug my azure function in azure portal instead of VS17

**Comment by arjgupta** [comment]
Hi @singhbibek , can you explain a bit more about your scenario? What do you mean by "debug my azure function in azure portal" ? If you mean remote debugging, then visual studio supports debugging azure app service ( on top of which azure function is built upon), both locally and remotely. You can find more details [here](https://docs.microsoft.com/en-us/azure/app-service/web-sites-dotnet-troubleshoot-visual-studio#remotedebug)

**Comment by singhbibek** [comment]
HI @arjgupta , i have few azure functions which I deployed in azure portal so can I run it from Azure portal and debug there? instead of doing in the visual studio.

**Comment by arjgupta** [comment]
@singhbibek , I am not sure if this is possible from the azure portal. I would suggest you to follow up on the Azure Functions forum [here](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureFunctions) . I am closing this issue since it is not related to vsts task. Reopen this if you face any issues with the vsts app service deploy task
