### ISSUE TITLE
Vsts Tasks using Get-VSTSinput

### ISSUE THREAD

**Issue by evolcode** [Microsoft/vsts-tasks#6189]
## Environment
VSTS

Task is a Azure PowerShell Task

- Agent - Hosted or Private: 
    
Hosted 2017

## Issue Description
Im running a VSTS task "Azure PowerShell" with the lastest version of PowerShell Running.

Here is the snippet of my code:Import-Module -Name VstsTaskSdk
Trace-VstsEnteringInvocation $MyInvocation

$billing = Get-VstsInput -Name Billing -Require
$resourceGroupName = Get-VstsInput -Name Resource

I keep getting an error:

The term 'Trace-VstsEnteringInvocation' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Do I import a module? What am I missing?

**Comment by arjgupta** [comment]
@evolcode , VstsTaskSdk is not present in psmodulepath at the time when your script execution begins, and so it will not be imported. The agent imports it for use in the context of the task, and right before the script execution begins, all commands imported from it are removed so that they do not conflict with names of functions that you may be using in your script. From the snippet you posted, I see that you want to use the Get-VstsInput function. If you want to pass arguments, You can do that using the "Script Arguments" input in the task.

**Comment by arjgupta** [comment]
Hey @evolcode , were you able to pass arguments using the "script arguments" input ?

**Comment by ericsciple** [comment]
+1 the vsts task sdk is for task authors, not ad-hoc scripts.
