### ISSUE TITLE
vsts-npm-auth cannot find .npmrc file

### ISSUE THREAD

**Issue by Zaniarr** [Microsoft/vsts-tasks#6248]
I have downloaded the vsts-npm-auth package [here](https://www.npmjs.com/package/vsts-npm-auth#install-and-run-the-tool) and followed the instructions 

`npm install -g vsts-npm-auth`
`vsts-npm-auth -config path-to-your\.npmrc`

I try and run `vsts-npm-auth -config path-to-your\.npmrc` but it gives me a file not found error. 
Not sure what i'm doing incorrect. 

![capture](https://user-images.githubusercontent.com/31470504/35096725-26ab585a-fc45-11e7-8c0a-cc31f3a628a3.PNG)

The .npmrc file exists and is there.

![capture1](https://user-images.githubusercontent.com/31470504/35096773-58d678dc-fc45-11e7-8963-31a27686a639.PNG)

**Comment by aldoms** [comment]
From the screenshot it looks like your file is missing the leading dot, can you confirm the file includes the leading dot?

The file should be named `.npmrc` or you could modify the path you're passing to vsts-npm-auth to not have the dot.

I think file explorer won't let you directly name the file `.npmrc` because it thinks it's missing the filename, so you'll need to do it through the cmd prompt.

**Comment by Zaniarr** [comment]
Thank you. that seems to have solved my issue!!!
