### ISSUE TITLE
Attempting to publish symbol packages should give helpful error message

### ISSUE THREAD

**Issue by jerickmsft** [Microsoft/vsts-tasks#6253]
When attempting to publish a package and a symbols package, one will fail with a cryptic error message.  Instead, the user should be directed to [some symbol service instructions](https://blogs.msdn.microsoft.com/devops/2017/11/15/vsts-is-now-a-symbol-server/)

**Comment by alkampfergit** [comment]
The error is the following: suppose we have a build where we create one or more nuget packages with generate symbols package activated

![image](https://user-images.githubusercontent.com/358545/35113388-8c15a7fe-fc81-11e7-8c3a-b65fa61e3761.png)

Now you configure the build to **push all packages to VSTS feed** 

![image](https://user-images.githubusercontent.com/358545/35113471-c8581d32-fc81-11e7-9c0f-550b68922b76.png)

The build fails with a generic message (1), if you read all the log you can indeed verify that the error happens when the task is trying to publish symbols package (2). 

![image](https://user-images.githubusercontent.com/358545/35113646-79f0268e-fc82-11e7-8846-19e36d6b3383.png)

I'm expecting a clearer error message, something like "Push of Symbols package failed, this feed does not support symbols package" or something that helps me to immediately troubleshoot the root cause.

If I remove the option of Create Symbols Package from the nuget task, the build runs just fine.

**Comment by jerickmsft** [comment]
@alkampfergit  What's the name of the task with the "Create Symbols Package" option?

**Comment by keithrob** [comment]
@alkampfergit ,
The root of the problem is that the Push wildcard pattern in is picking up *.symbols.nupkg and attempting to push it into the Feed.  Please change your pattern to [1] to exclude files with the suffix *.symbols.nupkg.

We have changed the defaults in the task to [1] and that change will be deployed to all accounts shortly.  I will take an action item to see if we can change the STDERR from VstsNuGetPush.exe to something more intelligible.
Thanks,
Keith

[1] $(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg
