### ISSUE TITLE
Publish VsTest Results Error: Failed to publish test results: Data at the root level is invalid. Line 1, position 1.

### ISSUE THREAD

**Issue by KostaVlev** [Microsoft/vsts-tasks#6316]
## Environment
- Server - VSTS 
     
Build: 20180130.36 
Task: Publish VsTest Results

- Agent - Hosted: 
    
Name: Hosted Agent

## Issue Description

Publish VsTest Results Error: Failed to publish test results: Data at the root level is invalid. Line 1, position 1.

Settings:

![untitled](https://user-images.githubusercontent.com/10883826/35583441-ebc2d1da-05bf-11e8-8d09-064891249645.png)

Result from VsTest TestAssemblies task

![untitled1](https://user-images.githubusercontent.com/10883826/35583565-5ac2ebec-05c0-11e8-8593-ad14a257ebf1.png)

### Error logs

2018-01-30T17:42:28.5385238Z ##[section]Starting: Publish VsTest Results
2018-01-30T17:42:28.5388442Z ==============================================================================
2018-01-30T17:42:28.5388624Z Task         : Publish Test Results
2018-01-30T17:42:28.5388741Z Description  : Publish Test Results to VSTS/TFS
2018-01-30T17:42:28.5388851Z Version      : 2.0.3
2018-01-30T17:42:28.5388957Z Author       : Microsoft Corporation
2018-01-30T17:42:28.5389095Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613742)
2018-01-30T17:42:28.5389246Z ==============================================================================
2018-01-30T17:42:31.5080876Z ##[warning]Failed to publish test results: Data at the root level is invalid. Line 1, position 1.
2018-01-30T17:42:31.6598770Z ##[section]Async Command Start: Publish test results
2018-01-30T17:42:31.6599033Z ##[section]Async Command End: Publish test results
2018-01-30T17:42:31.6600136Z ##[section]Finishing: Publish VsTest Results

**Comment by SadagopanRajaram** [comment]
I see that you already have a Vstest TestAssemblies task. Is there a reason why you require the Publish task? The vstest Test Assemblies task will automatically publish the results. 
In the publish task, you have a filter for *.coverage. Can you please remove this from the filter and try again?

**Comment by KostaVlev** [comment]
Vstest TestAssemblies task does the publishing and removing the *.converge solves this problem. I guess I can't use  Publish VsTest Results to publish .converge files...

The reason I am having the Publish VsTest Results is a try to workaround another issue I have with the published .coverage file by the  Vstest TestAssemblies task which doesn't contains my project DLLs but it has only microsoft.windowsazure.storage.dll and moq.dll

**Comment by nigurr** [comment]
@KostaVlev, currently you can only publish .coverage file with valid trx file. If the trx file contains the link to coverage file, the same will be published and code coverage report is generated.
Please let us know if you need more help on the same?

**Comment by nigurr** [comment]
Closing this issue as the functionality is working as expected. Please share your feedback/feature requests here: https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services

**Comment by eflorespalma** [comment]
I'm using my own agent and I am getting this error.

##[warning]Atleast for one assembly start time was not obtained due to tag not present or parsing issue, total run duration will now be summation of time taken by each assembly
Obtained XUnit Test Run Start Date: 2019-06-04T16:57:35.3622403Z and Completed Date: 2019-06-04T16:57:35.3622403Z
##[warning]Invalid results file. Make sure the result format of the file '/myagent/_work/74/s/TestResults/TestResults/ms-rp-contracts.trx' matches 'XUnit' test results format.
##[warning]Atleast for one assembly start time was not obtained due to tag not present or parsing issue, total run duration will now be summation of time taken by each assembly
Obtained XUnit Test Run Start Date: 2019-06-04T16:57:35.3650094Z and Completed Date: 2019-06-04T16:57:35.3650094Z
##[warning]Invalid results file. Make sure the result format of the file '/myagent/_work/74/s/TestResults/ms-rp-contracts.trx' matches 'XUnit' test results format.
