### ISSUE TITLE
[Feature request] Extract the xml variable substitution from iis web deploy task into a new task

### ISSUE THREAD

**Issue by ovebastiansen** [Microsoft/vsts-tasks#6487]
And make it available to use on app.config files as well.
I am working on deploying windows services, that has different values for different environments. This was originaly fixed with the slowcheeta plugin and build pr environment. I want to go over to use variable substitution instead, and use the same build artifact for all environments

**Comment by RoopeshNair** [comment]
There are extension available in marketplace which enables tokenization, variable substitution etc. Have you considered them?

Currently we are working on issues impacting broader set of customers. We will not be able to get this anytime soon. 
We know this issue is important to you, we will continue to monitor this.
