### ISSUE TITLE
Task 'InstallTestAgent' takes forever and timesout

### ISSUE THREAD

**Issue by swiec** [Microsoft/vsts-tasks#6580]
## Environment
- Server TFS on-premises version: 15.117.27024.0
   
- Agent - Private: 
    
    - Windows Server 2016, agent version: 2.124.0
## Issue Description

As title says. Task runs for an hour, until it's canceled by timeout. Logs says nothing.

### Error logs

![intaltestagenttimeout](https://user-images.githubusercontent.com/2485271/36850346-cbb0e2a6-1d66-11e8-8fe8-cc115ff8aa41.png)
[Worker_20180301-095247-utc.log](https://github.com/Microsoft/vsts-tasks/files/1771534/Worker_20180301-095247-utc.log)
[logs_175.zip](https://github.com/Microsoft/vsts-tasks/files/1771525/logs_175.zip)

**Comment by swiec** [comment]
Uninstalling all Visual Studio products from test machine helped. IMHO, logging can be improved here, as no informative messages were passed to the user. Issue can be closed.

**Comment by cltshivash** [comment]
@swiec : Thanks for finding the root cause. We have seen reliability issues with the installation/validation of the install that happs each time with the DeployTestAgent task. We now recommend using the vstest V2 task for all testing needs both in build and release pipelines. Since you are on TFS 2017 Update, Build doesn't support multiple phases. 

With TFS 2018 Update2 (yet to be released), build also supports multiple phases and we highly recommend looking at vstest V2 task for all your testing needs in the CI/CD pipelines (and RFT and DTA tasks will be marked deprecated as well).  

[https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/](https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/ )
