### ISSUE TITLE
Is it possible to get the vstest.console.exe logs out of a hosted controller?

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#6586]
## Environment
- Server - VSTS
- Agent - Hosted

## Issue Description

My test task is hanging.  I would like to look at the dtaexecutionhost logs.  Is this possible when using a VSTS hosted controller?

**Comment by cltshivash** [comment]
@gregpakes If you are using data collection in your test task, please use the test platform tools installer task prior to the test task and set the version in test task as "Installed by test platform tools installer". There's a bug that is fixed in the latest VS update and is being rolled out.

To answer your query, setting "System.debug" to true will collect the test platform logs and it will be part of the build logs itself. Though it doesn't help in case of a hang.

**Comment by gregpakes** [comment]
I am already doing this.

It doesn’t help.
