### ISSUE TITLE
VsTest task fails even when all tests passed 

### ISSUE THREAD

**Issue by ceddlyburge** [Microsoft/vsts-tasks#6625]
## Environment
- Server - VSTS
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
        - https://res-tec-systems.visualstudio.com/RESProjects/_build/index?buildId=41&_a=summary

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name:
         -  Hosted VS2017

## Issue Description

VsTest task fails even when all tests passed 

2018-03-07T16:36:06.2657225Z Total tests: 683. Passed: 683. Failed: 0. Skipped: 0.
2018-03-07T16:36:06.2657614Z Test Run Failed.
2018-03-07T16:36:06.2657991Z Test execution time: 1.4368 Minutes
2018-03-07T16:36:06.4674851Z Results File: D:\a\1\s\TestResults\VssAdministrator_factoryvm-az250_2018-03-07_16_34_53.trx
2018-03-07T16:36:06.4862119Z ##[warning]Vstest failed with error. Check logs for failu********. There might be failed tests.
2018-03-07T16:36:06.5452051Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
2018-03-07T16:36:07.1181444Z Publishing test ********ults to test run '16'
2018-03-07T16:36:07.1181901Z Test ********ults remaining: 683. Test run id: 16
2018-03-07T16:36:07.2998877Z ##[error]VsTest task failed.
2018-03-07T16:36:07.5970156Z ##[section]Async Command Start: Publish test ********ults
2018-03-07T16:36:07.9892267Z Published Test Run : https://********-tec-systems.visualstudio.com/RESProjects/_TestManagement/Runs#runId=16&_a=runCharts
2018-03-07T16:36:07.9893185Z ##[section]Async Command End: Publish test ********ults
2018-03-07T16:36:07.9894937Z ##[section]Finishing: Test Assemblies

Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1

## Notes

I see that this issue has happened previously, and have tried running the "Test Assemblies" task twice in a row, but this has not helped.

**Comment by prawalagarwal** [comment]
@ceddlyburge  Hi, can you please reach out to devops_tools[at]microsoft[dot]com with detailed logs (the zip attached with the run). What kind of tests are these (MSTest, nunit etc) and are you observing this with all builds (or intermittently)?

**Comment by ceddlyburge** [comment]
Hi there, I have sent an email to devops_tools with the logs.

They are NUnit tests, and the problem occurs on all builds.

**Comment by ceddlyburge** [comment]
Actually, the email bounced with `authentication required; Delivery restriction check failed because the sender was not authenticated when sending to this group`

**Comment by prawalagarwal** [comment]
We got your mail. Will get back to you soon.

**Comment by harinelluri** [comment]
Any update on this, I'm also facing the same issue.

**Comment by ceddlyburge** [comment]
I figured this out with Prawal.

There was this line in the logs, which I hadn't noticed

`Error: Exception System.IO.FileLoadException, Exception thrown executing tests in blah\blah.dll`

When I ran vstest locally on my computer (`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe`)  for just this dll, then it output the following warning.

`Warning: No test is available in blah\blah.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.`

This warning was true, in that the dll didn't have any tests in it.

I excluded this dll from vstest / the `Test Assemblies` step and then it worked.

**Comment by prawalagarwal** [comment]
@ceddlyburge Thanks Cedd for reporting the analysis. Closing the issue.

**Comment by didaskein** [comment]
I have the same issue, and i also need to be more clear on the path to use in order to not use the /bin/ folder 

Working setting : 
![image](https://user-images.githubusercontent.com/13362276/59059771-129dff00-88a0-11e9-8f55-cbb92cac4d50.png)

Not working setting
![image](https://user-images.githubusercontent.com/13362276/59060034-73c5d280-88a0-11e9-84de-2fed88cb26e7.png)

The error i have before in Azure DevOps: 

vstest.console.exe 
"D:\a\1\s\MyProject\bin\Release\netcoreapp2.2\MyProject.UnitTests.dll"
"D:\a\1\s\MyProject\obj\Release\netcoreapp2.2\MyProject.UnitTests.dll"
/TestCaseFilter:"TestCategory=UnitTest"
/logger:"trx"
/TestAdapterPath:"D:\a\1\s"
Starting test execution, please wait...
Passed   TestLuisRegex_NoEntity
Passed   TestLuisRegex_OneEntity
Passed   TestLuisRegex_TwoEntity
Unable to find D:\a\1\s\MyProject.UnitTests\obj\Release\netcoreapp2.2\MyProject.UnitTests.deps.json. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk".

task is looking for .json in the obj folder ... so it's not using the good dll which is in /bin/ folder where i have the json file ;)
