### ISSUE TITLE
Why do tasks have local copy of the vso-node-api?

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#6787]
I'm looking at writing/customizing some tasks and I'm looking at the **DownloadBuildArtifacts** task as an example.

Why is there a local copy of the vso-node-api?  And where is it copied from?  I might be misunderstanding something, but isn't a local copy likely to go out of date and need more maintenance to keep it up to date?

**Comment by omeshp** [comment]
We forked local copy of vso-node-api because currently released one had some issues (https://github.com/Microsoft/vsts-node-api/issues/132). We limited testing of this local copy to DownloadBuildArtifacts task. We will be shifting to the released versions of these libraries once these know issues are fixed.

**Comment by bryanmacfarlane** [comment]
That example should be the only example of that.  

On the out of date point - even if it was not checked into the repair (as it's not with all other tasks in the repro), there is still an explicit goal to lock a specific version and more importantly, the dependency chain (dependencies of dependencies) so they do not slide.  Thus the package json lock files.  Not checking in just avoids muddying up the sources.

Closing as the answer is answered.
