### ISSUE TITLE
Linux agent DOTNET CORE test publish fails with configuration

### ISSUE THREAD

**Issue by philip-haugaard** [Microsoft/vsts-tasks#6797]
## Troubleshooting
tried various workarounds, if i override the -o folder and set it to the artifact folder i can get the test results

## Environment
VSTS - please message me for account details if needed
Hosted Linux Preview

## Issue Description
queue up a new DOTNET Test task v 2.* 
run with the following config:
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.Test.csproj'
    arguments: '-c $(BuildConfiguration)'

If i remove the -c $(BuildConfiguration) everything works as expected except that it is the wrong configuration

### Error logs
2018-03-26T11:21:02.9237290Z [command]/usr/bin/dotnet test /opt/vsts/work/1/s/tests/ReRouter.Service.Test/ReRouter.Service.Test.csproj -c release --logger trx --results-directory /opt/vsts/work/_temp
2018-03-26T11:21:17.1351444Z Build started, please wait...
2018-03-26T11:21:21.9994371Z CSC : error CS0016: Could not write to output file '/opt/vsts/work/1/s/src/XXX.Dto/bin/Release/netcoreapp2.0/XXX.Dto.xml' -- 'Could not find a part of the path '/opt/vsts/work/1/s/src/XXX.Dto/bin/Release/netcoreapp2.0/XXX.Dto.xml'.' [/opt/vsts/work/1/s/src/XXX.Dto/ReRouter.Dto.csproj]
2018-03-26T11:21:24.2698855Z ##[error]Error: /usr/bin/dotnet failed with return code: 1
2018-03-26T11:21:24.3080200Z ##[warning]No test result files were found.

**Comment by sachinma** [comment]
@cltshivash can you look at this issue?

**Comment by ShreyasRmsft** [comment]
@philip-haugaard does this repro for a simple test project with a dummy test or is it specific to the project you have. If the former is true can you please provide us with such a sample project so that we can repro the issue?

**Comment by ShreyasRmsft** [comment]
@philip-haugaard any updates here?

**Comment by jayaranigarg** [comment]
As we have not been provided with a repro project. CLosing this issue for now. Please feel free to re-open it if you hit it again.

**Comment by mix-inteligencia** [comment]
Hi. I have the same message with .NET Core task v2.* and I want to say:

Removing '-c $(BuildConfiguration)' from argument works, because the default value is "**Debug**" (look the value starts with **uppercase**) if you don't specify argument -c or --configuration

When you create your pipeline (build definition in my case) with a template, some variables are created, for example '$(BuildConfiguration)' (in Variables tab) with a value '**release**', look the  value is **lowercase**

If you set variable '$(BuildConfiguration)' to '**Release**' also works the build

For a build with dotnet, the options of argument -c --configuration are [**Debug**|**Release**]

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x#options

maybe the Template don't create a correct value

@philip-haugaard 

¡Un cordial saludo!

**Comment by sachinma** [comment]
I am opening  a new issue to track whether the default template should use the configuration name starting with capital letter. #7686

**Comment by DanteDiaz** [comment]
CSC : error CS0016: Could not write to output file '/codebuild/output/src750521459/src/SICIC/bin/Release/netcoreapp2.0/SICIC.General.Api.xml' -- 'Could not find a part of the path '/codebuild/output/src750521459/src/SICIC/bin/Release/netcoreapp2.0/SICIC.General.Api.xml'.' [/codebuild/output/src750521459/src/SICIC/SICIC.General.csproj]
