### ISSUE TITLE
Multiple task versioning

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#6924]
According to https://docs.microsoft.com/en-us/vsts/extend/develop/build-task-schema?view=vsts if you want multiple versions of the same task, you simply need to change the layout of your task.  I have been looking for examples of this within this repo but can't see any.

The powershell task has multiple versions, but looking at the task in this repo, it does not adhere to the format outlined in the link above.

Is the powershell task doing something special?  Is the information in the link above correct?

**Comment by bryanmacfarlane** [comment]
That's because tasks in this repo are no market place extensions.  Per the readme, they are in the box tasks.  They are ingested the same way tasks are uploaded via tfx-cli.

Ultimately, tasks "installed" in the build backend either via extensions (think of it as a vehicle / installer into backend) or directly via api / tfx-cli.  An extension carrying multiple versions is a vehicle to an append only backend.

**Comment by bryanmacfarlane** [comment]
This is a better question for vsts-task-lib
