### ISSUE TITLE
Azure File Copy doesn't overwrite existing files

### ISSUE THREAD

**Issue by Prashanth-PS** [Microsoft/vsts-tasks#6996]
It fails when we pass additional arguments such as /Y, /XO to update existing file/s in Blob storage through VSTS task

**Comment by rajatagrawal-dev** [comment]
@Prashanth-PS We already pass /XO and /Y while copying files to blob and so you shouldn't have to pass them. Can you share your debug logs? Add a variable 'system.debug' with value 'true' in your release variable and requeue the release to get the debug logs.

**Comment by Prashanth-PS** [comment]
Hi Rajat,

Initially we were using this task without any additional arguments, when Devs complained of files not getting updated with the latest content tried with /Y.
And I have got this issue with the version 1.0.110 observed on 12th Apr. Didn’t realize until today that it started working without any issues with the version 1.0.112.

Regards,
Prashanth PS

**Comment by jsutes** [comment]
I am having this same issue where old files are not overwritten with Azure File Copy v2.0.9.  I'm using version 2.* preview because I am uploading to a $web container for a static website.  Does the fix still need added to version 2?

I have the debug logs but I'm not sure if I should attach them since it looks like they have my subscription ids visible.

**Comment by rajatagrawal-dev** [comment]
@jsutes The v2 task should overwrite existing files if they have been modified, unless you have explicitly passed some optional argument (like /XN) which prevents that.
You can hide the subscription id and upload the logs here or send the them to RM_Customer_Queries [at] microsoft [dot] com.

**Comment by jsutes** [comment]
@rajatagrawal-dev Thank you for the quick reply.  I might have been having this issue because I had some releases that took place back-to-back on hosted machines.  I only have one pipeline so I know they happened in order, but maybe the file time stamps were too close together or some other issue with the time stamps that stopped the modified files from being copied.  I built and released again an hour later and all files were replaced as expected.

If I'm able to repeat the issue, then I'll send the logs and steps that cause it to happen.
