### ISSUE TITLE
VSTS Copying a Task from a PBI to another

### ISSUE THREAD

**Issue by AmirNaghibi** [Microsoft/vsts-tasks#7004]
Is there any way to copy Tasks from a PBI to another PBI in VSTS? I haven't found any resources in the VSTS documentation and from searching on google.

I know how to copy a PBI but if that PBI has some tasks, they will not be copied.

I don't want to manually create exact same tasks for different PBIs.

**Comment by ArieHein** [comment]
Not sure this is related to the built-in tasks offered by VSTS, seems its more of a general VSTS question.

As far as I know, you can move tasks between PBIs, but since everything is possible in PowerShell I'm sure you can add a VSTS PowerShell script task and in it, use TFS API to read a task and create a new one with same information just with different linked PBI.
If that is indeed how you wanted it to work, via a VSTS task

**Comment by bryanmacfarlane** [comment]
closing since not an issue with a task in this repo.

Sorry, can you clarify "PBI"?

**Comment by ArieHein** [comment]
PBI is Product Backlog Item, its a Work Item in VSTS/TFS to help manage the development work based on Scrum template, that's why at the beginning of my answer I wrote that I didnt think the question related to this repo.
