### ISSUE TITLE
Download Build Artifacts task fails to get Triggering build artifact

### ISSUE THREAD

**Issue by RichRowan** [Microsoft/vsts-tasks#7092]
There is the following warning on this page - https://docs.microsoft.com/en-gb/vsts/build-release/concepts/definitions/build/triggers?view=vsts

> **Build completion triggers**
> **Important**
> There's a known issue that blocks the ability to download artifacts from the triggering build and with the build variables that are part of this feature. We're working on the fix.

My builds never pick up the build the triggering builds artifacts. Is this issue being fixed. I couldn't find a relevant issue anywhere

## Environment
VSTS 
Private Agent 2.131.0 Windows 10

## Issue Description

Triggering build. Uploads to 994228
LOG:
2018-04-27T14:50:36.3264811Z File upload succeed.
2018-04-27T14:50:36.3265828Z Upload 'D:\agent\_work\5\a' to file container: '#/994228/edem'

Build triggered by previous build. See container number is the default number 993854.
LOG:
2018-04-27T14:51:46.8330396Z Downloading artifacts from: https://dem-solutions.visualstudio.com//_apis/resources/Containers/993854?itemPath=edem&isShallow=true&api-version=4.1-preview.4

**Comment by scottboehmer** [comment]
The fix for that issue with the build completion triggers should now be fully deployed. The underlying problem was a bug in VSTS where the environment variables with information about the triggering build were not sent to the agent, so it was not being tracked as an issue in this project and no change to the Download Build Artifacts task was needed.

If you are still seeing a problem downloading the artifacts from a triggering build, please let me know.
