### ISSUE TITLE
The url AzureResourceGroupDeploymentV2 help tooltip points to is a 404

### ISSUE THREAD

**Issue by leftler** [Microsoft/vsts-tasks#7220]
When following the link provided by
https://github.com/Microsoft/vsts-tasks/blob/8500e2cfbdd50b027c667b1017138b1fd90e618f/Tasks/AzureResourceGroupDeploymentV2/task.json#L6

this will redirect you to https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureResourceGroupDeployment/README.md which results in a 404. The correct url the shortener needs to point to is https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureResourceGroupDeploymentV2/README.md

**Comment by PaulMEdwards** [comment]
Same issue affects multiple tasks/docs due to #7181 by @stephenmichaelf.

Another example:

https://github.com/Microsoft/vsts-tasks/blob/da020f113efb77c18f0629a1b90a14cbf87f040a/Tasks/IISWebAppManagementOnMachineGroupV0/task.json#L7
directs to: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/IISWebAppManagementOnMachineGroup/README.md
is now: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/IISWebAppManagementOnMachineGroupV0/README.md

**Comment by bryanmacfarlane** [comment]
Yeah, the fwlink value needs to be updated (the reason the indirection exists :) ) . Ultimately, that should move to our public docs.

**Comment by bryanmacfarlane** [comment]
Individual task owners need to update their fwlinks (they have access to update them)

**Comment by rokmicrosoft** [comment]
Done. Closed.
