### ISSUE TITLE
dataSourceBindings of Azure SQL servers and SQL databases

### ISSUE THREAD

**Issue by william726** [Microsoft/vsts-tasks#7252]
I am developing a custom VSTS task which would like to populate the SQL servers and SQL databases in an Azure subscription in a drop down list.

I researched the list of dataSourceName that I can use to populate the values in a drop down list and I found this api https://{accountName}.visualstudio.com/_apis/serviceendpoint/types?api-version=5.0-preview.1.
Unfortunately I can't find SQL servers and SQL databases types from this api.

Can you please let me know if this is the correct place I can find all dataSourceName of supported Azure resource type, or please provide the doc of that.
And let me know if SQL servers and SQL databases are supported now. If not, do you have a timeline when they will be supported?

**Comment by bryanmacfarlane** [comment]
service endpoints and sql ...

**Comment by william726** [comment]
Let me elaborate more.

For example in the below pic, I can get all app service names (App1 to App9) from a drop down list after selecting the Azure subscription endpoint (Azure subscription 1). I believe it is because now VSTS API now supports getting app service name from an existing Azure subscription, by adding`        {
            "target": "WebAppName",
            "endpointId": "$(ConnectedServiceName)",
            "dataSourceName": "AzureRMWebAppNames"
        }` to dataSourceBindings object in task.json when developing the custom task.
![azure_service_endpoint_webapp](https://user-images.githubusercontent.com/5792666/40309574-f9b62b88-5cd7-11e8-9774-a35e2c2153e3.png)

My custom task requires both SQL server name and SQL database name, and I would like to achieve the same by setting up only an Azure subscription endpoint and all server names and database names in that subscription can be shown in a drop down list.

**Comment by omeshp** [comment]
@william726 If there are APIs in azure that provide list of SQL servers and SQL databases, the you can directly use those urls in the dataSourceBindings instead of depending on a DataSource. Have a look at
https://github.com/Microsoft/vsts-tasks/blob/dabc382bcc98750676c3f1a79c17f39c7fe47e26/Tasks/AzureMonitorV0/task.json#L91

**Comment by Ajay-MS** [comment]
@william726 

Following are the dataSourceBinding URLs:

**SQL Server**
{{{endpoint.url}}}subscriptions/{{{endpoint.subscriptionId}}}/providers/Microsoft.Sql/servers?api-version=2015-05-01-preview

**SQL Database**
{{{endpoint.url}}}subscriptions/{{{endpoint.subscriptionId}}}/resourceGroups/{{{ResourceGroupName}}}/providers/Microsoft.Sql/servers/{{{SqlServerName}}}/databases?api-version=2017-10-01-preview

Note: In order to fetch SQL databases two additional inputs are required :  ResourceGroupName and SQLServerName

**Comment by william726** [comment]
thanks it works!

**Comment by william726** [comment]
paste my code here for others as a reference

```
  "dataSourceBindings": [
    {
      "target": "ResourceGroupName",
      "endpointId": "$(ConnectedServiceName)",
      "dataSourceName": "AzureResourceGroups"
    },
    {
      "target": "SqlServerName",
      "endpointId": "$(ConnectedServiceName)",
      "endpointUrl": "{{endpoint.url}}subscriptions/{{endpoint.subscriptionId}}/resourceGroups/$(ResourceGroupName)/providers/Microsoft.Sql/servers?api-version=2015-05-01-preview",
      "resultSelector": "jsonpath:$.value[*].name"
    },
    {
      "target": "SqlDatabaseName",
      "endpointId": "$(ConnectedServiceName)",
      "endpointUrl": "{{endpoint.url}}subscriptions/{{endpoint.subscriptionId}}/resourceGroups/$(ResourceGroupName)/providers/Microsoft.Sql/servers/$(SqlServerName)/databases?api-version=2017-10-01-preview",
      "resultSelector": "jsonpath:$.value[*].name"
    }
  ]
```

**Comment by Ajay-MS** [comment]
@william726  
Thanks for the confirmation that you are unblocked and for the reference.
