### ISSUE TITLE
hosted machine caches

### ISSUE THREAD

**Issue by cythomli** [Microsoft/vsts-tasks#7254]
How do I use git-cache in VSTS build/release definition?

**Comment by bryanmacfarlane** [comment]
This repo is for tracking issues for the in the box tasks (/Tasks).

If you can elaborate on your scenario and what you're trying to accomplish, I can perhaps help redirect.  In absence of that, the general answer would be you can create a market place extension.

hope that helps.

**Comment by lisapalathingal** [comment]
I'm using npm install task in vsts hosted agent because I am using gulp tasks. Because, npm install is taking a long time, I am trying to use npm-cache to speed up the process. Here are the tasks currently I am using:

![image](https://user-images.githubusercontent.com/6519992/40273923-1c4edb90-5b7f-11e8-816f-200de29b84bf.png)
![image](https://user-images.githubusercontent.com/6519992/40273929-309d1fd0-5b7f-11e8-9fe3-06c5bc91a015.png)
![image](https://user-images.githubusercontent.com/6519992/40273934-3a8ef374-5b7f-11e8-93bb-b75e75f2a62b.png)

I think since I am using hosted agent, adding npm-cache isn't affecting the time. Please let me know if I am using it correctly or not. Thanks!

**Comment by bryanmacfarlane** [comment]
Hosted agent is a fresh machine every time so the git or npm caches won't have any value from build to build.

**Comment by licythom** [comment]
Thanks for your reply. Is there any way to speed up the process with hosted agent?
