### ISSUE TITLE
Visual Studio Test Platform Installer' task to have option to choose latest release

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-tasks#7460]
## Environment
- Server - VSTS or TFS on-premises? -> VSTS

- Agent - Hosted or Private: -> NA

## Issue Description

Visual Studio Test Platform Installer has only an option for the `Latest Pre-Release` but not for **latest release**:
![image](https://user-images.githubusercontent.com/9250262/41365529-87170112-6f31-11e8-8394-fc5c5348be12.png)

**Comment by ShreyasRmsft** [comment]
@bergmeister the task is still in pre-view. Right now Latest Pre-Release gets you the latest version (Stable or Preview). We will soon be adding an option for latest Stable also.

But do note that as of today if the latest version available is a stable version then choosing latest pre-release gets you that.

**Comment by ShreyasRmsft** [comment]
@bergmeister for all intents and purposes latest pre-release == latest release. 
These pre-release versions are also thoroughly tested internally.

Also if you are adamant on sticking to a specific stable version then you can use the specific version option.

**Comment by bergmeister** [comment]
Ok, thanks, understood. To me it sounds like it would be best to have 3 options:
- `Latest version` (no matter if release or pre-release) as currently present but rrenaming it to `Latest version (allow pre-release)` or something like that would make it clearer
- Latest released version as per this issue request
- Specific version as currently present

**Comment by ShreyasRmsft** [comment]
@bergmeister thank you for your feedback. We should picking this up in sometime when we get the task out of preview. @PBoraMSFT to take a look at the suggestion for naming the options.

**Comment by ShreyasRmsft** [comment]
@bergmeister Apologies. Will keep it open for tracking. The reason is that internally we track all our work items elsewhere and that customers sadly don't have visibility over that. Will take your feedback going forward and keep issues that have pending action items open and tag them appropriately.

Thank you for pointing this out :).

**Comment by PBoraMSFT** [comment]
@bergmeister - we have picked this up for execution. Apart from the latest stable / latest including pre-release options, we are also adding support for custom feeds and the task will come out of preview.
ETA for roll-out to all accounts is 3-4 weeks from now.

**Comment by PBoraMSFT** [comment]
@ShreyasRmsft - can you close the issue if the deployment rollout has started ?

**Comment by bergmeister** [comment]
@PBoraMSFT Thanks, I can see it already in my VSTS account :-)

**Comment by PBoraMSFT** [comment]
Closing the issue.

**Comment by fourpastmidnight** [comment]
So....how do I use a custom feed? There's ZERO documentation on this--ANYWHERE.

I selected to use a custom feed and used `http://mynugetserver.com/v3/index.json`, but acquiring the test tools failed: `WARNING: This version of nuget.exe does not support listing packages from source 'http://mynugetserver.com/v3/index.json'`.

We're using Azure DevOps Server 2019 (not sure if it's RTM or update 1 or 2). Task version `1.*`.

Please add documentation about what the URL should look like. Also, it might be a good idea to document the minimum version of Nuget.exe that is required and how to go about checking that you meet such a minimum requirement since these tasks are all "black boxes".....
