### ISSUE TITLE
tfx task

### ISSUE THREAD

**Issue by hangy** [Microsoft/vsts-tasks#7470]
We are currently using a custom release pipeline to publish a custom, internal VSTS task to our server.

1. `npm install tfx-cli`
2. `tfx login --username $(TfsUsername) --token $(TfsToken) --service-url $(TfsUrl)`
3. `tfx build tasks upload --task-path $(System.DefaultWorkingDirectory)/VSTS-Tasks/Tasks/CustomTask`
4. `tfx logout`

Right now, we have to specify TFS server, username, and token from build variables. It would be much more comfortable and secure (no manual renew of the token) if there were a vsts-task that at least logged into the TFS server using the agent's internal service URL and access token.

Would it be possible to integrate that into TFS?

**Comment by bryanmacfarlane** [comment]
Yeah, it would be easy.  If you look at the vsts-task-lib repo, there's a method that gives you a bearer token (generated per build) which represents the service account. Now, it's still up to users to give permissions to the build service account - by default it has reasonable access like read sources etc... 

The problems you would have with that task:
1.  You would have to give the build service account really, really elevated permissions (install an extension requires root pool admin).  That means all builds could do it.
2.  User using the task would have to add it and then grant those very elevated permissions 

For that reason, you would want to integrate a service endpoint into your task (which is securable).  Service endpoints are extensible as well so you could create a "task installer" endpoint type that has a username / PAT.  Strongly typing it makes it obvious what that elevated credential should be used for (and thus secured accordingly).  

Now, the task simply has a dropdown showing service endpoints of that type.  You secure that and only folks that have permissions to the endpoint can select it in their definition.

This issue is probably more appropriate in the vsts-task-lib repo.  Issues in this repo are for issues with the tasks in this repo ...

hth

**Comment by hangy** [comment]
Thank you very much for your thorough response. Considering the TFS build account does not have the elevated permissions, the suggested approach sounds like a really good idea! I am not too eager having to configure the service endpoint and it's credentials manually, but considering they do not change too often, that is still doable. Again, thanks for your response - I'm positive that we can get rid of the manual `cmd` calls using your guidance. :+1:
