### ISSUE TITLE
Deployment Contributor

### ISSUE THREAD

**Issue by eric-caslake** [Microsoft/vsts-tasks#7488]
When attempting to use a deployment contributor in the Azure SQL Database Deployment task on a hosted VSTS release to apply schema filters to the dacpac file, I am getting an error.  If I use the same parameters dacpac and deployment contributor from my local machine it runs without error.

Both the dacpac and the deployment contributor assembly exist in the artifacts folder.  But when the release runs I get the following output:

##Log
2018-06-15T14:56:21.8498163Z ##[error]*** An error occurred during deployment plan generation. Deployment cannot continue.
2018-06-15T14:56:21.8528339Z ##[error]Error SQL0: Required contributor with id 'XXX' could not be loaded.

Contributor initialization error.

2018-06-15T14:56:22.7022289Z ##[error]Azure SQL Dacpac task failed. Checkout how to troubleshoot failures https://aka.ms/sqlazuredeployreadme#troubleshooting.

**Comment by niadak** [comment]
Can you please share the debug logs with us? Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/pipelines/troubleshooting?view=vsts#get-logs-to-diagnose-problems

You can send the logs over email to RM_Customer_Queries@microsoft.com

**Comment by eric-caslake** [comment]
Did you get my response?  I'm assuming that I just need to be able to tell sqlpackage.exe where the contributor dll is, but don't know how to do that.

**Comment by niadak** [comment]
@eric-caslake , Sorry for late response and thanks for following up. We have received the logs and analyzing. You said it is working for you from local machine. 
Does it mean you have tried the task on a private agent or you run the command from the local machine? Can you configure a private agent on the local machine and check if it is working fine?
We are suspecting  it might be a windows security issue because the dll is getting downloaded to hosted agent (refer to https://archive.codeplex.com/?p=agilesqlclub ). In that case, it should fail for private agents also. Can you please check and verify.

**Comment by SumiranAgg** [comment]
Closing the issue as no response from customer. Please feel free to reopen if required.
