### ISSUE TITLE
Latest verison of AzureRM 6.3.0 persists existing SP credentials on agent server which makes subsequent Azure login fail

### ISSUE THREAD

**Issue by danielstocker** [Microsoft/vsts-tasks#7601]
## This issue relates to 
https://github.com/Microsoft/vsts-tasks/blob/cb067440eacfc3445665f4a44ffcb80adb1ce91c/Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1

## previous contributors to this file
@pragupta-ms 
@Ajay-MS 
@ericsciple 
@rajatagrawal-dev 
@arjgupta 

## Troubleshooting
This issue happens in a scenario where a build/release server is used for releases to Azure using more than one Service Principal with different roles/levels of access. 

A change in AzureRM 6.3.0 has meant that sessions are now automatically persisted for each user of AzureRM. (previously users had to run Enable-AzureRMContextAutosave)

After upgrading customers need to run Disable-AzureRmContextAutosave on all of their agent machines to revert back to the previous behaviour. 

Until they do this the code in InitializeFunctions.ps1 will cause additional contexts to be added, but PowerShell will default to the first context, leading to errors like the below: 

The client '{object id}' with object id {object id}' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/read' over scope '{resourceId}'.

In the above case the first service principal used by the build/release account is being reused rather than the service principal specified in the endpoint selection in TFS. 

## Environment
- Server - VSTS or TFS on-premises?
    In the scenario where I observed this, this was TFS 2017 on-prem with an on-prem release agent. The agent had the AzureRM module mentioned above installed. 
This would also happen in VSTS, if on-prem agents were used and 6.3.0 was installed without additional configuration, based on the testing my colleagues and I did. 

    - If using TFS on-premises, provide the version: 2017 U2 in this particular case. Latest vsts agent. 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: N/A

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: not applicable to hosted agent

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2012 R2, Azure PowerShell 6.3.0

## Suggested fix
I am not sure if this would cause any other problems, which is why I am not opening up a pull request, but an issue. 

What has helped in our case was to run "LogOut-AzureRMAccount" at the beginning of each release phase. Running it before adding an account in Initialize-AzureSubscription would fix this issue, but I do not know if it would cause any other issues. 

If this is a "won't fix" we should update agent/task related docs to include guidance about the new behaviour.

Please let me know if you need further information.

**Comment by danielstocker** [comment]
Hi everyone,
Is there any update on this?

**Comment by SumiranAgg** [comment]
@danielstocker Sorry for the late reply. We were investigating on the same since we are planning to upgrade to latest Azure powershell version on our hosted agents.
You are correct Azure PS persists existing SP credentials, which is causing issues. Using Clear-AzureRmContext with appropriate scope removes all contexts. Then  Disable-AzureRmContextAutosave and Add-AzureRmAccount works fine.
But as you said we might have to do risk analysis for the same. Will update this thread with any more updates.

**Comment by danielstocker** [comment]
Thanks @SumiranAgg 
Glad to hear this is being looked into at the right level of detail. Good luck with the analysis.

**Comment by SumiranAgg** [comment]
@danielstocker We are following up with PS team for resolution on issue https://github.com/Azure/azure-powershell/issues/6680
In the meanwhile we will be implementing a workaround. We will Clear-AzureRmContext before logging in Azure again. This will ensure the recently created context is used in the task.
Thanks for reporting the issue. Please reach out if you have any more insights.

**Comment by danielstocker** [comment]
Thanks for following up @SumiranAgg 
Am I right in assuming that this change won't get to TFS (on-prem) customers until the next TFS update as most of the Azure tasks are built in rather than delivered via a TFS/VSTS extension? 

Thanks again for all your efforts everyone

**Comment by samuelbcollie** [comment]
Is there any update on this? I'm upgrading my AzureRM to 6.7.0 at the beginning of my release pipeline, and I still get this error intermittently. I've tried 6.6.0 as well and this still happens occasionally. [Azure/azure-powershell#6680](https://github.com/Azure/azure-powershell/issues/6680) has been marked as closed, so is this a vsts issue?

**Comment by SumiranAgg** [comment]
@samuelbcollie What is the error you see? Is it in your custom script?
As per our testing the context persisting has been fixed in 6.7.0 PS version. Also in our Azure tasks we clear all context before logging in with service principal credentials.
In what scenario are you facing the issue?

**Comment by samuelbcollie** [comment]
I have an initial inline powershell task that installs AzureRM 6.7.0. Then I have several subsequent Azure Powershell tasks that validate secrets in our key vault, set app settings, etc. My last task is an Azure Powershell script task that completes the slot swap for our app services. This task has consistently been failing with the same login error. I found this strange because the problem only started recently. There was a 2-3 week period where this issue seemed fixed. None of our other azure powershell tasks do it, which is also strange, since the login problem used to bounce around between tasks. It also seems like I still have to clear the context manually at the end of each script. I have the following code appended to my powershell scripts:

`Clear-AzureRmContext -Scope Process
Clear-AzureRmContext -Scope CurrentUser -Force
Disable-AzureRmContextAutosave`

I put this at the end of each script when this login issue started happening. I tried taking it out once Azure 6.7.0 released, but this caused my second Azure powershell task to fail consistently with a login error. So for now, I'm leaving it. Currently, I'm leaning towards only using regular powershell tasks and logging in manually with each one, so I can circumvent the service principal.

**Comment by SumiranAgg** [comment]
@samuelbcollie Can you share debug logs for the failed task. Add System.debug variable with value true and redeploy.

**Comment by samuelbcollie** [comment]
Yes, but I would rather not upload them to a public thread. If there's an email that I could send them privately, that would be great. As a side note, I made a test pipeline that converted all of my azure powershell tasks to regular powershell tasks with a manual login, and that seemed to work fine.

**Comment by SumiranAgg** [comment]
You can share the failure logs at RM_Customer_Queries@microsoft.com
Corresponding to your powershell task pipeline, are you clearing context before each new login?

**Comment by samuelbcollie** [comment]
Yes. I'm clearing the context manually at the very end of each script.

**Comment by SumiranAgg** [comment]
@samuelbcollie Sorry fro late reply.
Are you still facing the issue?

**Comment by samuelbcollie** [comment]
@SumiranAgg No, this issue has been fixed for us. It turns out that while our release pipeline for our dev environment used Hosted VS2017 release agents, our other release pipelines were still using "Hosted" agents. After switching them to VS2017 agent pools, they started working.

**Comment by SumiranAgg** [comment]
Glad to know. Closing the issue.
