### ISSUE TITLE
Secrets in env variables in 'Docker - run an image' task

### ISSUE THREAD

**Issue by virtrixke** [Microsoft/vsts-tasks#7812]
## Environment
- Version: TFS 2018 (Update 1)
- Agent - Private on Windows 2016 using latest docker version 17.06.2-ee-13

## Issue Description

We want to test release a docker image with some env variables using 'Run an image - Docker' task. We define some secrets in the 'Variables' tab of the 'new release definition'. However, it does not seem possible to use these secrets in the 'Environment Variables' section of the docker run image task. We use it in the form of MQ_SECRET=$(MQ_SecPass).

**Comment by The-real-Urb** [comment]
Same problem here. Using it in the form of
MQ_SECRET
in the 'Environment Variables' section doesn't work either.
The env variable is not set in the container.

**Comment by vithati** [comment]
@virtrixke @The-real-Urb, I have tried your scenario, setting release secrets variables in the 'Environment Variables'. it is working for me, i see environment variable properly set in docker container. Can you explian issue and your scenario more? Can you share the logs and Dockerfile.

**Comment by The-real-Urb** [comment]
@vithati , I have it working fine now. I had to change 2 things.

1. removed and added the secret to TFS again. It was blank for some reason :-s
2. In the 'Environment Variable' section, I had to put "SecretPassword=$(SecretPassword)" instead of "SecretPassword".

Now the secret is blanked out perfectly in the logs:
`2018-07-25T06:51:11.4532000Z ##[debug]C:\Program Files\Docker\docker.exe arg: ["-e","SecretPassword=********"]`

For me, this is a non issue. Thx!

**Comment by vithati** [comment]
@virtrixke, please reopen bug if you faces any issue.
