### ISSUE TITLE
How to deploy test agent in TFS 2018 to run CodedUI tests?

### ISSUE THREAD

**Issue by Selvaraj1989** [Microsoft/vsts-tasks#8082]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server -TFS on-premises
    
    - 2018 Update 3
    
- Agent - Private: 
    
    -OS version : Windows Server 2016 (10.0.14393) and Agent Version : 2.136.1

## Issue Description

Since "Deploy test agent" task got deprecated in TFS 2018, there is no way to run the test agent in interactive mode automatically (like it did in TFS 2015 using Deploy Test agent task) to execute the CodedUI tests. 

Please let me know if there is any alternative way to run TFS 2018 test agent in interactive mode.

Thanks
Selvaraj C

**Comment by abhishkk** [comment]
@Selvaraj1989 
You can start test agent in interactive mode. Check [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts#choose-interactive-or-service-mode) link for more details.
Since "Deploy test agent" task is deprecated now, you need to use "Visual studio test" [task](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts#choose-interactive-or-service-mode).

**Comment by abhishkk** [comment]
Closing this issue. Please re-open in case you need further assistance.

**Comment by abhishkk** [comment]
Closing this issue. Please re-open in case you need further assistance.
