### ISSUE TITLE
Azure SQL Database Deployment - Invoke-sqlcmd fails when password has special characters

### ISSUE THREAD

**Issue by debashis1982** [Microsoft/vsts-tasks#8140]
Task - Azure SQL Database Deployment
Version - 1
Agent - Hosted
Phase - Release
Issue Description - On trying to run Inline SQL script we get login failed error if the SQL Password contains special characters like semi-colon(;)
Solution - Enclose user ID and password between single quotes when executing Invoke-sqlcmd command through this task. Thanks!

**Comment by Ajay-MS** [comment]
@debashis1982 

I really appreciate your efforts to raise PR in order to fix this Bug. 

Since we are planning to deploy this fix with the deployment of the current sprint. Today is the second last day for the check. And we have to address a few more scenario along with your fix. So, I have addressed the fix for this issue as below mentioned PR 
PR - #8155
