### ISSUE TITLE
Add a channels option to CondaEnvironment

### ISSUE THREAD

**Issue by asmeurer** [Microsoft/vsts-tasks#8474]
The it would be useful to have a `channels` option to `CondaEnvironment` that lets you specify channels that get added (either as `-c` or using `conda config`, I'm not sure which is more appropriate). 

You can already do this with `createOptions: "-c channel_name"`, but since something like `-c conda-forge` is so common for conda, it would be useful to have this as its own flag.

**Comment by brcrista** [comment]
I think this is a fair point.  It's a bit of a hack, but assuming you want the channel to be highest priority for the whole list of installs, you can actually just do `packageSpecs: -c conda-forge <packages ...>` and it should work fine.

If you want to do different installs from different channels, now you're in script-land anyway, since the task is really designed for activating an environment.

So I'm going to say this is "by design" for now, but I will keep it in mind.  We may end up revisiting our channels story someday 😉
